// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Afghanistan (AF): 34 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const AF: SubdivisionTable = {
  country: "AF",
  types: ["province"],
  typesJa: ["州"],
  rows: `BAL|Balkh|バルフ州|0
BAM|Bamyan|バーミヤーン州|0
BDG|Badghis|バードギース州|0
BDS|Badakhshan|バダフシャーン州|0
BGL|Baghlan|バグラーン州|0
DAY|Daykundi|ダーイクンディー州|0
FRA|Farah|ファラー州|0
FYB|Faryab|ファーリヤーブ州|0
GHA|Ghazni|ガズニー州|0
GHO|Ghōr|ゴール州|0
HEL|Helmand|ヘルマンド州|0
HER|Herat|ヘラート州|0
JOW|Jowzjan|ジューズジャーン州|0
KAB|Kabul|カーブル州|0
KAN|Kandahar|カンダハール州|0
KAP|Kapisa|カーピーサー州|0
KDZ|Kunduz|クンドゥーズ州|0
KHO|Khost|ホースト州|0
KNR|Kunar|クナル州|0
LAG|Laghman|ラグマーン州|0
LOG|Logar|ローガル州|0
NAN|Nangarhar|ナンガルハール州|0
NIM|Nimruz|ニームルーズ州|0
NUR|Nuristan|ヌーリスターン州|0
PAN|Panjshir|パンジシール州|0
PAR|Parwan|パルヴァーン州|0
PIA|Paktia|パクティヤー州|0
PKA|Paktika|パクティーカー州|0
SAM|Samangan|サマンガーン州|0
SAR|Sar-e Pol|サーレポル州|0
TAK|Takhar|タハール州|0
URU|Urozgan|ウルーズガーン州|0
WAR|Maidan Wardak|ヴァルダク州|0
ZAB|Zabul|ザーブル州|0`,
};

export { AF };
