// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Albania (AL): 12 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const AL: SubdivisionTable = {
  country: "AL",
  types: ["county"],
  typesJa: ["州"],
  rows: `01|Berat County|ベラト州|0
02|Durrës County|ドゥラス州|0
03|Elbasan County|エルバサン州|0
04|Fier County|フィエル州|0
05|Gjirokastër County|ジロカストラ州|0
06|Korçë County|コルチャ州|0
07|Kukës County|クケス州|0
08|Lezhë County|レジャ州|0
09|Dibër County|ディブラ州|0
10|Shkodër County|シュコドラ州|0
11|Tirana County|ティラナ州|0
12|Vlorë County|ヴロラ州|0`,
};

export { AL };
