// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Armenia (AM): 11 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const AM: SubdivisionTable = {
  country: "AM",
  types: ["city","province"],
  typesJa: [null,"地方"],
  rows: `AG|Aragatsotn|アラガツォトゥン地方|1
AR|Ararat|アララト地方|1
AV|Armavir|アルマヴィル地方|1
ER|Yerevan|エレバン|0
GR|Gegharkunik|ゲガルクニク地方|1
KT|Kotayk|コタイク地方|1
LO|Lori|ロリ地方|1
SH|Shirak|シラク地方|1
SU|Syunik|シュニク地方|1
TV|Tavush|タヴシュ地方|1
VD|Vayots Dzor|ヴァヨツ・ゾル地方|1`,
};

export { AM };
