// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Angola (AO): 18 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const AO: SubdivisionTable = {
  country: "AO",
  types: ["province"],
  typesJa: [null],
  rows: `BGO|Bengo|ベンゴ州|0
BGU|Benguela|ベンゲラ州|0
BIE|Bié|ビエ州|0
CAB|Cabinda|カビンダ|0
CCU|Cuando Cubango|クアンド・クバンゴ州|0
CNN|Cunene|クネネ州|0
CNO|Cuanza Norte|クアンザ・ノルテ州|0
CUS|Cuanza Sul|クアンザ・スル州|0
HUA|Huambo|ウアンボ州|0
HUI|Huíla|ウイラ州|0
LNO|Lunda Norte|ルンダ・ノルテ州|0
LSU|Lunda Sul|ルンダ・スル州|0
LUA|Luanda|ルアンダ州|0
MAL|Malanje|マランジェ州|0
MOX|Moxico|モシコ州|0
NAM|Namibe|ナミベ州|0
UIG|Uíge|ウイジェ州|0
ZAI|Zaire|ザイーレ州|0`,
};

export { AO };
