// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Austria (AT): 9 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const AT: SubdivisionTable = {
  country: "AT",
  types: ["city","state"],
  typesJa: [null,"州"],
  rows: `1|Burgenland|ブルゲンラント州|1
2|Carinthia|ケルンテン州|1
3|Lower Austria|ニーダーエスターライヒ州
4|Upper Austria|オーバーエスターライヒ州|1
5|Salzburg|ザルツブルク州|1
6|Styria|シュタイアーマルク州|1
7|Tyrol|チロル州|1
8|Vorarlberg|フォアアールベルク州|1
9|Vienna|ウィーン|0`,
};

export { AT };
