// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Australia (AU): 8 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const AU: SubdivisionTable = {
  country: "AU",
  types: ["state","territory"],
  typesJa: ["州",null],
  rows: `ACT|Australian Capital Territory|オーストラリア首都特別地域|1
NSW|New South Wales|ニューサウスウェールズ州|0
NT|Northern Territory|ノーザンテリトリー|1
QLD|Queensland|クイーンズランド州|0
SA|South Australia|南オーストラリア州|0
TAS|Tasmania|タスマニア州|0
VIC|Victoria|ビクトリア州|0
WA|Western Australia|西オーストラリア州|0`,
};

export { AU };
