// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Azerbaijan (AZ): 78 subdivisions, at level 1 and 2.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const AZ: SubdivisionTable = {
  country: "AZ",
  types: ["capital-district","city","district","municipality","republic"],
  typesJa: [null,null,null,null,"自治共和国"],
  rows: `ABS|Absheron|アブシェロン県|2
AGA|Agstafa|アグスタファ県|2
AGC|Aghjabadi|アグジャバディ県|2
AGM|Agdam|アグダム県|2
AGS|Agdash|アグダシュ県|2
AGU|Agsu|アグス県|2
AST|Astara|アスタラ県|2
BA|Baku|バクー|0
BAB|Babek|バベク県|2|NX
BAL|Balakan|バラキャン県|2
BAR|Barda|バルダ県|2
BEY|Beylagan|ベイラガン県|2
BIL|Bilasuvar|ビラスヴァル県|2
CAB|Jabrayil|ジャブライル県|2
CAL|Jalilabad|ジャリラバド県|2
CUL|Julfa|ジュルファ県|2|NX
DAS|Dashkasan|ダシュキャサン県|2
FUZ|Fizuli|フュズリ県|2
GA|Ganja|ギャンジャ
GAD|Gadabay|ガダバイ県|2
GOR|Goranboy|ゴランボイ県|2
GOY|Goychay|ギョイチャイ県|2
GYG|Goygol|ギョイギョル県|2
HAC|Hajigabul|ハジュガブル県|2
IMI|Imishli|イミシュリ県|2
ISM|Ismailli|イスマイル県|2
KAL|Kalbajar|カルバジャル県|2
KAN|Kangarli|キャンギャルリ県|2|NX
KUR|Kurdamir|キュルダミル県|2
LA|Lankaran|レンキャラン県
LAC|Lachin|ラチン県|2
LAN|Lankaran District|ランカラン|2
LER|Lerik|レリク県|2
MAS|Masally|マサッル県|2
MI|Mingachevir|ミンゲチェヴィル
NA|Naftalan|ナフタラン|3
NEF|Neftchala|ネフトチャラ県|2
NV|Nakhchivan|ナヒチェヴァン|1|NX
NX|Nakhchivan AR|ナヒチェヴァン自治共和国|4
OGU|Oghuz|オグズ県|2
ORD|Ordubad|オルドゥバド県|2|NX
QAB|Qabala|ガバラ県|2
QAX|Qakh|ガフ県|2
QAZ|Qazakh|ガザフ県|2
QBA|Quba|クバ県|2
QBI|Qubadli|グバドリ県|2
QOB|Gobustan|ゴブスタン県|2
QUS|Qusar|クサル県|2
SA|Shaki|シャキ
SAB|Sabirabad|サビラバド県|2
SAD|Sadarak|サダラク県|2|NX
SAH|Shahbuz|シャフブズ県|2|NX
SAK|Shaki District|シャキ県|2
SAL|Salyan|サルヤン県|2
SAR|Sharur|シャルル県|2|NX
SAT|Saatly|サアトル|2
SBN|Shabran|ダヴァヒ県|2
SIY|Siazan|シアザン県|2
SKR|Shamkir|シャムキル県|2
SM|Sumqayit|スムガイト
SMI|Shamakhi|シャマフ県|2
SMX|Samukh|サムフ県|2
SR|Shirvan|シルヴァン (市)
SUS|Shusha|シュシャ県|2
TAR|Tartar|タルタル県|2
TOV|Tovuz|トヴズ県|2
UCA|Ujar|ウジャル県|2
XA|Stepanakert|ステパナケルト|1
XAC|Khachmaz|ハヒマズ県|2
XCI|Khojali|ホジャリ県|2
XIZ|Khizi|ヒジ県|2
XVD|Khojavend|ホジャヴェンド県|2
YAR|Yardymli|ヤルディムリ県|2
YE|Yevlakh|イェヴラフ
YEV|Yevlakh District|イェヴラフ県|2
ZAN|Zangilan|ザンギラン県|2
ZAQ|Zaqatala|ザガタラ県|2
ZAR|Zardab|ザルダブ県|2`,
};

export { AZ };
