// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Barbados (BB): 11 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const BB: SubdivisionTable = {
  country: "BB",
  types: ["parish"],
  typesJa: [null],
  rows: `01|Christ Church|クライスト・チャーチ|0
02|Saint Andrew|セント・アンドリュー|0
03|Saint George|セント・ジョージ|0
04|Saint James|セント・ジェームズ|0
05|Saint John|セント・ジョン|0
06|Saint Joseph|セント・ジョセフ|0
07|Saint Lucy|セント・ルーシー|0
08|Saint Michael|セント・マイケル|0
09|Saint Peter|セント・ペーター|0
10|Saint Philip|セント・フィリップ|0
11|Saint Thomas|セント・トーマス|0`,
};

export { BB };
