// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Bangladesh (BD): 72 subdivisions, at level 1 and 2.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const BD: SubdivisionTable = {
  country: "BD",
  types: ["district","division"],
  typesJa: ["県","区"],
  rows: `01|Bandarban|バンドルボン県|0|B
02|Barguna|ボルグナ県|0|A
03|Bogra|ボグラ県|0|E
04|Brahmanbaria|ブラモンバリア県|0|B
05|Bagerhat|バゲルハット県|0|D
06|Barisal Division|バリサル県|0|A
07|Bhola|ボラ県|0|A
08|Comilla|コミラ県|0|B
09|Chandpur|チャンドプール県|0|B
10|Chittagong|チッタゴン県|0|B
11|Cox’s Bazar|コックスバザール県|0|B
12|Chuadanga|チュアダンガ県|0|D
13|Dhaka|ダッカ県|0|C
14|Dinajpur|ディナジプール県|0|F
15|Faridpur|ファリドプル県|0|C
16|Feni|フェニー県|0|B
17|Gopalganj|ゴパルガンジュ県|0|C
18|Gazipur|ガジプル県|0|C
19|Gaibandha|ガイバンダ県|0|F
20|Habiganj|ハビガンジ県|0|G
21|Jamalpur|ジャマルプル県|0|H
22|Jessore|ジョソール県|0|D
23|Jhenaidah|ジェナイダ県|0|D
24|Joypurhat|ジョイプールハット県|0|E
25|Jhalokati|ジョルコタ県|0|A
26|Kishoreganj|キショレガンジュ県|0|C
27|Khulna|クルナ県|0|D
28|Kurigram|クリグラム県|0|F
29|Khagrachari|カグラチュリ県|0|B
30|Kushtia|クスティア県|0|D
31|Lakshmipur|ラクシュミプール県|0|B
32|Lalmonirhat|ラルモニールハット県|0|F
33|Manikganj|マニクガンジュ県|0|C
34|Mymensingh|ミメンシング県|0|H
35|Munshiganj|ムンシガンジュ県|0|C
36|Madaripur|マダリプル県|0|C
37|Magura|マグラ県|0|D
38|Maulvi Bazar|マウルビバザール県|0|G
39|Meherpur|メヘルプル県|0|D
40|Narayanganj|ナラヤンガンジュ県|0|C
41|Netrokona|ネトラコタ県|0|H
42|Narsingdi|ナルシングディ県|0|C
43|Narail|ナライル県|0|D
44|Natore|ナトール県|0|E
45|Nawabganj|ナワバンジ県|0|E
46|Nilphamari|ニルファマリ県|0|F
47|Noakhali|ノアカリ県|0|B
48|Naogaon|ナオガオン県|0|E
49|Pabna|パブナ県|0|E
50|Pirojpur|ピロジプール県|0|A
51|Patuakhali|パトゥアカリ県|0|A
52|Panchagarh|ポンテョゴル県|0|F
53|Rajbari|ラジバリ県|0|C
54|Rajshahi|ラジシャヒ県|0|E
55|Rangpur|ロンプール県|0|F
56|Rangamati Hill|ランガマティ県|0|B
57|Sherpur|シェルプル県|0|H
58|Satkhira|シャスキラ県|0|D
59|Sirajganj|シラジガンジ県|0|E
60|Sylhet|シレット県|0|G
61|Sunamganj|スナマンジ県|0|G
62|Shariatpur|シャリアトプル県|0|C
63|Tangail|タンガイル県|0|C
64|Thakurgaon|タクルガオン県|0|F
A|Barisal|バリサル管区|1
B|Chittagong Division|チッタゴン管区|1
C|Dhaka Division|ダッカ管区|1
D|Khulna Division|クルナ管区|1
E|Rajshahi Division|ラジシャヒ管区|1
F|Rangpur Division|ロンプール管区|1
G|Sylhet Division|シレット管区|1
H|Mymensingh Division|マイメンシン管区|1`,
};

export { BD };
