// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Burkina Faso (BF): 58 subdivisions, at level 1 and 2.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const BF: SubdivisionTable = {
  country: "BF",
  types: ["province","region"],
  typesJa: [null,null],
  rows: `01|Boucle du Mouhoun|ブクル・デュ・ムウン地方|1
02|Cascades|カスカード地方|1
03|Centre|中部地方 (ブルキナファソ)|1
04|Centre-Est|中東部地方 (ブルキナファソ)|1
05|Centre-Nord|中北部地方 (ブルキナファソ)|1
06|Centre-Ouest|中西部地方 (ブルキナファソ)|1
07|Centre-Sud|中南部地方 (ブルキナファソ)|1
08|Est|東部地方 (ブルキナファソ)|1
09|Hauts-Bassins|上流域地方|1
10|Nord|北部地方 (ブルキナファソ)|1
11|Plateau-Central|中央大地地方|1
12|Sahel|サヘル地方|1
13|Sud-Ouest|南西地方 (ブルキナファソ)|1
BAL|Balé|バレ県|0|01
BAM|Bam|バム県|0|05
BAN|Banwa|バンワ県|0|01
BAZ|Bazèga|バゼガ県|0|07
BGR|Bougouriba|ブグリバ県|0|13
BLG|Boulgou|ブルグ県|0|04
BLK|Boulkiemdé|ブルキアンデ県|0|06
COM|Comoé|コモエ県|0|02
GAN|Ganzourgou|ガンズル県|0|11
GNA|Gnagna|グナグナ州|0|08
GOU|Gourma|グルマ県|0|08
HOU|Houet|ウエ県|0|09
IOB|Ioba|イオバ県|0|13
KAD|Kadiogo|カディオゴ県|0|03
KEN|Kénédougou|ケネドゥグ県|0|09
KMD|Komondjari|コモンジャリ県|0|08
KMP|Kompienga|コンピエンガ県|0|08
KOP|Koulpélogo|クルペロゴ県|0|04
KOS|Kossi|コッシ県|0|01
KOT|Kouritenga|クリテンガ県|0|04
KOW|Kourwéogo|クルウェゴ県|0|11
LER|Léraba|レラバ県|0|02
LOR|Loroum|ロルム県|0|10
MOU|Mouhoun|ムフン県|0|01
NAM|Namentenga|ナメテンガ県|0|05
NAO|Nahouri|ナウリ県|0|07
NAY|Nayala|ナヤラ県|0|01
NOU|Noumbiel|ヌンビエル県|0|13
OUB|Oubritenga|ウブリテンガ県|0|11
OUD|Oudalan|ウダラン県|0|12
PAS|Passoré|パッソレ県|0|10
PON|Poni|ポニ県|0|13
SEN|Séno|セノ県|0|12
SIS|Sissili|シッシリ県|0|06
SMT|Sanmatenga|サンマテンガ県|0|05
SNG|Sanguié|サンギエ県|0|06
SOM|Soum|スム県|0|12
SOR|Sourou|スル県|0|01
TAP|Tapoa|タポア県|1|08
TUI|Tuy|トゥイ県|0|09
YAG|Yagha|ヤガ県|0|12
YAT|Yatenga|ヤテンガ県|0|10
ZIR|Ziro|ジロ県|0|06
ZON|Zondoma|ゾンドマ県|0|10
ZOU|Zoundwéogo|ズンドウェオゴ県|0|07`,
};

export { BF };
