// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Bulgaria (BG): 28 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const BG: SubdivisionTable = {
  country: "BG",
  types: ["oblast"],
  typesJa: [null],
  rows: `01|Blagoevgrad|ブラゴエヴグラト州|0
02|Burgas|ブルガス州|0
03|Varna|ヴァルナ州|0
04|Veliko Tarnovo|ヴェリコ・タルノヴォ州|0
05|Vidin|ヴィディン州|0
06|Vratsa|ヴラツァ州|0
07|Gabrovo|ガブロヴォ州|0
08|Dobrich|ドブリチ州|0
09|Kardzhali|クルジャリ州|0
10|Kyustendil|キュステンディル州|0
11|Lovech|ロヴェチ州|0
12|Montana|モンタナ州 (ブルガリア)|0
13|Pazardzhik|パザルジク州|0
14|Pernik|ペルニク州|0
15|Pleven|プレヴェン州|0
16|Plovdiv|プロヴディフ州|0
17|Razgrad|ラズグラト州|0
18|Ruse|ルセ州|0
19|Silistra|シリストラ州|0
20|Sliven|スリヴェン州|0
21|Smolyan|スモリャン州|0
22|Sofia|ソフィア市州|0
23|Sofia District|ソフィア州|0
24|Stara Zagora|スタラ・ザゴラ州|0
25|Targovishte|トゥルゴヴィシテ州|0
26|Haskovo|ハスコヴォ州|0
27|Shumen|シュメン州|0
28|Yambol|ヤンボル州|0`,
};

export { BG };
