// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Bahrain (BH): 4 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const BH: SubdivisionTable = {
  country: "BH",
  types: ["governorate"],
  typesJa: ["県"],
  rows: `13|Capital|首都県|0
14|Southern|南部県|0
15|Muharraq|ムハッラク県|0
17|Northern|北部県|0`,
};

export { BH };
