// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Benin (BJ): 12 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const BJ: SubdivisionTable = {
  country: "BJ",
  types: ["department"],
  typesJa: ["県"],
  rows: `AK|Atakora|アタコラ県|0
AL|Alibori|アリボリ県|0
AQ|Atlantique|アトランティック県|0
BO|Borgou|ボルグー県|0
CO|Collines|コリネス県|0
DO|Donga|ドンガ県|0
KO|Kouffo|クッフォ県|0
LI|Littoral|リトラル県|0
MO|Mono|モノ県|0
OU|Ouémé|ウェメ県|0
PL|Plateau|プラトー県|0
ZO|Zou|ズー県|0`,
};

export { BJ };
