// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Brazil (BR): 27 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const BR: SubdivisionTable = {
  country: "BR",
  types: ["capital-district","state"],
  typesJa: ["連邦直轄区","州"],
  rows: `AC|Acre|アクレ州|1
AL|Alagoas|アラゴアス州|1
AM|Amazonas|アマゾナス州|1
AP|Amapá|アマパー州|1
BA|Bahia|バイーア州|1
CE|Ceará|セアラー州|1
DF|Federal District|ブラジリア連邦直轄区|0
ES|Espírito Santo|エスピリトサント州|1
GO|Goiás|ゴイアス州|1
MA|Maranhão|マラニョン州|1
MG|Minas Gerais|ミナスジェライス州|1
MS|Mato Grosso do Sul|マットグロッソ・ド・スル州|1
MT|Mato Grosso|マットグロッソ州|1
PA|Pará|パラー州|1
PB|Paraíba|パライバ州|1
PE|Pernambuco|ペルナンブーコ州|1
PI|Piauí|ピアウイ州|1
PR|Paraná|パラナ州|1
RJ|Rio de Janeiro|リオデジャネイロ州|1
RN|Rio Grande do Norte|リオグランデ・ド・ノルテ州|1
RO|Rondônia|ロンドニア州|1
RR|Roraima|ロライマ州|1
RS|Rio Grande do Sul|リオグランデ・ド・スル州|1
SC|Santa Catarina|サンタカタリーナ州|1
SE|Sergipe|セルジッペ州|1
SP|São Paulo|サンパウロ州|1
TO|Tocantins|トカンティンス州|1`,
};

export { BR };
