// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Bahamas (BS): 32 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const BS: SubdivisionTable = {
  country: "BS",
  types: ["capital-district","district"],
  typesJa: [null,null],
  rows: `AK|Acklins|アクリンズ|1
BI|Bimini|ビミニ|1
BP|Black Point|ブラック・ポイント|1
BY|Berry Islands|ベリー諸島|1
CE|Central Eleuthera|セントラル・エルーセラ|1
CI|Cat Island|キャット島|1
CK|Crooked Island|クルックド島|1
CO|Central Abaco|セントラル・アバコ|1
CS|Central Andros|セントラル・アンドロス|1
EG|East Grand Bahama|イースト・グランド・バハマ|1
EX|Exuma|エグズーマ|1
FP|Freeport|フリーポート|1
GC|Grand Cay|グランド・キー|1
HI|Harbour Island|ハーバー島|1
HT|Hope Town|ホープ・タウン|1
IN|Inagua|イナグア島|1
LI|Long Island|ロング島
MC|Mangrove Cay|マングローブ・キー|1
MG|Mayaguana|マヤグアナ島|1
MI|Moore’s Island|モーレイズ島|1
NE|North Eleuthera|ノース・エルーセラ|1
NO|North Abaco|ノース・アバコ|1
NP|New Providence|ニュープロビデンス|0
NS|North Andros|ノース・アンドロス|1
RC|Rum Cay|ラム・キー|1
RI|Ragged Island|ラグド島|1
SA|South Andros|サウス・アンドロス|1
SE|South Eleuthera|サウス・エルーサラ|1
SO|South Abaco|サウス・アバコ|1
SS|San Salvador|サン・サルバドル島|1
SW|Spanish Wells|スパニッシュ・ウェルズ|1
WG|West Grand Bahama|ウェスト・グランド・バハマ|1`,
};

export { BS };
