// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Bhutan (BT): 20 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const BT: SubdivisionTable = {
  country: "BT",
  types: ["district"],
  typesJa: ["県"],
  rows: `11|Paro|パロ県|0
12|Chukha|チュカ県|0
13|Haa|ハ県|0
14|Samtse|サムツェ県|0
15|Thimphu|ティンプー県|0
21|Tsirang|チラン県|0
22|Dagana|ダガナ県|0
23|Punakha|プナカ県|0
24|Wangdue Phodrang|ワンデュ・ポダン県|0
31|Sarpang|サルパン県|0
32|Trongsa|トンサ県|0
33|Bumthang|ブムタン県|0
34|Zhemgang|シェムガン県|0
41|Trashigang|タシガン県|0
42|Mongar|モンガル県|0
43|Pemagatshel|ペマガツェル県|0
44|Lhuntse|ルンツェ県|0
45|Samdrup Jongkhar|サムドゥプ・ジョンカル県|0
GA|Gasa|ガサ県|0
TY|Trashiyangtse|タシ・ヤンツェ県|0`,
};

export { BT };
