// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Botswana (BW): 16 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const BW: SubdivisionTable = {
  country: "BW",
  types: ["city","district"],
  typesJa: [null,"地区"],
  rows: `CE|Central|セントラル地区|1
CH|Chobe|チョベ地区|1
FR|Francistown|フランシスタウン|0
GA|Gaborone|ハボローネ|0
GH|Ghanzi|ハンツィ地区|1
JW|Jwaneng|ジュワネン|0
KG|Kgalagadi|カラハリ地区|1
KL|Kgatleng|カトレン地区|1
KW|Kweneng|クウェネン地区|1
LO|Lobatse|ロバツェ|0
NE|North East|ノースイースト地区|1
NW|North West|ノースウェスト地区|1
SE|South East|サウスイースト地区|1
SO|Southern|サザン地区|1
SP|Selibe Phikwe|セレビ・ピクウェ|0
ST|Sowa Town|ソワ`,
};

export { BW };
