// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Belarus (BY): 7 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const BY: SubdivisionTable = {
  country: "BY",
  types: ["city","region"],
  typesJa: [null,"州"],
  rows: `BR|Brest|ブレスト州|1
HM|Minsk|ミンスク|0
HO|Homel|ホメリ州|1
HR|Hrodna|フロドナ州|1
MA|Magileu|マヒリョウ州|1
MI|Minsk Region|ミンスク州|1
VI|Vitebsk|ヴィーツェプスク州|1`,
};

export { BY };
