// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Congo - Kinshasa (CD): 26 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place, Japanese names CLDR lacks

import type { SubdivisionTable } from "../../rows";

const CD: SubdivisionTable = {
  country: "CD",
  types: ["capital-district","district","province"],
  typesJa: [null,"州","州"],
  rows: `BC|Bas-Congo|コンゴ中央州|2
BU|Bas-Uélé|低ウエレ州|2
EQ|Équateur|赤道州|2
HK|Haut-Katanga|上カタンガ州|2
HL|Haut-Lomami|上ロマミ州|2
HU|Haut-Uélé|高ウエレ州|2
IT|Ituri|イトゥリ州|2
KC|Kasaï Central|ルルア州|2
KE|Kasaï-Oriental|東カサイ州|2
KG|Kwango|クワンゴ州|2
KL|Kwilu|クウィル州|2
KN|Kinshasa|キンシャサ|0
KS|Kasaï|カサイ州|1
LO|Lomami|カビンダ州|2
LU|Lualaba|ルアラバ州|2
MA|Maniema|マニエマ州|2
MN|Mai-Ndombe|マイ＝ンドンベ州|2
MO|Mongala|モンガラ州|2
NK|North Kivu|北キヴ州|2
NU|Nord-Ubangi|北ウバンギ州|2
SA|Sankuru|サンクル州|2
SK|South Kivu|南キヴ州|2
SU|Sud-Ubangi|南ウバンギ州|2
TA|Tanganyika|タンガニーカ州|2
TO|Tshopo|ツォポ州|2
TU|Tshuapa|ツアパ州|2`,
};

export { CD };
