// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Congo - Brazzaville (CG): 12 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const CG: SubdivisionTable = {
  country: "CG",
  types: ["department","district"],
  typesJa: ["地方",null],
  rows: `11|Bouenza|ブエンザ地方|0
12|Pool|プール地方|0
13|Sangha|サンガ地方|0
14|Plateaux|プラトー地方|0
15|Cuvette-Ouest|西キュヴェト地方|0
16|Pointe-Noire||1
2|Lékoumou|レクム地方|0
5|Kouilou|クイル地方|0
7|Likouala|リクアラ地方|0
8|Cuvette|キュヴェト地方|0
9|Niari|ニアリ地方|0
BZV|Brazzaville|ブラザヴィル`,
};

export { CG };
