// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Switzerland (CH): 26 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place, Japanese names CLDR lacks

import type { SubdivisionTable } from "../../rows";

const CH: SubdivisionTable = {
  country: "CH",
  types: ["canton","city","state"],
  typesJa: ["州","準州","州"],
  rows: `AG|Aargau|アールガウ州|0
AI|Appenzell Innerrhoden|アッペンツェル・インナーローデン準州|2
AR|Appenzell Ausserrhoden|アッペンツェル・アウサーローデン準州|2
BE|Bern|ベルン州|0
BL|Basel-Landschaft|バーゼル＝ラント準州|2
BS|Basel-Stadt|バーゼル＝シュタット準州|1
FR|Fribourg|フリブール州|2
GE|Geneva|ジュネーヴ州|0
GL|Glarus|グラールス州|2
GR|Graubünden|グラウビュンデン州|0
JU|Jura|ジュラ州|2
LU|Lucerne|ルツェルン州|0
NE|Neuchâtel|ヌーシャテル州|0
NW|Nidwalden|ニトヴァルデン準州|0
OW|Obwalden|オプヴァルデン準州|0
SG|St. Gallen|ザンクト・ガレン州|0
SH|Schaffhausen|シャフハウゼン州|0
SO|Solothurn|ゾロトゥルン州|0
SZ|Schwyz|シュヴィーツ州|0
TG|Thurgau|トゥールガウ州|0
TI|Ticino|ティチーノ州|0
UR|Uri|ウーリ州|0
VD|Vaud|ヴォー州|0
VS|Valais|ヴァレー州|0
ZG|Zug|ツーク州|0
ZH|Zürich|チューリヒ州|0`,
};

export { CH };
