// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// China (CN): 34 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const CN: SubdivisionTable = {
  country: "CN",
  types: ["autonomous-region","city","province","special-administrative-region"],
  typesJa: ["自治区","市","省",null],
  rows: `AH|Anhui|安徽省|2
BJ|Beijing|北京市
CQ|Chongqing|重慶市|1
FJ|Fujian|福建省|2
GD|Guangdong|広東省|2
GS|Gansu|甘粛省|2
GX|Guangxi|広西チワン族自治区|0
GZ|Guizhou|貴州省|2
HA|Henan|河南省|2
HB|Hubei|湖北省|2
HE|Hebei|河北省|2
HI|Hainan|海南省|2
HK|Hong Kong|香港|3
HL|Heilongjiang|黒竜江省|2
HN|Hunan|湖南省|2
JL|Jilin|吉林省|2
JS|Jiangsu|江蘇省|2
JX|Jiangxi|江西省|2
LN|Liaoning|遼寧省|2
MO|Macau|マカオ|3
NM|Inner Mongolia|内モンゴル自治区|0
NX|Ningxia|寧夏回族自治区|0
QH|Qinghai|青海省|2
SC|Sichuan|四川省|2
SD|Shandong|山東省|2
SH|Shanghai|上海市|1
SN|Shaanxi|陝西省|2
SX|Shanxi|山西省|2
TJ|Tianjin|天津市|1
TW|Taiwan|台湾省|2
XJ|Xinjiang|新疆ウイグル自治区|0
XZ|Tibet|チベット自治区|0
YN|Yunnan|雲南省|2
ZJ|Zhejiang|浙江省|2`,
};

export { CN };
