// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Colombia (CO): 33 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const CO: SubdivisionTable = {
  country: "CO",
  types: ["capital-district","department","region"],
  typesJa: [null,"県","県"],
  rows: `AMA|Amazonas|アマソナス県|1
ANT|Antioquia|アンティオキア県|1
ARA|Arauca|アラウカ県|1
ATL|Atlántico|アトランティコ県|1
BOL|Bolívar|ボリーバル県|1
BOY|Boyacá|ボヤカ県|1
CAL|Caldas|カルダス県|1
CAQ|Caquetá|カケタ県|1
CAS|Casanare|カサナレ県|1
CAU|Cauca|カウカ県|1
CES|Cesar|セサール県|1
CHO|Chocó|チョコ県|1
COR|Córdoba|コルドバ県|1
CUN|Cundinamarca|クンディナマルカ県|1
DC|Bogotá|ボゴタ|0
GUA|Guainía|グアイニア県|1
GUV|Guaviare|グアビアーレ県|1
HUI|Huila|ウイラ県|1
LAG|La Guajira|ラ・グアヒーラ県|1
MAG|Magdalena|マグダレーナ県|1
MET|Meta|メタ県|1
NAR|Nariño|ナリーニョ県|1
NSA|Norte de Santander|ノルテ・デ・サンタンデール県|1
PUT|Putumayo|プトゥマヨ県|1
QUI|Quindío|キンディオ県|1
RIS|Risaralda|リサラルダ県|1
SAN|Santander|サンタンデール県|1
SAP|San Andrés & Providencia|サン・アンドレス・イ・プロビデンシア県|1
SUC|Sucre|スクレ県|1
TOL|Tolima|トリマ県|1
VAC|Valle del Cauca|バジェ・デル・カウカ県|1
VAU|Vaupés|バウペス県|1
VID|Vichada|ビチャーダ県|2`,
};

export { CO };
