// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Cuba (CU): 16 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const CU: SubdivisionTable = {
  country: "CU",
  types: ["municipality","province"],
  typesJa: [null,null],
  rows: `01|Pinar del Río|ピナール・デル・リオ州|1
03|Havana|ハバナ|1
04|Matanzas|マタンサス州|1
05|Villa Clara|ビジャ・クララ州|1
06|Cienfuegos|シエンフエーゴス州|1
07|Sancti Spíritus|サンクティ・スピリトゥス州|1
08|Ciego de Ávila|シエゴ・デ・アビラ州|1
09|Camagüey|カマグエイ州|1
10|Las Tunas|ラス・トゥーナス州|1
11|Holguín|オルギン州|1
12|Granma|グランマ州|1
13|Santiago de Cuba|サンティアーゴ・デ・クーバ州|1
14|Guantánamo|グァンタナモ州|1
15|Artemisa|アルテミサ州|1
16|Mayabeque|マヤベケ州|1
99|Isla de la Juventud|青年の島|0`,
};

export { CU };
