// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Cape Verde (CV): 24 subdivisions, at level 1 and 2.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const CV: SubdivisionTable = {
  country: "CV",
  types: ["island","municipality"],
  typesJa: [null,null],
  rows: `B|Barlavento Islands|バルラヴェント諸島|0
BR|Brava|ブラヴァ|1|S
BV|Boa Vista|ボア・ヴィスタ|1|B
CA|Santa Catarina|サンタ・カタリナ|1|S
CF|Santa Catarina do Fogo|サンタ・カタリナ・ド・フォゴ|1|S
CR|Santa Cruz|サンタ・クルス|1|S
MA|Maio|マイオ|1|S
MO|Mosteiros|モシュテイホシュ|1|S
PA|Paul|パウル|1|B
PN|Porto Novo|ポルト・ノボ|1|B
PR|Praia|プライア市|1|S
RB|Ribeira Brava|リベイラ・ブラヴァ|1|B
RG|Ribeira Grande|リベイラ・グランデ|1|B
RS|Ribeira Grande de Santiago|リベイラ・グランデ・デ・サンティアゴ|1|S
S|Sotavento Islands|ソタヴェント諸島|0
SD|São Domingos|サン・ドミンゴス|1|S
SF|São Filipe|サン・フィリペ|1|S
SL|Sal|サル|1|B
SM|São Miguel|サン・ミゲル|1|S
SO|São Lourenço dos Órgãos|サン・ローレンソ・ドス・オルガンス|1|S
SS|São Salvador do Mundo|サン・サルバドル・ド・ムンド|1|S
SV|São Vicente|サン・ビセンテ|1|B
TA|Tarrafal|タラファル|1|S
TS|Tarrafal de São Nicolau|タラファル・デ・サン・ニコラウ|1|B`,
};

export { CV };
