// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Cyprus (CY): 6 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const CY: SubdivisionTable = {
  country: "CY",
  types: ["district"],
  typesJa: ["地区"],
  rows: `01|Nicosia|ニコシア地区|0
02|Limassol|リマソール地区|0
03|Larnaca|ラルナカ地区|0
04|Famagusta|ファマグスタ地区|0
05|Paphos|パフォス地区|0
06|Kyrenia|キレニア地区|0`,
};

export { CY };
