// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Germany (DE): 16 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place, Japanese names CLDR lacks

import type { SubdivisionTable } from "../../rows";

const DE: SubdivisionTable = {
  country: "DE",
  types: ["city","state"],
  typesJa: [null,"州"],
  rows: `BB|Brandenburg|ブランデンブルク州|1
BE|Berlin|ベルリン|0
BW|Baden-Württemberg|バーデン＝ヴュルテンベルク州|1
BY|Bavaria|バイエルン自由州|1
HB|Bremen|ブレーメン州|0
HE|Hesse|ヘッセン州|1
HH|Hamburg|ハンブルク|0
MV|Mecklenburg-Vorpommern|メクレンブルク＝フォアポンメルン州|1
NI|Lower Saxony|ニーダーザクセン州|1
NW|North Rhine-Westphalia|ノルトライン＝ヴェストファーレン州|1
RP|Rhineland-Palatinate|ラインラント＝プファルツ州|1
SH|Schleswig-Holstein|シュレースヴィヒ＝ホルシュタイン州|1
SL|Saarland|ザールラント州|1
SN|Saxony|ザクセン州|1
ST|Saxony-Anhalt|ザクセン＝アンハルト州|1
TH|Thuringia|テューリンゲン州|1`,
};

export { DE };
