// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Denmark (DK): 5 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const DK: SubdivisionTable = {
  country: "DK",
  types: ["region"],
  typesJa: ["地域"],
  rows: `81|Northern Denmark|北ユラン地域|0
82|Central Denmark|中央ユラン地域|0
83|Southern Denmark|南デンマーク地域|0
84|Capital Region|デンマーク首都地域|0
85|Zealand|シェラン地域|0`,
};

export { DK };
