// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Dominica (DM): 10 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const DM: SubdivisionTable = {
  country: "DM",
  types: ["parish"],
  typesJa: [null],
  rows: `02|Saint Andrew|セント・アンドルー (ドミニカ国)|0
03|Saint David|セント・デイヴィッド郡 (ドミニカ国)|0
04|Saint George|セント・ジョージ (ドミニカ国)|0
05|Saint John|セント・ジョン郡 (ドミニカ国)|0
06|Saint Joseph|セント・ジョゼフ教区 (ドミニカ国)|0
07|Saint Luke|セント・ルーク (ドミニカ国)|0
08|Saint Mark|セント・マーク (ドミニカ国)|0
09|Saint Patrick|セント・パトリック (ドミニカ国)|0
10|Saint Paul|セント・ポール (ドミニカ国)|0
11|Saint Peter|セント・ピーター (ドミニカ国)|0`,
};

export { DM };
