// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Dominican Republic (DO): 42 subdivisions, at level 1 and 2.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const DO: SubdivisionTable = {
  country: "DO",
  types: ["province","region"],
  typesJa: [null,null],
  rows: `01|Distrito Nacional|ドミニカ共和国国家地区||40
02|Azua|アスア州|0|41
03|Baoruco|バオルコ州|0|38
04|Barahona|バラオナ|0|38
05|Dajabón|ダハボン|0|34
06|Duarte|ドゥアルテ州|0|33
07|Elías Piña|エリアス・ピーニャ州|0|37
08|El Seibo|エル・セイボ州|0|42
09|Espaillat|エスパイジャト州|0|35
10|Independencia|インデペンデンシア州|0|38
11|La Altagracia|ラ・アルタグラシア州|0|42
12|La Romana|ラ・ロマーナ州|0|42
13|La Vega|ラ・ベガ州|0|36
14|María Trinidad Sánchez|マリア・トリニダード・サンチェス州|0|33
15|Monte Cristi|モンテ・クリスティ州|0|34
16|Pedernales|ペデルナレス州|0|38
17|Peravia|ペラビア州|0|41
18|Puerto Plata|プエルト・プラタ州|0|35
19|Hermanas Mirabal|エルマーナス・ミラバル州|0|33
20|Samaná|サマナ州|0|33
21|San Cristóbal|サン・クリストバル州|0|41
22|San Juan|サン・フアン州 (ドミニカ共和国)|0|37
23|San Pedro de Macorís|サン・ペテロ・デ・マコリス州|0|39
24|Sánchez Ramírez|サンチェス・ラミレス州|0|36
25|Santiago|サンティアゴ県|0|35
26|Santiago Rodríguez|サンティアーゴ・ロドリゲス州|0|34
27|Valverde|バルベルデ州|0|34
28|Monseñor Nouel|モンセニョール・ノウエル州|0|36
29|Monte Plata|モンテ・プラタ州|0|39
30|Hato Mayor|アト・マジョール州|0|39
31|San José de Ocoa|サン・ホセ・デ・オコア州|0|41
32|Santo Domingo|サント・ドミンゴ州|0|40
33|Cibao Nordeste
34|Cibao Noroeste
35|Cibao Norte
36|Cibao Sur
37|El Valle
38|Enriquillo
39|Higüamo
40|Ozama||1
41|Valdesia||1
42|Yuma`,
};

export { DO };
