// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Algeria (DZ): 58 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const DZ: SubdivisionTable = {
  country: "DZ",
  types: ["province"],
  typesJa: ["県"],
  rows: `01|Adrar|アドラール県|0
02|Chlef|シュレフ県|0
03|Laghouat|ラグアット県|0
04|Oum El Bouaghi|ウメル・ブアーギ県|0
05|Batna|バトナ県|0
06|Béjaïa|ベジャイア県|0
07|Biskra|ビスクラ県|0
08|Béchar|ベシャール県|0
09|Blida|ブリダ県|0
10|Bouira|ブイラ県|0
11|Tamanghasset|タマンラセット県|0
12|Tébessa|テベッサ県|0
13|Tlemcen|トレムセン県|0
14|Tiaret|ティアレット県|0
15|Tizi Ouzou|ティジ・ウズー県|0
16|Algiers|アルジェ県|0
17|Djelfa|ジェルファ県|0
18|Jijel|ジジェル県|0
19|Sétif|セティフ県|0
20|Saïda|サイダ県|0
21|Skikda|スキクダ県|0
22|Sidi Bel Abbès|シディ・ベル・アッベス県|0
23|Annaba|アンナバ県|0
24|Guelma|ゲルマ県|0
25|Constantine|コンスタンティーヌ県|0
26|Médéa|メデア県|0
27|Mostaganem|モスタガネム県|0
28|M’Sila|ムシラ県|0
29|Mascara|マスカラ県|0
30|Ouargla|ワルグラ県|0
31|Oran|オラン県|0
32|El Bayadh|エル・バヤード県|0
33|Illizi|イリジ県|0
34|Bordj Bou Arréridj|ボルジ・ブ・アレリジ県|0
35|Boumerdès|ブメルデス県|0
36|El Tarf|エル・タルフ県|0
37|Tindouf|ティンドゥフ県|0
38|Tissemsilt|ティセムシルト県|0
39|El Oued|エル・ウェッド県|0
40|Khenchela|ヘンシュラ県|0
41|Souk Ahras|スーク・アフラース県|0
42|Tipasa|ティパザ県|0
43|Mila|ミラ県|0
44|Aïn Defla|アインデフラ県|0
45|Naama|ナーマ県|0
46|Aïn Témouchent|アイン・ティムシェント県|0
47|Ghardaïa|ガルダイア県|0
48|Relizane|ルリザンヌ県|0
49|Timimoun|ティミムン県|0
50|Bordj Badji Mokhtar|ボルジュ・バジ・モウタール県|0
51|Ouled Djellal|ウレド・ジェラル県|0
52|Béni Abbès|ベニ・アッベス県|0
53|In Salah|イン・サラー県|0
54|In Guezzam|イン・ゲザム県|0
55|Touggourt|トゥーグラ県|0
56|Djanet|ジャーネット県|0
57|El Meghaier|エル・ムエラ県|0
58|El Meniaa|エル・メニア県|0`,
};

export { DZ };
