// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Estonia (EE): 94 subdivisions, at level 1 and 2.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place, Japanese names CLDR lacks

import type { SubdivisionTable } from "../../rows";

const EE: SubdivisionTable = {
  country: "EE",
  types: ["city","county","municipality"],
  typesJa: [null,"県",null],
  rows: `130|Alutaguse||2|45
141|Anija||2|37
142|Antsla||2|87
171|Elva||2|79
184|Haapsalu|||56
191|Haljala|||60
198|Harku|||37
205|Hiiumaa||2|39
214|Häädemeeste||2|68
245|Jõelähtme||2|37
247|Jõgeva||2|50
251|Jõhvi|||45
255|Järva||2|52
272|Kadrina|||60
283|Kambja|||79
284|Kanepi|||64
291|Kastre|||79
293|Kehtna|||71
296|Keila|||37
303|Kihnu|||68
305|Kiili|||37
317|Kohila|||71
321|Kohtla-Järve|コフトラ＝ヤルヴェ|0|45
338|Kose|||37
353|Kuusalu|||37
37|Harju|ハリュ県|1
39|Hiiu|ヒーウ県|1
424|Loksa|||37
430|Lääneranna||2|68
431|Lääne-Harju||2|37
432|Luunja|||79
441|Lääne-Nigula||2|56
442|Lüganuse|ルガヌーセ教区|2|45
446|Maardu|||37
45|Ida-Virumaa|イダ＝ヴィル県|1
478|Muhu|||74
480|Mulgi|||84
486|Mustvee|||50
50|Jõgevamaa|ヨゲヴァ県|1
503|Märjamaa|||71
511|Narva|||45
514|Narva-Jõesuu||0|45
52|Järvamaa|イェルヴァ県|1
528|Nõo|||79
557|Otepää|オテパー|2|81
56|Läänemaa|レーネ県|1
567|Paide|||52
586|Peipsiääre||2|79
60|Lääne-Virumaa|レーネ＝ヴィル県|1
615|Põhja-Sakala||2|84
618|Põltsamaa||2|50
622|Põlva|||64
624|Pärnu|||68
638|Põhja-Pärnumaa||2|68
64|Põlvamaa|ポルヴァ県|1
651|Raasiku|||37
653|Rae|||37
661|Rakvere|||60
663|Rakvere|||60
668|Rapla|||71
68|Pärnumaa|ペルヌ県|1
689|Ruhnu|||74
698|Rõuge||2|87
708|Räpina|||64
71|Raplamaa|ラプラ県|1
712|Saarde|||68
714|Saaremaa|||74
719|Saku|||37
726|Saue|||37
732|Setomaa|||87
735|Sillamäe|シッラマエ|0|45
74|Saare|サーレ県|1
784|Tallinn|||37
79|Tartumaa|タルトゥ県|1
792|Tapa|||60
793|Tartu|||79
796|Tartu|||79
803|Toila|||45
809|Tori||2|68
81|Valgamaa|ヴァルガ県|1
824|Tõrva|||81
834|Türi|チュリ|2|52
84|Viljandi|ヴィリャンディ県|1
855|Valga|||81
87|Võrumaa|ヴォル県|1
890|Viimsi|||37
897|Viljandi|||84
899|Viljandi|||84
901|Vinni|||60
903|Viru-Nigula|||60
907|Vormsi|||56
917|Võru|||87
919|Võru|||87
928|Väike-Maarja||2|60`,
};

export { EE };
