// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Ethiopia (ET): 13 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const ET: SubdivisionTable = {
  country: "ET",
  types: ["capital-district","region"],
  typesJa: [null,null],
  rows: `AA|Addis Ababa|アディスアベバ|0
AF|Afar|アファール州|1
AM|Amhara|アムハラ州|1
BE|Benishangul-Gumuz|ベニシャングル・グムズ州|1
DD|Dire Dawa|ディレ・ダワ|1
GA|Gambela|ガンベラ州|1
HA|Harari|ハラリ州|1
OR|Oromia|オロミア州|1
SI|Sidama|シダマ県|1
SN|Southern Nations, Nationalities, and Peoples|南部諸民族州
SO|Somali|ソマリ州|1
SW|Southwest Ethiopia Peoples|南西エチオピア諸民族州|1
TI|Tigray|ティグレ州|1`,
};

export { ET };
