// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Gabon (GA): 9 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const GA: SubdivisionTable = {
  country: "GA",
  types: ["province"],
  typesJa: ["州"],
  rows: `1|Estuaire|エスチュエール州|0
2|Haut-Ogooué|オートオゴウェ州|0
3|Moyen-Ogooué|モワイエン・オゴウェ州|0
4|Ngounié|ングニエ州|0
5|Nyanga|ニャンガ州|0
6|Ogooué-Ivindo|オゴウェ・イヴィンド州|0
7|Ogooué-Lolo|オゴウェ・ロロ州|0
8|Ogooué-Maritime|オゴウェ・マリティム州|0
9|Woleu-Ntem|ウォレウ・ンテム州|0`,
};

export { GA };
