// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Ghana (GH): 16 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const GH: SubdivisionTable = {
  country: "GH",
  types: ["region"],
  typesJa: ["州"],
  rows: `AA|Greater Accra|グレーター・アクラ州|0
AF|Ahafo|アハフォ州|0
AH|Ashanti|アシャンティ州|0
BE|Bono East|ボノ・イースト州|0
BO|Bono|ボノ州|0
CP|Central|セントラル州|0
EP|Eastern|イースタン州|0
NE|North East|ノース・イースト州|0
NP|Northern|ノーザン州|0
OT|Oti|オティ州|0
SV|Savannah|サバンナ州|0
TV|Volta|ヴォルタ州|0
UE|Upper East|アッパー・イースト州|0
UW|Upper West|アッパー・ウエスト州|0
WN|Western North|ウェスタン・ノース州|0
WP|Western|ウェスタン州|0`,
};

export { GH };
