// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Equatorial Guinea (GQ): 10 subdivisions, at level 1 and 2.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const GQ: SubdivisionTable = {
  country: "GQ",
  types: ["province","region"],
  typesJa: [null,null],
  rows: `AN|Annobón|アンノボン県|0|I
BN|Bioko Norte|北ビオコ県|0|I
BS|Bioko Sur|南ビオコ県|0|I
C|Río Muni|リオ・ムニ|0
CS|Centro Sur|中南部県|0|C
DJ|Djibloho|ジブロホ県|0|C
I|Insular|島嶼地方 (赤道ギニア)|1
KN|Kié-Ntem|キエンテム県|0|C
LI|Litoral|リトラル県|0|C
WN|Wele-Nzas|ウェレンザス県|0|C`,
};

export { GQ };
