// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Greece (GR): 14 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const GR: SubdivisionTable = {
  country: "GR",
  types: ["autonomous-region","region"],
  typesJa: [null,null],
  rows: `69|Mount Athos|アトス山|0
A|East Macedonia and Thrace|東マケドニア・トラキア|1
B|Central Macedonia|中央マケドニア|1
C|West Macedonia|西マケドニア|1
D|Epirus|イピロス|1
E|Thessaly|テッサリア|1
F|Ionian Islands||1
G|West Greece|西ギリシャ|1
H|Central Greece|中央ギリシャ|1
I|Attica|アッティキ|1
J|Peloponnese|ペロポネソス|1
K|North Aegean|北エーゲ|1
L|South Aegean|南エーゲ|1
M|Crete||1`,
};

export { GR };
