// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Guinea-Bissau (GW): 12 subdivisions, at level 1 and 2.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const GW: SubdivisionTable = {
  country: "GW",
  types: ["city","province","region"],
  typesJa: [null,null,"州"],
  rows: `BA|Bafatá|バファタ州|2|L
BL|Bolama|ボラマ州|2|S
BM|Biombo|ビオンボ州|2|N
BS|Bissau|ビサウ|0
CA|Cacheu|カシェウ州|2|N
GA|Gabú|ガブ州|2|L
L|Leste||1
N|Norte||1
OI|Oio|オイオ州|2|N
QU|Quinara|キナラ州|2|S
S|Sul||1
TO|Tombali|トンバリ州|2|S`,
};

export { GW };
