// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Guyana (GY): 10 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place, Japanese names CLDR lacks

import type { SubdivisionTable } from "../../rows";

const GY: SubdivisionTable = {
  country: "GY",
  types: ["region"],
  typesJa: ["州"],
  rows: `BA|Barima-Waini|バリマ・ワイニ州|0
CU|Cuyuni-Mazaruni|クユニ＝マザルニ州|0
DE|Demerara-Mahaica|デメララ・マハイカ州|0
EB|East Berbice-Corentyne|東ベルビセ＝コレンティネ州|0
ES|Essequibo Islands-West Demerara|エセキボ諸島＝西デメララ州|0
MA|Mahaica-Berbice|マハイカ＝ベルビセ州|0
PM|Pomeroon-Supenaam|ポメローン＝スペナーム州|0
PT|Potaro-Siparuni|ポタ＝シパルニ州|0
UD|Upper Demerara-Berbice|アッパー・デメララ＝ベルビセ州|0
UT|Upper Takutu-Upper Essequibo|アッパー・タクトゥ＝アッパー・エセキボ州|0`,
};

export { GY };
