// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Croatia (HR): 21 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place, Japanese names CLDR lacks

import type { SubdivisionTable } from "../../rows";

const HR: SubdivisionTable = {
  country: "HR",
  types: ["city","county"],
  typesJa: [null,"郡"],
  rows: `01|Zagreb County|ザグレブ郡|1
02|Krapina-Zagorje|クラピナ＝ザゴリエ郡|1
03|Sisak-Moslavina|シサク＝モスラヴィナ郡|1
04|Karlovac|カルロヴァツ郡|1
05|Varaždin|ヴァラジュディン郡|1
06|Koprivnica-Križevci|コプリヴニツァ＝クリジェヴツィ郡|1
07|Bjelovar-Bilogora|ビェロヴァル＝ビロゴラ郡|1
08|Primorje-Gorski Kotar|プリモリェ＝ゴルスキ・コタル郡|1
09|Lika-Senj|リカ＝セニ郡|1
10|Virovitica-Podravina|ヴィロヴィティツァ＝ポドラヴィナ郡|1
11|Požega-Slavonia|ポジェガ＝スラヴォニア郡|1
12|Brod-Posavina|ブロド＝ポサヴィナ郡|1
13|Zadar|ザダル郡|1
14|Osijek-Baranja|オシエク＝バラニャ郡|1
15|Šibenik-Knin|シベニク＝クニン郡|1
16|Vukovar-Syrmia|ヴコヴァル＝スリイェム郡|1
17|Split-Dalmatia|スプリト＝ダルマチア郡|1
18|Istria|イストラ郡|1
19|Dubrovnik-Neretva|ドゥブロヴニク＝ネレトヴァ郡|1
20|Međimurje|メジムリェ郡|1
21|Zagreb|ザグレブ|0`,
};

export { HR };
