// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Haiti (HT): 10 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const HT: SubdivisionTable = {
  country: "HT",
  types: ["department"],
  typesJa: ["県"],
  rows: `AR|Artibonite|アルティボニット県|0
CE|Centre|中央県|0
GA|Grand’Anse|グランダンス県|0
ND|Nord|北県|0
NE|Nord-Est|北東県|0
NI|Nippes|ニップ県|0
NO|Nord-Ouest|北西県|0
OU|Ouest|西県|0
SD|Sud|南県|0
SE|Sud-Est|南東県|0`,
};

export { HT };
