// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Hungary (HU): 43 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const HU: SubdivisionTable = {
  country: "HU",
  types: ["capital-district","city","county"],
  typesJa: [null,null,"県"],
  rows: `BA|Baranya|バラニャ県|2
BC|Békéscsaba|ベーケーシュチャバ|1
BE|Békés|ベーケーシュ県|2
BK|Bács-Kiskun|バーチ・キシュクン県|2
BU|Budapest|ブダペスト|0
BZ|Borsod-Abaúj-Zemplén|ボルショド・アバウーイ・ゼンプレーン県|2
CS|Csongrád-Csanád|チョングラード・チャナード県|2
DE|Debrecen|デブレツェン|1
DU|Dunaújváros|ドゥナウーイヴァーロシュ|1
EG|Eger|エゲル|1
ER|Érd|エールド|1
FE|Fejér|フェイェール県|2
GS|Győr-Moson-Sopron|ジェール・モション・ショプロン県|2
GY|Győr|ジェール|1
HB|Hajdú-Bihar|ハイドゥー・ビハール県|2
HE|Heves|ヘヴェシュ県|2
HV|Hódmezővásárhely|ホードメゼーヴァーシャールヘイ|1
JN|Jász-Nagykun-Szolnok|ヤース・ナジクン・ソルノク県|2
KE|Komárom-Esztergom|コマーロム・エステルゴム県|2
KM|Kecskemét|ケチケメート|1
KV|Kaposvár|カポシュヴァール|1
MI|Miskolc|ミシュコルツ|1
NK|Nagykanizsa|ナジカニジャ|1
NO|Nógrád|ノーグラード県|2
NY|Nyíregyháza|ニーレジハーザ|1
PE|Pest|ペシュト県|2
PS|Pécs|ペーチ|1
SD|Szeged|セゲド|1
SF|Székesfehérvár|セーケシュフェヘールヴァール|1
SH|Szombathely|ソンバトヘイ|1
SK|Szolnok|ソルノク|1
SN|Sopron|ショプロン|1
SO|Somogy|ショモジ県|2
SS|Szekszárd|セクサールド|1
ST|Salgótarján|シャルゴータルヤーン|1
SZ|Szabolcs-Szatmár-Bereg|サボルチ・サトマール・ベレグ県|2
TB|Tatabánya|タタバーニャ|1
TO|Tolna|トルナ県|2
VA|Vas|ヴァシュ県|2
VE|Veszprém County|ヴェスプレーム県|2
VM|Veszprém|ヴェスプレーム|1
ZA|Zala|ザラ県|2
ZE|Zalaegerszeg|ザラエゲルセグ|1`,
};

export { HU };
