// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Indonesia (ID): 45 subdivisions, at level 1 and 2.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const ID: SubdivisionTable = {
  country: "ID",
  types: ["capital-district","province"],
  typesJa: [null,"州"],
  rows: `AC|Aceh|アチェ州|1|SM
BA|Bali|バリ州|1|NU
BB|Bangka–Belitung Islands|バンカ・ブリトゥン州|1|SM
BE|Bengkulu|ブンクル州|1|SM
BT|Banten|バンテン州|1|JW
GO|Gorontalo|ゴロンタロ州|1|SL
JA|Jambi|ジャンビ州|1|SM
JB|West Java|西ジャワ州|1|JW
JI|East Java|東ジャワ州|1|JW
JK|Jakarta|ジャカルタ|0|JW
JT|Central Java|中部ジャワ州|1|JW
JW|Java|ジャワ島
KA|Kalimantan|カリマンタン
KB|West Kalimantan|西カリマンタン州|1|KA
KI|East Kalimantan|東カリマンタン州|1|KA
KR|Riau Islands|リアウ諸島州|1|SM
KS|South Kalimantan|南カリマンタン州|1|KA
KT|Central Kalimantan|中部カリマンタン州|1|KA
KU|North Kalimantan|北カリマンタン州|1|KA
LA|Lampung|ランプン州|1|SM
MA|Maluku|マルク州|1|ML
ML|Maluku Islands|モルッカ諸島
MU|North Maluku|北マルク州|1|ML
NB|West Nusa Tenggara|西ヌサ・トゥンガラ州|1|NU
NT|East Nusa Tenggara|東ヌサ・トゥンガラ州|1|NU
NU|Lesser Sunda Islands|小スンダ列島
PA|Papua|パプア州|1|PP
PB|West Papua|西パプア州|1|PP
PD|Papua Barat Daya|南西パプア州|1|PP
PE|Papua Pengunungan|山岳パプア州|1|PP
PP|Papua Islands|イリアンジャヤ
PS|Papua Selatan|南パプア州|1|PP
PT|Papua Tengah|中部パプア州|1|PP
RI|Riau|リアウ州|1|SM
SA|North Sulawesi|北スラウェシ州|1|SL
SB|West Sumatra|西スマトラ州|1|SM
SG|Southeast Sulawesi|南東スラウェシ州|1|SL
SL|Sulawesi|スラウェシ島
SM|Sumatra|スマトラ島
SN|South Sulawesi|南スラウェシ州|1|SL
SR|West Sulawesi|西スラウェシ州|1|SL
SS|South Sumatra|南スマトラ州|1|SM
ST|Central Sulawesi|中部スラウェシ州|1|SL
SU|North Sumatra|北スマトラ州|1|SM
YO|Yogyakarta|ジョグジャカルタ特別州|1|JW`,
};

export { ID };
