// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Israel (IL): 6 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const IL: SubdivisionTable = {
  country: "IL",
  types: [],
  typesJa: [],
  rows: `D|Southern District|南部地区
HA|Haifa District|ハイファ地区
JM|Jerusalem|エルサレム地区
M|Central District|中央地区
TA|Tel Aviv District|テルアビブ地区
Z|Northern District|北部地区`,
};

export { IL };
