// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Every country's subdivision table (200 countries, 5046 subdivisions), for the /subdivisions entry.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json

import type { SubdivisionTable } from "../../rows";
import { AD } from "./ad.data";
import { AE } from "./ae.data";
import { AF } from "./af.data";
import { AG } from "./ag.data";
import { AL } from "./al.data";
import { AM } from "./am.data";
import { AO } from "./ao.data";
import { AR } from "./ar.data";
import { AT } from "./at.data";
import { AU } from "./au.data";
import { AZ } from "./az.data";
import { BA } from "./ba.data";
import { BB } from "./bb.data";
import { BD } from "./bd.data";
import { BE } from "./be.data";
import { BF } from "./bf.data";
import { BG } from "./bg.data";
import { BH } from "./bh.data";
import { BI } from "./bi.data";
import { BJ } from "./bj.data";
import { BN } from "./bn.data";
import { BO } from "./bo.data";
import { BQ } from "./bq.data";
import { BR } from "./br.data";
import { BS } from "./bs.data";
import { BT } from "./bt.data";
import { BW } from "./bw.data";
import { BY } from "./by.data";
import { BZ } from "./bz.data";
import { CA } from "./ca.data";
import { CD } from "./cd.data";
import { CF } from "./cf.data";
import { CG } from "./cg.data";
import { CH } from "./ch.data";
import { CI } from "./ci.data";
import { CL } from "./cl.data";
import { CM } from "./cm.data";
import { CN } from "./cn.data";
import { CO } from "./co.data";
import { CR } from "./cr.data";
import { CU } from "./cu.data";
import { CV } from "./cv.data";
import { CY } from "./cy.data";
import { CZ } from "./cz.data";
import { DE } from "./de.data";
import { DJ } from "./dj.data";
import { DK } from "./dk.data";
import { DM } from "./dm.data";
import { DO } from "./do.data";
import { DZ } from "./dz.data";
import { EC } from "./ec.data";
import { EE } from "./ee.data";
import { EG } from "./eg.data";
import { ER } from "./er.data";
import { ES } from "./es.data";
import { ET } from "./et.data";
import { FI } from "./fi.data";
import { FJ } from "./fj.data";
import { FM } from "./fm.data";
import { FR } from "./fr.data";
import { GA } from "./ga.data";
import { GB } from "./gb.data";
import { GD } from "./gd.data";
import { GE } from "./ge.data";
import { GH } from "./gh.data";
import { GL } from "./gl.data";
import { GM } from "./gm.data";
import { GN } from "./gn.data";
import { GQ } from "./gq.data";
import { GR } from "./gr.data";
import { GT } from "./gt.data";
import { GW } from "./gw.data";
import { GY } from "./gy.data";
import { HN } from "./hn.data";
import { HR } from "./hr.data";
import { HT } from "./ht.data";
import { HU } from "./hu.data";
import { ID } from "./id.data";
import { IE } from "./ie.data";
import { IL } from "./il.data";
import { IN } from "./in.data";
import { IQ } from "./iq.data";
import { IR } from "./ir.data";
import { IS } from "./is.data";
import { IT } from "./it.data";
import { JM } from "./jm.data";
import { JO } from "./jo.data";
import { JP } from "./jp.data";
import { KE } from "./ke.data";
import { KG } from "./kg.data";
import { KH } from "./kh.data";
import { KI } from "./ki.data";
import { KM } from "./km.data";
import { KN } from "./kn.data";
import { KP } from "./kp.data";
import { KR } from "./kr.data";
import { KW } from "./kw.data";
import { KZ } from "./kz.data";
import { LA } from "./la.data";
import { LB } from "./lb.data";
import { LC } from "./lc.data";
import { LI } from "./li.data";
import { LK } from "./lk.data";
import { LR } from "./lr.data";
import { LS } from "./ls.data";
import { LT } from "./lt.data";
import { LU } from "./lu.data";
import { LV } from "./lv.data";
import { LY } from "./ly.data";
import { MA } from "./ma.data";
import { MC } from "./mc.data";
import { MD } from "./md.data";
import { ME } from "./me.data";
import { MG } from "./mg.data";
import { MH } from "./mh.data";
import { MK } from "./mk.data";
import { ML } from "./ml.data";
import { MM } from "./mm.data";
import { MN } from "./mn.data";
import { MR } from "./mr.data";
import { MT } from "./mt.data";
import { MU } from "./mu.data";
import { MV } from "./mv.data";
import { MW } from "./mw.data";
import { MX } from "./mx.data";
import { MY } from "./my.data";
import { MZ } from "./mz.data";
import { NA } from "./na.data";
import { NE } from "./ne.data";
import { NG } from "./ng.data";
import { NI } from "./ni.data";
import { NL } from "./nl.data";
import { NO } from "./no.data";
import { NP } from "./np.data";
import { NR } from "./nr.data";
import { NZ } from "./nz.data";
import { OM } from "./om.data";
import { PA } from "./pa.data";
import { PE } from "./pe.data";
import { PG } from "./pg.data";
import { PH } from "./ph.data";
import { PK } from "./pk.data";
import { PL } from "./pl.data";
import { PS } from "./ps.data";
import { PT } from "./pt.data";
import { PW } from "./pw.data";
import { PY } from "./py.data";
import { QA } from "./qa.data";
import { RO } from "./ro.data";
import { RS } from "./rs.data";
import { RU } from "./ru.data";
import { RW } from "./rw.data";
import { SA } from "./sa.data";
import { SB } from "./sb.data";
import { SC } from "./sc.data";
import { SD } from "./sd.data";
import { SE } from "./se.data";
import { SG } from "./sg.data";
import { SH } from "./sh.data";
import { SI } from "./si.data";
import { SK } from "./sk.data";
import { SL } from "./sl.data";
import { SM } from "./sm.data";
import { SN } from "./sn.data";
import { SO } from "./so.data";
import { SR } from "./sr.data";
import { SS } from "./ss.data";
import { ST } from "./st.data";
import { SV } from "./sv.data";
import { SY } from "./sy.data";
import { SZ } from "./sz.data";
import { TD } from "./td.data";
import { TG } from "./tg.data";
import { TH } from "./th.data";
import { TJ } from "./tj.data";
import { TL } from "./tl.data";
import { TM } from "./tm.data";
import { TN } from "./tn.data";
import { TO } from "./to.data";
import { TR } from "./tr.data";
import { TT } from "./tt.data";
import { TV } from "./tv.data";
import { TW } from "./tw.data";
import { TZ } from "./tz.data";
import { UA } from "./ua.data";
import { UG } from "./ug.data";
import { UM } from "./um.data";
import { US } from "./us.data";
import { UY } from "./uy.data";
import { UZ } from "./uz.data";
import { VC } from "./vc.data";
import { VE } from "./ve.data";
import { VN } from "./vn.data";
import { VU } from "./vu.data";
import { WF } from "./wf.data";
import { WS } from "./ws.data";
import { YE } from "./ye.data";
import { ZA } from "./za.data";
import { ZM } from "./zm.data";
import { ZW } from "./zw.data";

const SUBDIVISION_TABLES: readonly SubdivisionTable[] = [
  AD,
  AE,
  AF,
  AG,
  AL,
  AM,
  AO,
  AR,
  AT,
  AU,
  AZ,
  BA,
  BB,
  BD,
  BE,
  BF,
  BG,
  BH,
  BI,
  BJ,
  BN,
  BO,
  BQ,
  BR,
  BS,
  BT,
  BW,
  BY,
  BZ,
  CA,
  CD,
  CF,
  CG,
  CH,
  CI,
  CL,
  CM,
  CN,
  CO,
  CR,
  CU,
  CV,
  CY,
  CZ,
  DE,
  DJ,
  DK,
  DM,
  DO,
  DZ,
  EC,
  EE,
  EG,
  ER,
  ES,
  ET,
  FI,
  FJ,
  FM,
  FR,
  GA,
  GB,
  GD,
  GE,
  GH,
  GL,
  GM,
  GN,
  GQ,
  GR,
  GT,
  GW,
  GY,
  HN,
  HR,
  HT,
  HU,
  ID,
  IE,
  IL,
  IN,
  IQ,
  IR,
  IS,
  IT,
  JM,
  JO,
  JP,
  KE,
  KG,
  KH,
  KI,
  KM,
  KN,
  KP,
  KR,
  KW,
  KZ,
  LA,
  LB,
  LC,
  LI,
  LK,
  LR,
  LS,
  LT,
  LU,
  LV,
  LY,
  MA,
  MC,
  MD,
  ME,
  MG,
  MH,
  MK,
  ML,
  MM,
  MN,
  MR,
  MT,
  MU,
  MV,
  MW,
  MX,
  MY,
  MZ,
  NA,
  NE,
  NG,
  NI,
  NL,
  NO,
  NP,
  NR,
  NZ,
  OM,
  PA,
  PE,
  PG,
  PH,
  PK,
  PL,
  PS,
  PT,
  PW,
  PY,
  QA,
  RO,
  RS,
  RU,
  RW,
  SA,
  SB,
  SC,
  SD,
  SE,
  SG,
  SH,
  SI,
  SK,
  SL,
  SM,
  SN,
  SO,
  SR,
  SS,
  ST,
  SV,
  SY,
  SZ,
  TD,
  TG,
  TH,
  TJ,
  TL,
  TM,
  TN,
  TO,
  TR,
  TT,
  TV,
  TW,
  TZ,
  UA,
  UG,
  UM,
  US,
  UY,
  UZ,
  VC,
  VE,
  VN,
  VU,
  WF,
  WS,
  YE,
  ZA,
  ZM,
  ZW,
];

export { SUBDIVISION_TABLES };
