// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Iraq (IQ): 19 subdivisions, at level 1 and 2.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const IQ: SubdivisionTable = {
  country: "IQ",
  types: ["governorate"],
  typesJa: ["県"],
  rows: `AN|Al Anbar|アンバール県|0
AR|Erbil|アルビール県|0|KR
BA|Basra|バスラ県|0
BB|Babylon|バービル県|0
BG|Baghdad|バグダード県|0
DA|Dohuk|ドホーク県|0|KR
DI|Diyala|ディヤーラー県|0
DQ|Dhi Qar|ジーカール県|0
KA|Karbala|カルバラー県|0
KI|Kirkuk|キルクーク県|0
KR|Kurdistan
MA|Maysan|マイサーン県|0
MU|Al Muthanna|ムサンナー県|0
NA|Najaf|ナジャフ県|0
NI|Nineveh|ニーナワー県|0
QA|Al-Qādisiyyah|カーディーシーヤ県|0
SD|Saladin|サラーフッディーン県|0
SU|Sulaymaniyah|スレイマニヤ県|0|KR
WA|Wasit|ワーシト県|0`,
};

export { IQ };
