// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Iceland (IS): 72 subdivisions, at level 1 and 2.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const IS: SubdivisionTable = {
  country: "IS",
  types: ["capital-district","city","municipality","region"],
  typesJa: [null,null,null,null],
  rows: `1|Capital|大レイキャヴィーク|3
2|Southern Peninsula|南西アイスランド|3
3|Western|西アイスランド|3
4|Westfjords|西部フィヨルド|3
5|Northwestern|北アイスランド西部|3
6|Northeastern|北アイスランド東部|3
7|Eastern|東アイスランド|3
8|Southern|南アイスランド|3
AKN|Akraneskaupstaður|アクラネース|2|3
AKU|Akureyrarbær|アークレイリ|1|6
ARN|Árneshreppur||2|4
ASA|Ásahreppur||2|8
BLA|Bláskógabyggð||2|8
BOG|Borgarbyggð|ボルガルビッグズ|2|3
BOL|Bolungarvíkurkaupstaður|ボルンガルヴィーク|2|4
DAB|Dalabyggð||2|3
DAV|Dalvíkurbyggð|ダールヴィークルビッグズ|2|6
EOM|Eyja- og Miklaholtshreppur||2|3
EYF|Eyjafjarðarsveit||2|6
FJD|Fjarðabyggð|フィヤルザビッグズ|2|7
FJL|Fjallabyggð||2|6
FLA|Flóahreppur||2|8
FLR|Fljótsdalshreppur||2|7
GAR|Garðabær|ガルザバイル||1
GOG|Grímsnes- og Grafningshreppur|||8
GRN|Grindavíkurbær||2|2
GRU|Grundarfjarðarbær|グルンダルフィヨルズル|2|3
GRY|Grýtubakkahreppur|||6
HAF|Hafnarfjarðarkaupstaður|ハフナルフィヨルズゥル|1|1
HRG|Hörgársveit|||6
HRU|Hrunamannahreppur|||8
HUG|Húnabyggð||2|5
HUV|Húnaþing vestra||2|5
HVA|Hvalfjarðarsveit|||3
HVE|Hveragerðisbær|クヴェラゲルジ|2|8
ISA|Ísafjarðarbær|||4
KAL|Kaldrananeshreppur|||4
KJO|Kjósarhreppur|||1
KOP|Kópavogsbær|コーパヴォグル|1|1
LAN|Langanesbyggð|||6
MOS|Mosfellsbær|||1
MUL|Múlaþing||2|7
MYR|Mýrdalshreppur|||8
NOR|Norðurþing|||6
RGE|Rangárþing eystra|ラゥングアゥルシンク・エイストラ|2|8
RGY|Rangárþing ytra||2|8
RHH|Reykhólahreppur|||4
RKN|Reykjanesbær|||2
RKV|Reykjavíkurborg|レイキャヴィーク|0|1
SBT|Svalbarðsstrandarhreppur|||6
SDN|Suðurnesjabær||2|2
SDV|Súðavíkurhreppur||2|4
SEL|Seltjarnarnesbær|セルチャルトナルネース|2|1
SFA|Sveitarfélagið Árborg|アゥルボルグ|2|8
SHF|Sveitarfélagið Hornafjörður|||7
SKF|Skaftárhreppur|||8
SKG|Skagabyggð|||5
SKO|Skorradalshreppur|||3
SKR|Skagafjörður|スカーガフィヨルズル|2|5
SNF|Snæfellsbær|||3
SOG|Skeiða- og Gnúpverjahreppur|||8
SOL|Sveitarfélagið Ölfus||2|8
SSS|Sveitarfélagið Skagaströnd||2|5
STR|Strandabyggð||2|4
STY|Stykkishólmsbær|||3
SVG|Sveitarfélagið Vogar||2|2
TAL|Tálknafjarðarhreppur|||4
THG|Þingeyjarsveit|||6
TJO|Tjörneshreppur||2|6
VEM|Vestmannaeyjabær|ヴェストマン諸島||8
VER|Vesturbyggð|||4
VOP|Vopnafjarðarhreppur|||7`,
};

export { IS };
