// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Italy (IT): 126 subdivisions, at level 1 and 2.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place, Japanese names CLDR lacks

import type { SubdivisionTable } from "../../rows";

const IT: SubdivisionTable = {
  country: "IT",
  types: ["autonomous-region","city","municipality","province","region"],
  typesJa: ["州",null,"県","県","州"],
  rows: `21|Piedmont|ピエモンテ州|4
23|Aosta Valley|ヴァッレ・ダオスタ州|0
25|Lombardy|ロンバルディア州|4
32|Trentino-South Tyrol|トレンティーノ＝アルト・アディジェ州|0
34|Veneto|ヴェネト州|4
36|Friuli–Venezia Giulia|フリウリ＝ヴェネツィア・ジュリア州|0
42|Liguria|リグーリア州|4
45|Emilia-Romagna|エミリア＝ロマーニャ州|4
52|Tuscany|トスカーナ州|4
55|Umbria|ウンブリア州|4
57|Marche|マルケ州|4
62|Lazio|ラツィオ州|4
65|Abruzzo|アブルッツォ州|4
67|Molise|モリーゼ州|4
72|Campania|カンパニア州|4
75|Apulia|プッリャ州|4
77|Basilicata|バジリカータ州|4
78|Calabria|カラブリア州|4
82|Sicily|シチリア州|0
88|Sardinia|サルデーニャ州|0
AG|Agrigento|アグリジェント県|2|82
AL|Alessandria|アレッサンドリア県|3|21
AN|Ancona|アンコーナ県|3|57
AP|Ascoli Piceno|アスコリ・ピチェーノ県|3|57
AQ|L’Aquila|ラクイラ県|3|65
AR|Arezzo|アレッツォ県|3|52
AT|Asti|アスティ県|3|21
AV|Avellino|アヴェッリーノ県|3|72
BA|Bari|バーリ県|1|75
BG|Bergamo|ベルガモ県|3|25
BI|Biella|ビエッラ県|3|21
BL|Belluno|ベッルーノ県|3|34
BN|Benevento|ベネヴェント県|3|72
BO|Bologna|ボローニャ県|1|45
BR|Brindisi|ブリンディジ県|3|75
BS|Brescia|ブレシア県|3|25
BT|Barletta-Andria-Trani|バルレッタ＝アンドリア＝トラーニ県|3|75
BZ|South Tyrol|ボルツァーノ自治県|3|32
CA|Cagliari|カリャリ県|1|88
CB|Campobasso|カンポバッソ県|3|67
CE|Caserta|カゼルタ県|3|72
CH|Chieti|キエーティ県|3|65
CL|Caltanissetta|カルタニッセッタ県|2|82
CN|Cuneo|クーネオ県|3|21
CO|Como|コモ県|3|25
CR|Cremona|クレモナ県|3|25
CS|Cosenza|コゼンツァ県|3|78
CT|Catania|カターニア県|1|82
CZ|Catanzaro|カタンザーロ県|3|78
EN|Enna|エンナ県|2|82
FC|Forlì-Cesena|フォルリ＝チェゼーナ県|3|45
FE|Ferrara|フェラーラ県|3|45
FG|Foggia|フォッジャ県|3|75
FI|Florence|フィレンツェ県|1|52
FM|Fermo|フェルモ県|3|57
FR|Frosinone|フロジノーネ県|3|62
GE|Genoa|ジェノヴァ|1|42
GO|Gorizia|ゴリツィア県||36
GR|Grosseto|グロッセート県|3|52
IM|Imperia|インペリア県|3|42
IS|Isernia|イゼルニア県|3|67
KR|Crotone|クロトーネ県|3|78
LC|Lecco|レッコ県|3|25
LE|Lecce|レッチェ県|3|75
LI|Livorno|リヴォルノ県|3|52
LO|Lodi|ローディ県|3|25
LT|Latina|ラティーナ県|3|62
LU|Lucca|ルッカ県|3|52
MB|Monza and Brianza|モンツァ・エ・ブリアンツァ県|3|25
MC|Macerata|マチェラータ県|3|57
ME|Messina|メッシーナ県|1|82
MI|Milan|ミラノ県|1|25
MN|Mantua|マントヴァ県|3|25
MO|Modena|モデナ県|3|45
MS|Massa and Carrara|マッサ＝カッラーラ県|3|52
MT|Matera|マテーラ県|3|77
NA|Naples|ナポリ県|1|72
NO|Novara|ノヴァーラ県|3|21
NU|Nuoro|ヌーオロ県|3|88
OR|Oristano|オリスターノ県|3|88
PA|Palermo|パレルモ県|1|82
PC|Piacenza|ピアチェンツァ県|3|45
PD|Padua|パドヴァ県|3|34
PE|Pescara|ペスカーラ県|3|65
PG|Perugia|ペルージャ県|3|55
PI|Pisa|ピサ県|3|52
PN|Pordenone|ポルデノーネ県||36
PO|Prato|プラート県|3|52
PR|Parma|パルマ県|3|45
PT|Pistoia|ピストイア県|3|52
PU|Pesaro and Urbino|ペーザロ・エ・ウルビーノ県|3|57
PV|Pavia|パヴィーア県|3|25
PZ|Potenza|ポテンツァ県|3|77
RA|Ravenna|ラヴェンナ県|3|45
RC|Reggio Calabria|レッジョ・カラブリア県|1|78
RE|Reggio Emilia|レッジョ・エミリア県|3|45
RG|Ragusa|ラグーザ県|2|82
RI|Rieti|リエーティ県|3|62
RM|Rome|ローマ県|1|62
RN|Rimini|リミニ県|3|45
RO|Rovigo|ロヴィーゴ県|3|34
SA|Salerno|サレルノ県|3|72
SI|Siena|シエーナ県|3|52
SO|Sondrio|ソンドリオ県|3|25
SP|La Spezia|ラ・スペツィア県|3|42
SR|Syracuse|シラクーザ県|2|82
SS|Sassari|サッサリ県||88
SU|Sud Sardegna|南サルデーニャ県||88
SV|Savona|サヴォーナ県|3|42
TA|Taranto|ターラント県|3|75
TE|Teramo|テーラモ県|3|65
TN|Trentino|トレント自治県|3|32
TO|Turin|トリノ県|1|21
TP|Trapani|トラーパニ県|2|82
TR|Terni|テルニ県|3|55
TS|Trieste|トリエステ県||36
TV|Treviso|トレヴィーゾ県|3|34
UD|Udine|ウーディネ県||36
VA|Varese|ヴァレーゼ県|3|25
VB|Verbano-Cusio-Ossola|ヴェルバーノ・クジオ・オッソラ県|3|21
VC|Vercelli|ヴェルチェッリ県|3|21
VE|Venice|ヴェネツィア県|1|34
VI|Vicenza|ヴィチェンツァ県|3|34
VR|Verona|ヴェローナ県|3|34
VT|Viterbo|ヴィテルボ県|3|62
VV|Vibo Valentia|ヴィボ・ヴァレンツィア県|3|78`,
};

export { IT };
