// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Jamaica (JM): 14 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const JM: SubdivisionTable = {
  country: "JM",
  types: ["parish"],
  typesJa: ["教区"],
  rows: `01|Kingston|キングストン教区|0
02|Saint Andrew|セント・アンドリュー教区|0
03|Saint Thomas|セント・トーマス教区|0
04|Portland|ポートランド教区|0
05|Saint Mary|セント・メアリー教区|0
06|Saint Ann|セント・アン教区|0
07|Trelawny|トレローニー教区|0
08|Saint James|セント・ジェームズ教区|0
09|Hanover|ハノーバー教区|0
10|Westmoreland|ウェストモアランド教区|0
11|Saint Elizabeth|セント・エリザベス教区|0
12|Manchester|マンチェスター教区|0
13|Clarendon|クラレンドン教区|0
14|Saint Catherine|セント・キャサリン教区|0`,
};

export { JM };
