// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Japan (JP): 47 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place, readings

import type { SubdivisionTable } from "../../rows";

const JP: SubdivisionTable = {
  country: "JP",
  types: ["circuit","metropolis","prefecture","urban-prefecture"],
  typesJa: ["道","都","県","府"],
  rows: `01|Hokkaidō|北海道|0||ほっかいどう
02|Aomori|青森県|2||あおもりけん
03|Iwate|岩手県|2||いわてけん
04|Miyagi|宮城県|2||みやぎけん
05|Akita|秋田県|2||あきたけん
06|Yamagata|山形県|2||やまがたけん
07|Fukushima|福島県|2||ふくしまけん
08|Ibaraki|茨城県|2||いばらきけん
09|Tochigi|栃木県|2||とちぎけん
10|Gunma|群馬県|2||ぐんまけん
11|Saitama|埼玉県|2||さいたまけん
12|Chiba|千葉県|2||ちばけん
13|Tokyo|東京都|1||とうきょうと
14|Kanagawa|神奈川県|2||かながわけん
15|Niigata|新潟県|2||にいがたけん
16|Toyama|富山県|2||とやまけん
17|Ishikawa|石川県|2||いしかわけん
18|Fukui|福井県|2||ふくいけん
19|Yamanashi|山梨県|2||やまなしけん
20|Nagano|長野県|2||ながのけん
21|Gifu|岐阜県|2||ぎふけん
22|Shizuoka|静岡県|2||しずおかけん
23|Aichi|愛知県|2||あいちけん
24|Mie|三重県|2||みえけん
25|Shiga|滋賀県|2||しがけん
26|Kyōto|京都府|3||きょうとふ
27|Ōsaka|大阪府|3||おおさかふ
28|Hyōgo|兵庫県|2||ひょうごけん
29|Nara|奈良県|2||ならけん
30|Wakayama|和歌山県|2||わかやまけん
31|Tottori|鳥取県|2||とっとりけん
32|Shimane|島根県|2||しまねけん
33|Okayama|岡山県|2||おかやまけん
34|Hiroshima|広島県|2||ひろしまけん
35|Yamaguchi|山口県|2||やまぐちけん
36|Tokushima|徳島県|2||とくしまけん
37|Kagawa|香川県|2||かがわけん
38|Ehime|愛媛県|2||えひめけん
39|Kōchi|高知県|2||こうちけん
40|Fukuoka|福岡県|2||ふくおかけん
41|Saga|佐賀県|2||さがけん
42|Nagasaki|長崎県|2||ながさきけん
43|Kumamoto|熊本県|2||くまもとけん
44|Ōita|大分県|2||おおいたけん
45|Miyazaki|宮崎県|2||みやざきけん
46|Kagoshima|鹿児島県|2||かごしまけん
47|Okinawa|沖縄県|2||おきなわけん`,
};

export { JP };
