// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Kenya (KE): 47 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const KE: SubdivisionTable = {
  country: "KE",
  types: ["county"],
  typesJa: [null],
  rows: `01|Baringo|バリンゴ|0
02|Bomet|ボメット|0
03|Bungoma|ブンゴマ|0
04|Busia|ブシア|0
05|Elgeyo-Marakwet||0
06|Embu|エンブ|0
07|Garissa|ガリッサ|0
08|Homa Bay|ホマ・ベイ|0
09|Isiolo|イシオロ|0
10|Kajiado|カジアド|0
11|Kakamega|カカメガ|0
12|Kericho|ケリチョ|0
13|Kiambu|キアンブ|0
14|Kilifi|キリフィ|0
15|Kirinyaga|キリーニャガ|0
16|Kisii|キシイ県|0
17|Kisumu|キスム|0
18|Kitui|キツイ|0
19|Kwale|クワレ|0
20|Laikipia|ライキピア|0
21|Lamu|ラム|0
22|Machakos|マチャコス|0
23|Makueni|マクエニ|0
24|Mandera|マンデラ|0
25|Marsabit|マルサビット|0
26|Meru|メルー|0
27|Migori|ミゴリ|0
28|Mombasa|モンバサ|0
29|Murang’a|ムランガ|0
30|Nairobi County|ナイロビ|0
31|Nakuru|ナクル|0
32|Nandi|ナンディ|0
33|Narok|ナロク|0
34|Nyamira|ニャミラ県|0
35|Nyandarua|ニャンダルア|0
36|Nyeri|ニエリ|0
37|Samburu|サンブル|0
38|Siaya|シアヤ|0
39|Taita-Taveta||0
40|Tana River|タナ・リバー|0
41|Tharaka-Nithi||0
42|Trans Nzoia|トランス・ンゾイア|0
43|Turkana|トゥルカナ|0
44|Uasin Gishu|ウアシン・ギシュ|0
45|Vihiga|ヴィヒガ|0
46|Wajir|ワジール|0
47|West Pokot|ウェスト・ポコット|0`,
};

export { KE };
