// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Kiribati (KI): 3 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const KI: SubdivisionTable = {
  country: "KI",
  types: ["island"],
  typesJa: [null],
  rows: `G|Gilbert Islands|ギルバート諸島|0
L|Line Islands|ライン諸島|0
P|Phoenix Islands|フェニックス諸島|0`,
};

export { KI };
