// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// North Korea (KP): 13 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const KP: SubdivisionTable = {
  country: "KP",
  types: ["city","municipality","province"],
  typesJa: ["特別市",null,"道"],
  rows: `01|Pyongyang|平壌|1
02|South Pyongan|平安南道|2
03|North Pyongan|平安北道|2
04|Chagang|慈江道|2
05|South Hwanghae|黄海南道|2
06|North Hwanghae|黄海北道|2
07|Kangwon|江原道|2
08|South Hamgyong|咸鏡南道|2
09|North Hamgyong|咸鏡北道|2
10|Ryanggang|両江道|2
13|Rason|羅先特別市|0
14|Nampho|南浦特別市|0
15|Kaeseong|開城特別市|0`,
};

export { KP };
