// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Lebanon (LB): 8 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place, Japanese names CLDR lacks

import type { SubdivisionTable } from "../../rows";

const LB: SubdivisionTable = {
  country: "LB",
  types: ["governorate"],
  typesJa: ["県"],
  rows: `AK|Akkar|アッカール県|0
AS|North|北レバノン県|0
BA|Beirut|ベイルート県|0
BH|Baalbek-Hermel|バールベック＝ヘルメル県|0
BI|Beqaa|ベッカー県|0
JA|South|南レバノン県|0
JL|Mount Lebanon|山岳レバノン県|0
NA|Nabatieh|ナバティーエ県|0`,
};

export { LB };
