// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// St. Lucia (LC): 10 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const LC: SubdivisionTable = {
  country: "LC",
  types: ["city","district","quarter"],
  typesJa: [null,null,"地区"],
  rows: `01|Anse la Raye|アンス・ラ・レイ地区|2
02|Castries|カストリーズ地区|2
03|Choiseul|ショゼール地区|2
05|Dennery|デナリー地区|2
06|Gros Islet|グロス・イスレット地区|2
07|Laborie|ラボリー地区|2
08|Micoud|ミクッド地区|2
10|Soufrière|スフレ|1
11|Vieux Fort|ビュー・フォート|1
12|Canaries|カナリアス|0`,
};

export { LC };
