// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Sri Lanka (LK): 34 subdivisions, at level 1 and 2.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const LK: SubdivisionTable = {
  country: "LK",
  types: ["district","province"],
  typesJa: ["県","州"],
  rows: `1|Western|西部州|1
11|Colombo|コロンボ県|0|1
12|Gampaha|ガンパハ県|0|1
13|Kalutara|カルタラ県|0|1
2|Central|中部州|1
21|Kandy|キャンディ県|0|2
22|Matale|マータレー県|0|2
23|Nuwara Eliya|ヌワラ・エリヤ県|0|2
3|Southern|南部州|1
31|Galle|ゴール県|0|3
32|Matara|マータラ県|0|3
33|Hambantota|ハンバントタ県|0|3
4|Northern|北部州|1
41|Jaffna|ジャフナ県|0|4
42|Kilinochchi|キリノッチ県|0|4
43|Mannar|マンナール県|0|4
44|Vavuniya|バブニヤ県|0|4
45|Mullaitivu|ムッライッティーヴー県|0|4
5|Eastern|東部州|1
51|Batticaloa|バッティカロア県|0|5
52|Ampara|アンパーラ県|0|5
53|Trincomalee|トリンコマリー県|0|5
6|North Western|北西部州|1
61|Kurunegala|クルネーガラ県|0|6
62|Puttalam|プッタラム県|0|6
7|North Central|北中部州|1
71|Anuradhapura|アヌラーダプラ県|0|7
72|Polonnaruwa|ポロンナルワ県|0|7
8|Uva|ウバ州|1
81|Badulla|バドゥッラ県|0|8
82|Moneragala|モナラーガラ県|0|8
9|Sabaragamuwa|サバラガムワ州|1
91|Ratnapura|ラトゥナプラ県|0|9
92|Kegalle|ケーガッラ県|0|9`,
};

export { LK };
