// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Liberia (LR): 15 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const LR: SubdivisionTable = {
  country: "LR",
  types: ["county"],
  typesJa: ["郡"],
  rows: `BG|Bong|ボン郡|0
BM|Bomi|ボミ郡|0
CM|Grand Cape Mount|グランドケープマウント郡|0
GB|Grand Bassa|グランドバッサ郡|0
GG|Grand Gedeh|グランドゲデ郡|0
GK|Grand Kru|グランドクル郡|0
GP|Gbarpolu|バルポル郡|0
LO|Lofa|ロファ郡|0
MG|Margibi|マージビ郡|0
MO|Montserrado|モンセラード郡|0
MY|Maryland|メリーランド郡|0
NI|Nimba|ニンバ郡|0
RG|River Gee|リバージー郡|0
RI|Rivercess|リバーセス郡|0
SI|Sinoe|シノエ郡|0`,
};

export { LR };
