// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Lesotho (LS): 10 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const LS: SubdivisionTable = {
  country: "LS",
  types: ["district"],
  typesJa: ["県"],
  rows: `A|Maseru|マセル県|0
B|Butha-Buthe|ブータ・ブーテ県|0
C|Leribe|レリベ県|0
D|Berea|ベレア県|0
E|Mafeteng|マフェテング県|0
F|Mohale’s Hoek|モハレス・フーク県|0
G|Quthing|クティング県|0
H|Qacha’s Nek|クァクハスネック県|0
J|Mokhotlong|モコトロング県|0
K|Thaba-Tseka|ターバ・ツェーカ県|0`,
};

export { LS };
