// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Luxembourg (LU): 12 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place, Japanese names CLDR lacks

import type { SubdivisionTable } from "../../rows";

const LU: SubdivisionTable = {
  country: "LU",
  types: ["canton"],
  typesJa: ["郡"],
  rows: `CA|Capellen|カペレン郡|0
CL|Clervaux|クレルヴォー郡|0
DI|Diekirch|ディーキルヒ郡|0
EC|Echternach|エヒタナハ郡|0
ES|Esch-sur-Alzette|エシュ＝シュル＝アルゼット郡|0
GR|Grevenmacher|グレーヴェンマハ郡|0
LU|Luxembourg|ルクセンブルク郡|0
ME|Mersch|メルシュ郡|0
RD|Redange|ルダンジュ郡|0
RM|Remich|レーミッヒ郡|0
VD|Vianden|ヴィアンデン郡|0
WI|Wiltz|ヴィルツ郡|0`,
};

export { LU };
