// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Latvia (LV): 43 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const LV: SubdivisionTable = {
  country: "LV",
  types: ["city","municipality"],
  typesJa: [null,null],
  rows: `002|Aizkraukle|アイズクラウクレ|1
007|Alūksne|アルークスネ|1
011|Ādaži|アーダジ|1
015|Balvi|バルヴィ|1
016|Bauska|バウスカ|1
022|Cēsis|ツェースィス|1
026|Dobele|ドベレ|1
033|Gulbene|グルベネ|1
041|Jelgava Municipality|イェルガヴァ|1
042|Jēkabpils Municipality|イェーカブピルス|1
047|Krāslava|クラスラヴァ|1
050|Kuldīga|クルディーガ|1
052|Ķekava|キェカワ|1
054|Limbaži|リンバジ|1
056|Līvāni|リーヴァーニ|1
058|Ludza|ルザ|1
059|Madona|マドナ|1
062|Mārupe|マールペ|1
067|Ogre|オグレ|1
068|Olaine|ウアライネ|1
073|Preiļi|プレイリ|1
077|Rēzekne Municipality|レーゼクネ|1
080|Ropaži|ルアパジ|1
087|Salaspils|サラスピルス|1
088|Saldus|サルドゥス|1
089|Saulkrasti|サウルクラスチ|1
091|Sigulda|スィグルダ|1
094|Smiltene|スミルテネ|1
097|Talsi|タルスィ|1
099|Tukums|トゥクムス|1
101|Valka|ヴァルカ|1
102|Varakļāni|ヴァラクリャーニ
106|Ventspils Municipality|ヴェンツピルス|1
111|Augšdaugavas novads|アウゲシュダウガヴァ市|1
112|Dienvidkurzemes Novads|南クルゼメ市|1
113|Valmieras Novads|ヴァルミエラ市|1
DGV|Daugavpils|ダウガフピルス|0
JEL|Jelgava|イェルガヴァ|0
JUR|Jūrmala|ユールマラ|0
LPX|Liepāja|リエパーヤ|0
REZ|Rēzekne|レーゼクネ|0
RIX|Riga|リガ|0
VEN|Ventspils|ヴェンツピルス|0`,
};

export { LV };
