// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Libya (LY): 22 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const LY: SubdivisionTable = {
  country: "LY",
  types: ["district","municipality"],
  typesJa: ["県",null],
  rows: `BA|Benghazi|ベンガジ|1
BU|Butnan|ブトナーン県|0
DR|Derna|デルナ県|0
GT|Ghat|ガート県|0
JA|Jabal al Akhdar|ジャバル・アル・アフダル県|0
JG|Jabal al Gharbi|ジャバル・アル・ガルビ県|0
JI|Jafara|ジファーラ県|0
JU|Jufra|ジュフラ県|0
KF|Kufra|クフラ県|0
MB|Murqub|ムルクブ県|0
MI|Misrata|ミスラタ県|0
MJ|Marj|マルジュ県|0
MQ|Murzuq|ムルズク県|0
NL|Nalut|ナールート県|0
NQ|Nuqat al Khams|ヌカート・アル・ハムス県|0
SB|Sabha|サブハー県|0
SR|Sirte|スルト県|0
TB|Tripoli|トリポリ県|0
WA|Al Wahat|アル・ワーハート県|0
WD|Wadi al Hayaa|ワジ・アル・ハヤー県|0
WS|Wadi al Shatii|ワジ・アル・シャーティー県|0
ZA|Zawiya|ザーウィヤ県|0`,
};

export { LY };
