// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Morocco (MA): 87 subdivisions, at level 1 and 2.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place, Japanese names CLDR lacks

import type { SubdivisionTable } from "../../rows";

const MA: SubdivisionTable = {
  country: "MA",
  types: ["prefecture","province","region"],
  typesJa: [null,null,"地方"],
  rows: `01|Tangier-Tetouan-Al Hoceima|タンジェ＝テトゥアン＝アル・ホセイマ地方|2
02|Oriental|オリアンタル地方|2
03|Fès-Meknès|フェズ＝メクネス地方|2
04|Rabat-Salé-Kénitra|ラバト＝サレ＝ケニトラ地方|2
05|Béni Mellal-Khénifra|ベニ・メラル＝ヘニフラ地方|2
06|Casablanca-Settat|カサブランカ＝セタット地方|2
07|Marrakesh-Safi|マラケシュ＝サフィ地方|2
08|Drâa-Tafilalet|ドラア＝タフィラルト地方|2
09|Souss-Massa|スース＝マサ地方|2
10|Guelmim-Oued Noun|ゲルミン＝オウィド・ノウン地方|2
11|Laâyoune-Sakia El Hamra|ラアユーン＝サギア・エル・ハムラ地方|2
12|Dakhla-Oued Ed-Dahab|ダフラ＝オウィド・エッ＝ダハブ地方|2
AGD|Agadir-Ida Ou Tanane|アガディール|0|09
AOU|Aousserd|アウサード州|1|12
ASZ|Assa-Zag|アサ・ザグ州|1|10
AZI|Azilal|アジラル州|1|05
BEM|Béni-Mellal|ベニ・メラル州|1|05
BER|Berkane|ベルカンヌ州|1|02
BES|Ben Slimane|ベン・スリマン州|1|06
BOD|Boujdour|ブジュール州|1|11
BOM|Boulemane|ブルマーヌ州|1|03
BRR|Berrechid|ベレチド州|1|06
CAS|Casablanca|カサブランカ|0|06
CHE|Chefchaouen|シャウエン州|1|01
CHI|Chichaoua|シカウア州|1|07
CHT|Chtouka Aït Baha|チュトウカ・アイト・バハ州|1|06
DRI|Driouch|ドリオウチュ州|1|02
ERR|Errachidia|エルラシディア州|1|08
ESI|Essaouira|エッサウィラ州|1|07
ESM|Es Semara|スマラ州|1|11
FAH|Fahs-Beni Makada|ファフス・アンジュラ州|1|01
FES|Fès-Dar-Dbibegh|フェズ|0|03
FIG|Figuig|フィギグ州|1|02
FQH|Fquih Ben Salah|フキレ・ベンヌ・サラ州|1|05
GUE|Guelmim|ゲルミン州|1|10
GUF|Guercif|ゲルシフ州|1|02
HAJ|El Hajeb|ハジェブ州|1|03
HAO|Al Haouz|ハオウズ|1|07
HOC|Al Hoceïma|アル・ホセイマ州|1|01
IFR|Ifrane|イフレン州|1|03
INE|Inezgane-Aït Melloul|イネガーヌ・アイト・メロウル県|0|09
JDI|El Jadida|アル・ジャディーダ州|1|06
JRA|Jerada|ジェラダ州|1|02
KEN|Kénitra|ケニトラ州|1|04
KES|Kelaat Sraghna|エル・ケッラ・デ・スラーナ州|1|07
KHE|Khemisset|ケミセット州|1|04
KHN|Khénifra|ヘニフラ州|1|05
KHO|Khouribga|クーリブカ州|1|05
LAA|Laâyoune|アイウン州|1|11
LAR|Larache|アライシュ州|1|01
MAR|Marrakech|マラケシュ県|0|07
MDF|M’diq-Fnideq|メディック・フニデク県|0|01
MED|Médiouna|メディウナ州|1|06
MEK|Meknès|メクネス|0|03
MID|Midelt|ミデルト州|1|08
MOH|Mohammedia|モハメディア|0|06
MOU|Moulay Yacoub|ムーレイ・ヤコブ州|1|03
NAD|Nador|ナドール州|1|02
NOU|Nouaceur|ノウアセウル州|1|04
OUA|Ouarzazate|ワルザザート州|1|08
OUD|Oued Ed-Dahab|オウィド・エッ＝ダハブ州|1|12
OUJ|Oujda-Angad|ウジダ|0|02
OUZ|Ouezzane|ウェザーン州|1|01
RAB|Rabat|ラバト|0|04
REH|Rehamna|レハムナ州|1|07
SAF|Safi|サフィ州|1|07
SAL|Salé|サレ|0|04
SEF|Sefrou|セフル州|1|03
SET|Settat|セタト州|1|06
SIB|Sidi Bennour|シディベヌール州|1|06
SIF|Sidi Ifni|シディ・イフニー州|1|10
SIK|Sidi Kacem|シディ・カセム州|1|04
SIL|Sidi Slimane|シーディ スリマネ州|1|04
SKH|Skhirat-Témara|テマラ|0|04
TAF|Tarfaya (EH-partial)|タルファヤ州|1|11
TAI|Taourirt|タウリル州|1|02
TAO|Taounate|タウナト州|1|03
TAR|Taroudant|タルーダント州|1|09
TAT|Tata|タタ州|1|09
TAZ|Taza|ターザ州|1|03
TET|Tétouan|テトゥアン州|1|01
TIN|Tinghir|ティンジル州|1|08
TIZ|Tiznit|ティーズニート州|1|09
TNG|Tangier-Assilah|タンジェ|0|01
TNT|Tan-Tan|タンタン州|1|10
YUS|Youssoufia|ユスーフィーア州|1|07
ZAG|Zagora|ザゴラ州|1|08`,
};

export { MA };
