// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Monaco (MC): 17 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const MC: SubdivisionTable = {
  country: "MC",
  types: ["city","district","quarter"],
  typesJa: [null,null,null],
  rows: `CL|La Colle|ラ・コル|2
CO|La Condamine|ラ・コンダミーヌ地区|1
FO|Fontvieille|フォンヴィエイユ|1
GA|La Gare||2
JE|Jardin Exotique de Monaco|熱帯公園|1
LA|Larvotto|ラルヴォット|1
MA|Malbousquet||2
MC|Monte Carlo|モンテカルロ|0
MG|Moneghetti||1
MO|Monaco-Ville|モナコ・ヴィル|2
MU|Moulins||2
PH|Port Hercules|ポートエルキュール
SD|Sainte-Dévote Chapel||1
SO|La Source||2
SP|Spélugues||2
SR|Saint Roman||2
VR|Vallon de la Rousse||2`,
};

export { MC };
