// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Moldova (MD): 37 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const MD: SubdivisionTable = {
  country: "MD",
  types: ["district","municipality"],
  typesJa: [null,null],
  rows: `AN|Anenii Noi|アネニイ・ノイ県|0
BA|Bălţi|バルツィ|1
BD|Bender|ベンデル|1
BR|Briceni|ブリチェニー県|0
BS|Basarabeasca|バサラベアスカ県|0
CA|Cahul|カフル県|0
CL|Călărași|カララシ県 (モルドヴァ)|0
CM|Cimișlia|チミシリア県|0
CR|Criuleni|クリウレニ県|0
CS|Căușeni|カウシェニ県|0
CT|Cantemir|カンテミール県|0
CU|Chișinău|キシナウ|1
DO|Dondușeni|ドンドゥセニ県|0
DR|Drochia|ドロキア県|0
DU|Dubăsari|ドゥベサリ県|0
ED|Edineț|エディネツ県|0
FA|Fălești|ファレシュティ県|0
FL|Florești|フロレシュティ県|0
GA|Gagauzia|ガガウズ自治区
GL|Glodeni|グロデニ県|0
HI|Hîncești|ヒンチェシュティ県|0
IA|Ialoveni|ヤロベニ県|0
LE|Leova|レオバ県|0
NI|Nisporeni|ニスポレニ県|0
OC|Ocniţa|オクニタ県|0
OR|Orhei|オルゲイ県|0
RE|Rezina|レジナ県|0
RI|Rîșcani|リスカニ県|0
SD|Șoldănești|ソルダネシュティ県|0
SI|Sîngerei|シンジェレイ県|0
SN|Transnistria|沿ドニエストル地域
SO|Soroca|ソロカ県|0
ST|Strășeni|ストラセニ県|0
SV|Ştefan Vodă|シュテファン・ボーダ県|0
TA|Taraclia|タラクリア県|0
TE|Telenești|テレネシュティ県|0
UN|Ungheni|ウンゲニ県|0`,
};

export { MD };
