// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Montenegro (ME): 25 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const ME: SubdivisionTable = {
  country: "ME",
  types: ["municipality"],
  typesJa: [null],
  rows: `01|Andrijevica|アンドリイェヴィツァ|0
02|Bar|バール|0
03|Berane|ベラネ|0
04|Bijelo Polje|ビイェロ・ポリェ|0
05|Budva|ブドヴァ|0
06|Cetinje|ツェティニェ|0
07|Danilovgrad|ダニロヴグラード|0
08|Herceg Novi|ヘルツェグ・ノヴィ|0
09|Kolašin|コラシン|0
10|Kotor||0
11|Mojkovac|モイコヴァツ|0
12|Nikšić|ニクシチ|0
13|Plav|プラヴ|0
14|Pljevlja|プリェヴリャ|0
15|Plužine|プルジネ|0
16|Podgorica||0
17|Rožaje||0
18|Šavnik|シャヴニク|0
19|Tivat||0
20|Ulcinj|ウルツィニ|0
21|Žabljak|ジャブリャク|0
22|Gusinje||0
23|Petnjica||0
24|Tuzi||0
25|Zeta||0`,
};

export { ME };
