// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Marshall Islands (MH): 26 subdivisions, at level 1 and 2.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const MH: SubdivisionTable = {
  country: "MH",
  types: ["city","island"],
  typesJa: [null,null],
  rows: `ALK|Ailuk Atoll|アイルック環礁||T
ALL|Ailinglaplap Atoll|アイリングラップ環礁||L
ARN|Arno|アルノ環礁||T
AUR|Aur Atoll|オール環礁||T
EBO|Ebon Atoll|エボン環礁||L
ENI|Enewetak Atoll|エニウェトク環礁||L
JAB|Jabat Island|ジャボット島||L
JAL|Jaluit Atoll|ジャルート環礁||L
KIL|Kili Island|キリ島|1|L
KWA|Kwajalein|クェゼリン環礁||L
L|Ralik Chain|ラリック列島
LAE|Lae Atoll|ラエー環礁||L
LIB|Lib Island|リブ島||L
LIK|Likiep Atoll|リキエップ環礁||T
MAJ|Majuro|マジュロ|0|T
MAL|Maloelap Atoll|マロエラップ環礁||T
MEJ|Mejit Island|メジット島|1|T
MIL|Mili Atoll|ミリ環礁||T
NMK|Namdrik Atoll|ナモリック環礁||L
NMU|Namu Atoll|ナムー環礁||L
RON|Rongelap Atoll|ロンゲラップ環礁||L
T|Ratak Chain|ラタック列島
UJA|Ujae Atoll|ウジャエ環礁||L
UTI|Utirik Atoll|ウチリック環礁||T
WTH|Wotho Atoll|オトー環礁||L
WTJ|Wotje Atoll|ウォッジェ環礁||T`,
};

export { MH };
