// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// North Macedonia (MK): 80 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place, Japanese names CLDR lacks

import type { SubdivisionTable } from "../../rows";

const MK: SubdivisionTable = {
  country: "MK",
  types: ["municipality"],
  typesJa: [null],
  rows: `101|Veles||0
102|Gradsko|グラドスコ|0
103|Demir Kapija|デミル・カピヤ|0
104|Kavadarci|カヴァダルツィ|0
105|Lozovo|ロゾヴォ|0
106|Negotino|ネゴティノ|0
107|Rosoman|ロソマン|0
108|Sveti Nikole|スヴェティ・ニコレ|0
109|Čaška|チャシュカ|0
201|Berovo|ベロヴォ (マケドニア)|0
202|Vinica|ヴィニツァ|0
203|Delčevo|デルチェヴォ|0
204|Zrnovci|ズルノヴツィ|0
205|Karbinci|カルビンツィ|0
206|Kočani|クアツェーニ|0
207|Makedonska Kamenica|マケドンスカ・カメニツァ|0
208|Pehčevo|ペフチェヴォ|0
209|Probištip|プロビシュティプ|0
210|Češinovo-Obleševo|チェシノヴォ＝オブレシェヴォ|0
211|Štip|シュティプ|0
301|Vevčani|ヴェヴチャニ|0
303|Debar|デバル|0
304|Debrca|デバルツァ|0
307|Kičevo|キチェボ|0
308|Makedonski Brod|マケドンスキ・ブロド|0
310|Ohrid|オフリド|0
311|Plasnica|プラスニツァ|0
312|Struga|ストルガ基礎自治体|0
313|Centar Župa|ツェンタル・ジュパ|0
401|Bogdanci|ボグダンツィ|0
402|Bosilovo|ボシロヴォ|0
403|Valandovo|ヴァランドヴォ|0
404|Vasilevo|ヴァシレヴォ|0
405|Gevgelija|ゲヴゲリヤ|0
406|Dojran|ドイラン|0
407|Konče|コンチェ|0
408|Novo Selo|ノヴォ・セロ|0
409|Radoviš|ラドヴィシュ|0
410|Strumica|ストルミツァ|0
501|Bitola|ビトラ|0
502|Demir Hisar|デミル・ヒサル|0
503|Dolneni|ドルネニ|0
504|Krivogaštani|クリヴォガシュタニ|0
505|Kruševo|クルシェヴォ|0
506|Mogila|モギラ|0
507|Novaci|ノヴァツィ|0
508|Prilep|プリレプ|0
509|Resen|レセン|0
601|Bogovinje|ボゴヴィニェ|0
602|Brvenica|ブルヴェニツァ|0
603|Vrapčište|ヴラプチシュテ|0
604|Gostivar|ゴスティヴァル|0
605|Želino|ジェリノ|0
606|Jegunovce|イェグノヴツェ|0
607|Mavrovo i Rostuše|マヴロヴォ・ロストゥシャ|0
608|Tearce|テアルツェ|0
609|Tetovo|テトヴォ|0
701|Kratovo|クラトヴォ|0
702|Kriva Palanka|クリヴァ・パランカ|0
703|Kumanovo|クマノヴォ|0
704|Lipkovo|リプコヴォ|0
705|Rankovce|ランコヴツェ|0
706|Staro Nagoričane|スタロ・ナゴリチャネ|0
801|Aerodrom †||0
802|Aračinovo|アラチノヴォ|0
803|Butel †||0
804|Gazi Baba †||0
805|Gjorče Petrov †||0
806|Zelenikovo|ゼレニコヴォ|0
807|Ilinden|イリンデン|0
808|Karpoš †||0
809|Kisela Voda †||0
810|Petrovec|ペトロヴェツ|0
811|Saraj †||0
812|Sopište|ソピシュテ|0
813|Studeničani|ストゥデニチャニ|0
814|Centar †||0
815|Čair †||0
816|Čučer-Sandevo|チュチェル・サンデヴォ|0
817|Šuto Orizari †|シュトオリザリ|0`,
};

export { MK };
