// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Myanmar (Burma) (MM): 15 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const MM: SubdivisionTable = {
  country: "MM",
  types: ["region","state","territory"],
  typesJa: ["管区","州",null],
  rows: `01|Sagaing|ザガイン管区|0
02|Bago|バゴー管区|0
03|Magway|マグウェ管区|0
04|Mandalay|マンダレー管区|0
05|Tanintharyi|タニンダーリ管区|0
06|Yangon|ヤンゴン管区|0
07|Ayeyarwady|エーヤワディ管区|0
11|Kachin|カチン州|1
12|Kayah|カヤー州|1
13|Kayin|カレン州|1
14|Chin|チン州|1
15|Mon|モン州|1
16|Rakhine|ラカイン州|1
17|Shan|シャン州|1
18|Naypyidaw|ネピドー連邦領|2`,
};

export { MM };
