// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Malta (MT): 68 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const MT: SubdivisionTable = {
  country: "MT",
  types: ["city","municipality"],
  typesJa: [null,null],
  rows: `01|Attard|アタード|0
02|Balzan|バルツァーン
03|Birgu|ビルグ|0
04|Birkirkara|ビルキルカラ|0
05|Birżebbuġa|ビルゼブジャ|0
06|Cospicua|コスピクア|0
07|Dingli|ディングリ
08|Fgura|フグーラ|0
09|Floriana|フロリアーナ|0
10|Fontana|フォンターナ
11|Gudja|グーディア
12|Gżira|グジラ|0
13|Għajnsielem|アインシーレム|1
14|Għarb|アーブ
15|Għargħur|アーウール
16|Għasri|アーシリ
17|Għaxaq|アーシャ
18|Ħamrun|ハムルーン|0
19|Iklin|イキリン
20|Senglea|セングレア|0
21|Kalkara|カルカラ
22|Kerċem|ケルチャム
23|Kirkop|キルコップ
24|Lija|リーヤ
25|Luqa|ルア|0
26|Marsa|マルサ|0
27|Marsaskala|マルサスカラ|0
28|Marsaxlokk|マルサシロク
29|Mdina|イムディーナ
30|Mellieħa|メリッハ
31|Mġarr|イムジャー
32|Mosta|モスタ|0
33|Mqabba|アッバ|0
34|Msida|イムシーダ|0
35|Imtarfa|イムタルファ
36|Munxar|ムンシー
37|Nadur|ナドゥール|0
38|Naxxar|ナッシャー|0
39|Paola|パウラ|0
40|Pembroke|ペンブローク
41|Pietà|ピータ
42|Qala|アラ
43|Qormi|オルミ|0
44|Qrendi|レンディ
45|Victoria|ヴィクトリア|0
46|Rabat|ラバト|0
47|Safi|サーフィ
48|St. Julian’s|センジュリアン|0
49|San Ġwann|サンジュワン|0
50|Saint Lawrence|サン・ローレンツ
51|St. Paul’s Bay|セントポールズ・ベイ
52|Sannat|サンナット|0
53|Santa Luċija|サンタルーチャ
54|Santa Venera|サンタヴェネラ|0
55|Siġġiewi|シッジウィー|0
56|Sliema|スリマ|0
57|Swieqi|シウィーイ
58|Ta’ Xbiex|タシビイシェ
59|Tarxien|タルシーン|0
60|Valletta|バレッタ|0
61|Xagħra|シャーラ|0
62|Xewkija|シェウキーヤ
63|Xgħajra|シャイラ
64|Żabbar|ザッパール|0
65|Żebbuġ Gozo|ゼブージ
66|Żebbuġ|ゼブージ|0
67|Żejtun|ゼイトゥン|0
68|Żurrieq|ズッリー|0`,
};

export { MT };
