// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Mauritius (MU): 12 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const MU: SubdivisionTable = {
  country: "MU",
  types: ["district","island"],
  typesJa: ["県",null],
  rows: `AG|Agaléga|アガレガ諸島
BL|Rivière Noire|ブラックリバー県|0
CC|Cargados Carajos|カルガドス・カラホス諸島|1
FL|Flacq|フラック県|0
GP|Grand Port|グラン・ポール県|0
MO|Moka|モカ県|0
PA|Pamplemousses|パンプルムース県|0
PL|Port Louis District|ポートルイス県|0
PW|Plaines Wilhems|プレーン・ウィルヘルム県|0
RO|Rodrigues|ロドリゲス島
RR|Rivière du Rempart|リヴィエール・デュ・ランパール県|0
SA|Savanne|サバンナ県|0`,
};

export { MU };
