// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Malawi (MW): 31 subdivisions, at level 1 and 2.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const MW: SubdivisionTable = {
  country: "MW",
  types: ["district","region"],
  typesJa: [null,"州"],
  rows: `BA|Balaka|バラカ|0|S
BL|Blantyre|ブランタイヤ|0|S
C|Central|中部州|1
CK|Chikwawa|チクワワ|0|S
CR|Chiradzulu|チラズル|0|S
CT|Chitipa|チティパ|0|N
DE|Dedza|デッザ|0|C
DO|Dowa|ドーワ|0|C
KR|Karonga|カロンガ|0|N
KS|Kasungu|カスング|0|C
LI|Lilongwe|リロングウェ県|0|C
LK|Likoma|リコマ|0|N
MC|Mchinji|ムチンジ|0|C
MG|Mangochi|マンゴチ|0|S
MH|Machinga|マチンガ|0|S
MU|Mulanje|ムランジェ|0|S
MW|Mwanza|ムワンザ|0|S
MZ|Mzimba|ムジンバ|0|N
N|Northern|北部州|1
NB|Nkhata Bay|カタベイ|0|N
NE|Neno|ネノ|0|S
NI|Ntchisi|ンチシ|0|C
NK|Nkhotakota|コタコタ|0|C
NS|Nsanje|ンサンジェ|0|S
NU|Ntcheu|ンチェウ|0|C
PH|Phalombe|パロンベ|0|S
RU|Rumphi|ルンピ|0|N
S|Southern|南部州|1
SA|Salima|サリマ|0|C
TH|Thyolo|チョロ|0|S
ZO|Zomba|ゾンバ県|0|S`,
};

export { MW };
