// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Mexico (MX): 32 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const MX: SubdivisionTable = {
  country: "MX",
  types: ["capital-district","state"],
  typesJa: [null,"州"],
  rows: `AGU|Aguascalientes|アグアスカリエンテス州|1
BCN|Baja California|バハ・カリフォルニア州|1
BCS|Baja California Sur|バハ・カリフォルニア・スル州|1
CAM|Campeche|カンペチェ州|1
CHH|Chihuahua|チワワ州|1
CHP|Chiapas|チアパス州|1
CMX|Ciudad de Mexico|メキシコシティ|0
COA|Coahuila|コアウイラ州|1
COL|Colima|コリマ州|1
DUR|Durango|ドゥランゴ州|1
GRO|Guerrero|ゲレーロ州|1
GUA|Guanajuato|グアナフアト州|1
HID|Hidalgo|イダルゴ州|1
JAL|Jalisco|ハリスコ州|1
MEX|Mexico State|メヒコ州|1
MIC|Michoacán|ミチョアカン州|1
MOR|Morelos|モレロス州|1
NAY|Nayarit|ナヤリット州|1
NLE|Nuevo León|ヌエボ・レオン州|1
OAX|Oaxaca|オアハカ州|1
PUE|Puebla|プエブラ州|1
QUE|Querétaro|ケレタロ州|1
ROO|Quintana Roo|キンタナ・ロー州|1
SIN|Sinaloa|シナロア州|1
SLP|San Luis Potosí|サン・ルイス・ポトシ州|1
SON|Sonora|ソノラ州|1
TAB|Tabasco|タバスコ州|1
TAM|Tamaulipas|タマウリパス州|1
TLA|Tlaxcala|トラスカラ州|1
VER|Veracruz|ベラクルス州|1
YUC|Yucatán|ユカタン州|1
ZAC|Zacatecas|サカテカス州|1`,
};

export { MX };
