// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Namibia (NA): 14 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const NA: SubdivisionTable = {
  country: "NA",
  types: ["region"],
  typesJa: ["州"],
  rows: `CA|Zambezi|カプリビ州|0
ER|Erongo|エロンゴ州|0
HA|Hardap|ハルダプ州|0
KA|Karas|カラス州|0
KE|Kavango East|東カバンゴ州|0
KH|Khomas|ホマス州|0
KU|Kunene|クネネ州|0
KW|Kavango West|西カバンゴ州|0
OD|Otjozondjupa|オチョソンデュパ州|0
OH|Omaheke|オマヘケ州|0
ON|Oshana|オシャナ州|0
OS|Omusati|オムサティ州|0
OT|Oshikoto|オシコト州|0
OW|Ohangwena|オハングウェナ州|0`,
};

export { NA };
