// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Norway (NO): 13 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const NO: SubdivisionTable = {
  country: "NO",
  types: ["capital-district","county","territory"],
  typesJa: [null,null,null],
  rows: `03|Oslo|オスロ|0
11|Rogaland|ローガラン県|1
15|Møre og Romsdal|ムーレ・オ・ロムスダール県|1
18|Nordland|ヌールラン県|1
21|Svalbard|スヴァールバル諸島|2
22|Jan Mayen|ヤンマイエン島|1
30|Viken|ヴィッケン県
34|Innlandet|インラント県|1
38|Vestfold og Telemark|ヴェストフォル・オ・テレマルク県
42|Agder|アグデル|1
46|Vestland|ヴェストラン県|1
50|Trøndelag|トロンデラーグ|1
54|Tromssan ja Finmarkun|トロムス・オ・フィンマルク県|1`,
};

export { NO };
