// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Nepal (NP): 7 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const NP: SubdivisionTable = {
  country: "NP",
  types: ["province"],
  typesJa: ["州"],
  rows: `P1|Province 1|第一州|0
P2|Province 2|マデシ州|0
P3|Province 3|第三州|0
P4|Gandaki²
P5|Province 5|第五州|0
P6|Karnali²|カルナリ・プラデーシュ州|0
P7|Province 7|第七州|0`,
};

export { NP };
