// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Oman (OM): 11 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const OM: SubdivisionTable = {
  country: "OM",
  types: ["governorate"],
  typesJa: [null],
  rows: `BJ|Janub al Batinah|南バーティナ地方|0
BS|Shamal al Batinah|北バーティナ地方|0
BU|Al Buraimi|ブライミ特別行政区|0
DA|Ad Dakhiliyah|ダーヒリーヤ行政区|0
MA|Muscat|マスカット特別行政区|0
MU|Musandam|ムサンダム特別行政区|0
SJ|Janub ash Sharqiyah|南シャルキーヤ地方|0
SS|Shamal ash Sharqiyah|北シャルキーヤ地方|0
WU|Al Wusta|ウスタ行政区|0
ZA|Ad Dhahirah|ザーヒラ行政区|0
ZU|Dhofar|ドファール特別行政区|0`,
};

export { OM };
