// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Peru (PE): 26 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const PE: SubdivisionTable = {
  country: "PE",
  types: ["department","province"],
  typesJa: ["県",null],
  rows: `AMA|Amazonas|アマソナス県|0
ANC|Ancash|アンカシュ県|0
APU|Apurímac|アプリマク県|0
ARE|Arequipa|アレキパ県|0
AYA|Ayacucho|アヤクーチョ県|0
CAJ|Cajamarca|カハマルカ県|0
CAL|El Callao|カヤオ特別区|1
CUS|Cusco|クスコ県|0
HUC|Huánuco|ワヌコ県|0
HUV|Huancavelica|ワンカベリカ県|0
ICA|Ica|イカ県|0
JUN|Junín|フニン県|0
LAL|La Libertad|ラ・リベルタ県|0
LAM|Lambayeque|ランバイエケ県|0
LIM|Lima Region|リマ県|0
LMA|Lima|リマ郡|1
LOR|Loreto|ロレート県|0
MDD|Madre de Dios|マードレ・デ・ディオス県|0
MOQ|Moquegua|モケグア県|0
PAS|Pasco|パスコ県|0
PIU|Piura|ピウラ県|0
PUN|Puno|プーノ県|0
SAM|San Martín|サン・マルティン県|0
TAC|Tacna|タクナ県|0
TUM|Tumbes|トゥンベス県|0
UCA|Ucayali|ウカヤリ県|0`,
};

export { PE };
