// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Papua New Guinea (PG): 22 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const PG: SubdivisionTable = {
  country: "PG",
  types: ["city","province"],
  typesJa: [null,"州"],
  rows: `CPK|Chimbu|シンブ州|1
CPM|Central|中央州|1
EBR|East New Britain|東ニューブリテン州|1
EHG|Eastern Highlands|東部山岳州|1
EPW|Enga|エンガ州|1
ESW|East Sepik|東セピック州|1
GPK|Gulf|湾岸州|1
HLA|Hela|ヘラ州|1
JWK|Jiwaka|ジワカ州|1
MBA|Milne Bay|ミルン湾州|1
MPL|Morobe|モロベ州|1
MPM|Madang|マダン州|1
MRL|Manus|マヌス州|1
NCD|Port Moresby|ポートモレスビー|0
NIK|New Ireland|ニューアイルランド州|1
NPP|Oro|オロ州|1
NSB|Bougainville|ブーゲンビル州
SAN|Sandaun|サンダウン州|1
SHM|Southern Highlands|南部山岳州|1
WBK|West New Britain|西ニューブリテン州|1
WHM|Western Highlands|西部山岳州|1
WPD|Western|西部州|1`,
};

export { PG };
