// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Poland (PL): 16 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place, Japanese names CLDR lacks

import type { SubdivisionTable } from "../../rows";

const PL: SubdivisionTable = {
  country: "PL",
  types: ["voivodeship"],
  typesJa: ["県"],
  rows: `02|Lower Silesia|ドルヌィ・シロンスク県|0
04|Kuyavia-Pomerania|クヤヴィ＝ポモージェ県|0
06|Lublin|ルブリン県|0
08|Lubusz|ルブシュ県|0
10|Łódź|ウッチ県|0
12|Lesser Poland|マウォポルスカ県|0
14|Mazovia|マゾフシェ県|0
16|Opole|オポーレ県|0
18|Subcarpathia|ポトカルパチェ県|0
20|Podlachia|ポドラシェ県|0
22|Pomerania|ポモージェ県|0
24|Silesia|シロンスク県|0
26|Holy Cross|シフィェンティクシシュ県|0
28|Warmia-Masuria|ヴァルミア＝マズールィ県|0
30|Greater Poland|ヴィエルコポルスカ県|0
32|West Pomerania|西ポモージェ県|0`,
};

export { PL };
