// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Portugal (PT): 20 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const PT: SubdivisionTable = {
  country: "PT",
  types: ["autonomous-region","district"],
  typesJa: [null,"県"],
  rows: `01|Aveiro|アヴェイロ県|1
02|Beja|ベージャ県|1
03|Braga|ブラガ県|1
04|Bragança|ブラガンサ県|1
05|Castelo Branco|カステロ・ブランコ県|1
06|Coimbra|コインブラ県|1
07|Évora|エヴォラ県|1
08|Faro|ファーロ県|1
09|Guarda|グアルダ県|1
10|Leiria|レイリア県|1
11|Lisbon|リスボン県|1
12|Portalegre|ポルタレグレ県|1
13|Porto|ポルト県|1
14|Santarém|サンタレン県|1
15|Setúbal|セトゥーバル県|1
16|Viana do Castelo|ヴィアナ・ド・カステロ県|1
17|Vila Real|ヴィラ・レアル県|1
18|Viseu|ヴィゼウ県|1
20|Azores|アゾレス諸島|0
30|Madeira|マデイラ諸島|0`,
};

export { PT };
