// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Palau (PW): 16 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const PW: SubdivisionTable = {
  country: "PW",
  types: ["state"],
  typesJa: [null],
  rows: `002|Aimeliik|アイメリーク州|0
004|Airai|アイライ州|0
010|Angaur|アンガウル州|0
050|Hatohobei|ハトホベイ州|0
100|Kayangel|カヤンゲル州|0
150|Koror|コロール|0
212|Melekeok|マルキョク州|0
214|Ngaraard|ガラルド州|0
218|Ngarchelong|アルコロン州|0
222|Ngardmau|ガラスマオ州|0
224|Ngatpang|ガスパン州|0
226|Ngchesar|エサール州|0
227|Ngeremlengui|アルモノグイ州|0
228|Ngiwal|オギワル州|0
350|Peleliu|ペリリュー州|0
370|Sonsorol|ソンソロール州|0`,
};

export { PW };
