// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Romania (RO): 42 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place, Japanese names CLDR lacks

import type { SubdivisionTable } from "../../rows";

const RO: SubdivisionTable = {
  country: "RO",
  types: ["county","region"],
  typesJa: [null,"県"],
  rows: `AB|Alba|アルバ県|0
AG|Argeș|アルジェシュ県|0
AR|Arad|アラド県|0
B|Bucharest|ブカレスト|0
BC|Bacău|バカウ県|0
BH|Bihor|ビホル県|0
BN|Bistriţa-Năsăud|ビストリツァ＝ナサウド県|0
BR|Brăila|ブライラ県|0
BT|Botoşani|ボトシャニ県|0
BV|Braşov|ブラショフ県|0
BZ|Buzău|ブザウ県|0
CJ|Cluj|クルジュ県|0
CL|Călărași|カララシ県|0
CS|Caraș-Severin|カラシュ＝セヴェリン県|0
CT|Constanța|コンスタンツァ県|0
CV|Covasna|コヴァスナ県|0
DB|Dâmbovița|ドゥンボヴィツァ県|0
DJ|Dolj|ドルジュ県|0
GJ|Gorj|ゴルジュ県|0
GL|Galați|ガラツィ県|0
GR|Giurgiu|ジュルジュ県|0
HD|Hunedoara|フネドアラ県|0
HR|Harghita|ハルギタ県|0
IF|Ilfov|イルフォヴ県|0
IL|Ialomița|ヤロミツァ県|0
IS|Iași|ヤシ県|0
MH|Mehedinți|メヘディンチ県|0
MM|Maramureş|マラムレシュ県|0
MS|Mureş|ムレシュ県|0
NT|Neamţ|ネアムツ県|0
OT|Olt|オルト県|0
PH|Prahova|プラホヴァ県|0
SB|Sibiu|シビウ県|0
SJ|Sălaj|サラージュ県|0
SM|Satu Mare|サトゥ・マーレ県|0
SV|Suceava|スチャヴァ県|0
TL|Tulcea|トゥルチャ県|0
TM|Timiș|ティミシュ県|1
TR|Teleorman|テレオルマン県|0
VL|Vâlcea|ヴルチャ県|0
VN|Vrancea|ヴランチャ県|0
VS|Vaslui|ヴァスルイ県|0`,
};

export { RO };
