// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Russia (RU): 83 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const RU: SubdivisionTable = {
  country: "RU",
  types: ["autonomous-region","city","krai","oblast","republic"],
  typesJa: [null,null,"地方","州","共和国"],
  rows: `AD|Adygea|アディゲ共和国|4
AL|Altai Republic|アルタイ共和国|4
ALT|Altai Krai|アルタイ地方|2
AMU|Amur|アムール州|3
ARK|Arkhangelsk|アルハンゲリスク州|3
AST|Astrakhan|アストラハン州|3
BA|Bashkortostan|バシコルトスタン共和国|4
BEL|Belgorod|ベルゴロド州|3
BRY|Bryansk|ブリャンスク州|3
BU|Buryatia|ブリヤート共和国|4
CE|Chechnya|チェチェン共和国|4
CHE|Chelyabinsk|チェリャビンスク州|3
CHU|Chukotka Okrug|チュクチ自治管区|0
CU|Chuvashia|チュヴァシ共和国|4
DA|Dagestan|ダゲスタン共和国|4
IN|Ingushetia|イングーシ共和国|4
IRK|Irkutsk|イルクーツク州|3
IVA|Ivanovo|イヴァノヴォ州|3
KAM|Kamchatka Krai|カムチャツカ地方|2
KB|Kabardino-Balkaria|カバルダ・バルカル共和国|4
KC|Karachay-Cherkessia|カラチャイ・チェルケス共和国|4
KDA|Krasnodar Krai|クラスノダール地方|2
KEM|Kemerovo|ケメロヴォ州|3
KGD|Kaliningrad|カリーニングラード州|3
KGN|Kurgan|クルガン州|3
KHA|Khabarovsk Krai|ハバロフスク地方|2
KHM|Khanty-Mansi|ハンティ・マンシ自治管区・ユグラ|0
KIR|Kirov|キーロフ州|3
KK|Khakassia|ハカス共和国|4
KL|Kalmykia|カルムイク共和国|4
KLU|Kaluga|カルーガ州|3
KO|Komi Republic|コミ共和国|4
KOS|Kostroma|コストロマ州|3
KR|Karelia|カレリア共和国|4
KRS|Kursk|クルスク州|3
KYA|Krasnoyarsk Krai|クラスノヤルスク地方|2
LEN|Leningrad|レニングラード州|3
LIP|Lipetsk|リペツク州|3
MAG|Magadan|マガダン州|3
ME|Mari El|マリ・エル共和国|4
MO|Mordovia|モルドヴィア共和国|4
MOS|Moscow Province|モスクワ州|3
MOW|Moscow|モスクワ|1
MUR|Murmansk|ムルマンスク州|3
NEN|Nenets|ネネツ自治管区|0
NGR|Novgorod|ノヴゴロド州|3
NIZ|Nizhny Novgorod|ニジニ・ノヴゴロド州|3
NVS|Novosibirsk|ノヴォシビルスク州|3
OMS|Omsk|オムスク州|3
ORE|Orenburg|オレンブルク州|3
ORL|Oryol|オリョール州|3
PER|Perm Krai|ペルミ地方|2
PNZ|Penza|ペンザ州|3
PRI|Primorsky Krai|沿海地方|2
PSK|Pskov|プスコフ州|3
ROS|Rostov|ロストフ州|3
RYA|Ryazan|リャザン州|3
SA|Sakha|サハ共和国|4
SAK|Sakhalin|サハリン州|3
SAM|Samara|サマラ州|3
SAR|Saratov|サラトフ州|3
SE|North Ossetia-Alania|北オセチア共和国|4
SMO|Smolensk|スモレンスク州|3
SPE|Saint Petersburg|サンクトペテルブルク
STA|Stavropol Krai|スタヴロポリ地方|2
SVE|Sverdlovsk|スヴェルドロフスク州|3
TA|Tatarstan|タタールスタン共和国|4
TAM|Tambov|タンボフ州|3
TOM|Tomsk|トムスク州|3
TUL|Tula|トゥーラ州|3
TVE|Tver|トヴェリ州|3
TY|Tuva|トゥヴァ共和国|4
TYU|Tyumen|チュメニ州|3
UD|Udmurtia|ウドムルト共和国|4
ULY|Ulyanovsk|ウリヤノフスク州|3
VGG|Volgograd|ヴォルゴグラード州|3
VLA|Vladimir|ヴラジーミル州|3
VLG|Vologda|ヴォログダ州|3
VOR|Voronezh|ヴォロネジ州|3
YAN|Yamalo-Nenets Okrug|ヤマロ・ネネツ自治管区|0
YAR|Yaroslavl|ヤロスラヴリ州|3
YEV|Jewish|ユダヤ自治州|0
ZAB|Zabaykalsky Krai|ザバイカリエ地方|2`,
};

export { RU };
