// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Rwanda (RW): 5 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const RW: SubdivisionTable = {
  country: "RW",
  types: ["capital-district","province"],
  typesJa: [null,"州"],
  rows: `01|Kigali|キガリ|0
02|Eastern|東部州|1
03|Northern|北部州|1
04|Western|西部州|1
05|Southern|南部州|1`,
};

export { RW };
