// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Saudi Arabia (SA): 13 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const SA: SubdivisionTable = {
  country: "SA",
  types: ["province"],
  typesJa: ["州"],
  rows: `01|Riyadh|リヤード州|0
02|Makkah|マッカ州|0
03|Al Madinah|マディーナ州|0
04|Eastern|東部州|0
05|Al-Qassim|カスィーム州|0
06|Ha’il|ハーイル州|0
07|Tabuk|タブーク州|0
08|Northern Borders|北部国境州|0
09|Jizan|ジーザーン州|0
10|Najran|ナジュラーン州|0
11|Al Bahah|バーハ州|0
12|Al Jawf|ジャウフ州|0
14|Asir|アスィール州|0`,
};

export { SA };
