// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Solomon Islands (SB): 10 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const SB: SubdivisionTable = {
  country: "SB",
  types: ["city","province"],
  typesJa: [null,"州"],
  rows: `CE|Central|中央州|1
CH|Choiseul|チョイスル州|1
CT|Honiara|ホニアラ|0
GU|Guadalcanal|ガダルカナル州|1
IS|Isabel|イサベル州|1
MK|Makira-Ulawa|マキラ・ウラワ州|1
ML|Malaita|マライタ州|1
RB|Rennell and Bellona|レンネル・ベローナ州|1
TE|Temotu|テモツ州|1
WE|Western|西部州|1`,
};

export { SB };
