// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Seychelles (SC): 27 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place, Japanese names CLDR lacks

import type { SubdivisionTable } from "../../rows";

const SC: SubdivisionTable = {
  country: "SC",
  types: ["district"],
  typesJa: [null],
  rows: `01|Anse aux Pins|アンセ=エクス=プリス|0
02|Anse Boileau|アンセ・ボイレヤー|0
03|Anse Etoile|アンセ・エチオエ|0
04|Au Cap|アウ・カップ|0
05|Anse Royale|アンセ・ロイヤル|0
06|Baie Lazare|バイエ・ロザーレ|0
07|Baie Sainte Anne|バイエ・セント・アンセ|0
08|Beau Vallon|ベウ・バロン|0
09|Bel Air|ベル・エアー|0
10|Bel Ombre|ベル・オンブレ|0
11|Cascade|カスカドゥ|0
12|Glacis|グラシ|0
13|Grand’Anse Mahé|グランド・アンセ・マーヘ|0
14|Grand’Anse Praslin|グランド・アンセ・プラスリン|0
15|La Digue|ラ・ディーグ島|0
16|La Rivière Anglaise|ラ・リヴィエール・アングレーズ|0
17|Mont Buxton|モント・ブクソン|0
18|Mont Fleuri|モント・フレーリー|0
19|Plaisance|プライセンス|0
20|Pointe La Rue|ポイント・ラ・ルエ|0
21|Port Glaud|ポート・グランド|0
22|Saint Louis|セント・ローイス|0
23|Takamaka|タカマカ|0
24|Les Mamelles|レス・マーメルズ|0
25|Roche Caiman|ロッチェ・チャイマン|0
26|Ile Perseverance I||0
27|Ile Perseverance II||0`,
};

export { SC };
