// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Sweden (SE): 21 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const SE: SubdivisionTable = {
  country: "SE",
  types: ["county"],
  typesJa: ["県"],
  rows: `AB|Stockholm|ストックホルム県|0
AC|Västerbotten|ヴェステルボッテン県|0
BD|Norrbotten|ノールボッテン県|0
C|Uppsala|ウプサラ県|0
D|Södermanland|セーデルマンランド県|0
E|Östergötland|エステルイェータランド県|0
F|Jönköping|ヨンショーピング県|0
G|Kronoberg|クロノベリ県|0
H|Kalmar|カルマル県|0
I|Gotland|ゴットランド県|0
K|Blekinge|ブレーキンゲ県|0
M|Skåne|スコーネ県|0
N|Halland|ハッランド県|0
O|Västra Götaland|ヴェストラ・イェータランド県|0
S|Värmland|ヴェルムランド県|0
T|Örebro|エレブルー県|0
U|Västmanland|ヴェストマンランド県|0
W|Dalarna|ダーラナ県|0
X|Gävleborg|イェヴレボリ県|0
Y|Västernorrland|ヴェステルノールランド県|0
Z|Jämtland|イェムトランド県|0`,
};

export { SE };
