// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Singapore (SG): 5 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const SG: SubdivisionTable = {
  country: "SG",
  types: [],
  typesJa: [],
  rows: `01|Central Singapore|シンガポール中央地区
02|North East|北東地区 (シンガポール)
03|North West|北西地区 (シンガポール)
04|South East|南東地区
05|South West|南西地区 (シンガポール)`,
};

export { SG };
