// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// St. Helena (SH): 3 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const SH: SubdivisionTable = {
  country: "SH",
  types: [],
  typesJa: [],
  rows: `AC|Ascension Island|アセンション島
HL|Saint Helena|セントヘレナ
TA|Tristan da Cunha|トリスタン・ダ・クーニャ`,
};

export { SH };
