// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Slovakia (SK): 8 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const SK: SubdivisionTable = {
  country: "SK",
  types: ["region"],
  typesJa: ["県"],
  rows: `BC|Banská Bystrica|バンスカー・ビストリツァ県|0
BL|Bratislava|ブラチスラヴァ県|0
KI|Košice|コシツェ県|0
NI|Nitra|ニトラ県|0
PV|Prešov|プレショウ県|0
TA|Trnava|トルナヴァ県|0
TC|Trenčín|トレンチーン県|0
ZI|Žilina|ジリナ県|0`,
};

export { SK };
