// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Sierra Leone (SL): 5 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const SL: SubdivisionTable = {
  country: "SL",
  types: ["province"],
  typesJa: [null],
  rows: `E|Eastern|東部州|0
N|Northern|北部州|0
NW|North Western|北西部州|0
S|Southern|南部州|0
W|Western Area|西部地域|0`,
};

export { SL };
