// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// San Marino (SM): 9 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const SM: SubdivisionTable = {
  country: "SM",
  types: ["municipality"],
  typesJa: [null],
  rows: `01|Acquaviva|アックアヴィーヴァ|0
02|Chiesanuova|キエザヌオーヴァ|0
03|Domagnano|ドマニャーノ|0
04|Faetano|ファエターノ|0
05|Fiorentino|フィオレンティーノ|0
06|Borgo Maggiore|ボルゴ・マッジョーレ|0
07|San Marino|サンマリノ市|0
08|Montegiardino|モンテジャルディーノ|0
09|Serravalle|セラヴァッレ|0`,
};

export { SM };
