// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// South Sudan (SS): 10 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const SS: SubdivisionTable = {
  country: "SS",
  types: ["state"],
  typesJa: ["州"],
  rows: `BN|Northern Bahr el Ghazal|北バハル・アル・ガザール州|0
BW|Western Bahr el Ghazal|西バハル・アル・ガザール州|0
EC|Central Equatoria|中央エクアトリア州|0
EE|Eastern Equatoria|東エクアトリア州|0
EW|Western Equatoria|西エクアトリア州|0
JG|Jonglei|ジョングレイ州|0
LK|Lakes|レイク州|0
NU|Upper Nile|上ナイル州|0
UY|Unity|ユニティ州|0
WR|Warrap|ワラブ州|0`,
};

export { SS };
