// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Syria (SY): 14 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const SY: SubdivisionTable = {
  country: "SY",
  types: ["governorate"],
  typesJa: ["県"],
  rows: `DI|Damascus|ダマスカス県|0
DR|Daraa|ダルアー県|0
DY|Deir ez-Zor|デリゾール県|0
HA|Al-Hasakah|ハサカ県|0
HI|Homs|ホムス県|0
HL|Aleppo|アレッポ県|0
HM|Hama|ハマー県|0
ID|Idlib|イドリブ県|0
LA|Latakia|ラタキア県|0
QU|Quneitra|クネイトラ県|0
RA|Ar-Raqqah|ラッカ県|0
RD|Rif Dimashq|ダマスカス郊外県|0
SU|As-Suwayda|スワイダー県|0
TA|Tartus|タルトゥース県|0`,
};

export { SY };
