// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Eswatini (SZ): 4 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const SZ: SubdivisionTable = {
  country: "SZ",
  types: ["region"],
  typesJa: [null],
  rows: `HH|Hhohho|ホホ|0
LU|Lubombo|ルボンボ|0
MA|Manzini|マンジニ地方|0
SH|Shiselweni|シセルウェニ|0`,
};

export { SZ };
