// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Togo (TG): 5 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const TG: SubdivisionTable = {
  country: "TG",
  types: ["region"],
  typesJa: ["州"],
  rows: `C|Centrale|中央州|0
K|Kara|カラ州|0
M|Maritime|沿岸州|0
P|Plateaux|高原州|0
S|Savanes|サバナ州|0`,
};

export { TG };
