// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Thailand (TH): 78 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const TH: SubdivisionTable = {
  country: "TH",
  types: ["capital-district","city","province"],
  typesJa: [null,null,"県"],
  rows: `10|Bangkok|バンコク|0
11|Samut Prakan|サムットプラーカーン県|2
12|Nonthaburi|ノンタブリー県|2
13|Pathum Thani|パトゥムターニー県|2
14|Phra Nakhon Si Ayutthaya|アユタヤ県|2
15|Ang Thong|アーントーン県|2
16|Lopburi|ロッブリー県|2
17|Sing Buri|シンブリー県|2
18|Chai Nat|チャイナート県|2
19|Saraburi|サラブリー県|2
20|Chon Buri|チョンブリー県|2
21|Rayong|ラヨーン県|2
22|Chanthaburi|チャンタブリー県|2
23|Trat|トラート県|2
24|Chachoengsao|チャチューンサオ県|2
25|Prachin Buri|プラーチーンブリー県|2
26|Nakhon Nayok|ナコーンナーヨック県|2
27|Sa Kaeo|サケーオ県|2
30|Nakhon Ratchasima|ナコーンラーチャシーマー県|2
31|Buri Ram|ブリーラム県|2
32|Surin|スリン県|2
33|Si Sa Ket|シーサケート県|2
34|Ubon Ratchathani|ウボンラーチャターニー県|2
35|Yasothon|ヤソートーン県|2
36|Chaiyaphum|チャイヤプーム県|2
37|Amnat Charoen|アムナートチャルーン県|2
38|Bueng Kan|ブンカーン県|2
39|Nong Bua Lam Phu|ノーンブワラムプー県|2
40|Khon Kaen|コーンケン県|2
41|Udon Thani|ウドーンターニー県|2
42|Loei|ルーイ県|2
43|Nong Khai|ノーンカーイ県|2
44|Maha Sarakham|マハーサーラカーム県|2
45|Roi Et|ローイエット県|2
46|Kalasin|カーラシン県|2
47|Sakon Nakhon|サコンナコーン県|2
48|Nakhon Phanom|ナコーンパノム県|2
49|Mukdahan|ムックダーハーン県|2
50|Chiang Mai|チエンマイ県|2
51|Lamphun|ラムプーン県|2
52|Lampang|ラムパーン県|2
53|Uttaradit|ウッタラディット県|2
54|Phrae|プレー県|2
55|Nan|ナーン県|2
56|Phayao|パヤオ県|2
57|Chiang Rai|チエンラーイ県|2
58|Mae Hong Son|メーホンソーン県|2
60|Nakhon Sawan|ナコーンサワン県|2
61|Uthai Thani|ウタイターニー県|2
62|Kamphaeng Phet|カムペーンペット県|2
63|Tak|ターク県|2
64|Sukhothai|スコータイ県|2
65|Phitsanulok|ピッサヌローク県|2
66|Phichit|ピチット県|2
67|Phetchabun|ペッチャブーン県|2
70|Ratchaburi|ラーチャブリー県|2
71|Kanchanaburi|カーンチャナブリー県|2
72|Suphanburi|スパンブリー県|2
73|Nakhon Pathom|ナコーンパトム県|2
74|Samut Sakhon|サムットサーコーン県|2
75|Samut Songkhram|サムットソンクラーム県|2
76|Phetchaburi|ペッチャブリー県|2
77|Prachuap Khiri Khan|プラチュワップキーリーカン県|2
80|Nakhon Si Thammarat|ナコーンシータンマラート県|2
81|Krabi|クラビー県|2
82|Phang Nga|パンガー県|2
83|Phuket|プーケット県|2
84|Surat Thani|スラートターニー県|2
85|Ranong|ラノーン県|2
86|Chumphon|チュムポーン県|2
90|Songkhla|ソンクラー県|2
91|Satun|サトゥーン県|2
92|Trang|トラン県|2
93|Phatthalung|パッタルン県|2
94|Pattani|パッターニー県|2
95|Yala|ヤラー県|2
96|Narathiwat|ナラーティワート県|2
S|Pattaya|パッタヤー|1`,
};

export { TH };
