// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Tajikistan (TJ): 5 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const TJ: SubdivisionTable = {
  country: "TJ",
  types: ["capital-district","region"],
  typesJa: [null,null],
  rows: `DU|Dushanbe|ドゥシャンベ|0
GB|Gorno-Badakhshan|ゴルノ・バダフシャン自治州|1
KT|Khatlon|ハトロン州|1
RA|Nohiyahoi Tobei Jumhurí|共和国直轄地|1
SU|Sughd|ソグド州|1`,
};

export { TJ };
