// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Timor-Leste (TL): 13 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place, Japanese names CLDR lacks

import type { SubdivisionTable } from "../../rows";

const TL: SubdivisionTable = {
  country: "TL",
  types: ["municipality","special-administrative-region"],
  typesJa: ["県",null],
  rows: `AL|Aileu|アイレウ県|0
AN|Ainaro|アイナロ県|0
BA|Baucau|バウカウ県|0
BO|Bobonaro|ボボナロ県|0
CO|Cova Lima|コヴァ・リマ県|0
DI|Dili|ディリ県|0
ER|Ermera|エルメラ県|0
LA|Lautém|ラウテン県|0
LI|Liquiçá|リキシャ県|0
MF|Manufahi|マヌファヒ県|0
MT|Manatuto|マナトゥト県|0
OE|Oecusse|オエクシ＝アンベノ|1
VI|Viqueque|ヴィケケ県|0`,
};

export { TL };
