// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Tunisia (TN): 24 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const TN: SubdivisionTable = {
  country: "TN",
  types: ["governorate"],
  typesJa: ["県"],
  rows: `11|Tunis|チュニス県|0
12|Ariana|アリアナ県|0
13|Ben Arous|ベンナラス県|0
14|Manouba|マヌーバ県|0
21|Nabeul|ナブール県|0
22|Zaghouan|ザグアン県|0
23|Bizerte|ビゼルト県|0
31|Béja|ベジャ県|0
32|Jendouba|ジェンドゥーバ県|0
33|Kef|ケフ県|0
34|Siliana|シリアナ県|0
41|Kairouan|ケルアン県|0
42|Kasserine|カスリーヌ県|0
43|Sidi Bouzid|シディブジッド県|0
51|Sousse|スース県|0
52|Monastir|モナスティル県|0
53|Mahdia|マーディア県|0
61|Sfax|スファックス県|0
71|Gafsa|ガフサ県|0
72|Tozeur|トズール県|0
73|Kebili|ケビリ県|0
81|Gabès|ガベズ県|0
82|Medenine|メドニン県|0
83|Tataouine|タタウイヌ県|0`,
};

export { TN };
