// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Tonga (TO): 5 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const TO: SubdivisionTable = {
  country: "TO",
  types: ["division"],
  typesJa: [null],
  rows: `01|ʻEua|エウア島|0
02|Haʻapai|ハアパイ諸島|0
03|Niuas|ニウアス諸島|0
04|Tongatapu|トンガタプ島|0
05|Vavaʻu|ヴァヴァウ諸島|0`,
};

export { TO };
