// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Türkiye (TR): 81 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const TR: SubdivisionTable = {
  country: "TR",
  types: ["province"],
  typesJa: ["県"],
  rows: `01|Adana|アダナ県|0
02|Adıyaman|アドゥヤマン県|0
03|Afyonkarahisar|アフィヨンカラヒサール県|0
04|Ağrı|アール県|0
05|Amasya|アマスィヤ県|0
06|Ankara|アンカラ県|0
07|Antalya|アンタルヤ県|0
08|Artvin|アルトヴィン県|0
09|Aydın|アイドゥン県|0
10|Balıkesir|バルケスィル県|0
11|Bilecik|ビレジク県|0
12|Bingöl|ビンギョル県|0
13|Bitlis|ビトリス県|0
14|Bolu|ボル県|0
15|Burdur|ブルドゥル県|0
16|Bursa|ブルサ県|0
17|Çanakkale|チャナッカレ県|0
18|Çankırı|チャンクル県|0
19|Çorum|チョルム県|0
20|Denizli|デニズリ県|0
21|Diyarbakır|ディヤルバクル県|0
22|Edirne|エディルネ県|0
23|Elazığ|エラズー県|0
24|Erzincan|エルズィンジャン県|0
25|Erzurum|エルズルム県|0
26|Eskişehir|エスキシェヒル県|0
27|Gaziantep|ガズィアンテプ県|0
28|Giresun|ギレスン県|0
29|Gümüşhane|ギュミュシュハーネ県|0
30|Hakkâri|ハッキャリ県|0
31|Hatay|ハタイ県|0
32|Isparta|ウスパルタ県|0
33|Mersin|メルスィン県|0
34|Istanbul|イスタンブール県|0
35|Izmir|イズミル県|0
36|Kars|カルス県|0
37|Kastamonu|カスタモヌ県|0
38|Kayseri|カイセリ県|0
39|Kırklareli|クルクラーレリ県|0
40|Kırşehir|クルシェヒル県|0
41|Kocaeli|コジャエリ県|0
42|Konya|コンヤ県|0
43|Kütahya|キュタヒヤ県|0
44|Malatya|マラティヤ県|0
45|Manisa|マニサ県|0
46|Kahramanmaraş|カフラマンマラシュ県|0
47|Mardin|マルディン県|0
48|Muğla|ムーラ県|0
49|Muş|ムシュ県|0
50|Nevşehir|ネヴシェヒル県|0
51|Niğde|ニーデ県|0
52|Ordu|オルドゥ県|0
53|Rize|リゼ県|0
54|Sakarya|サカリヤ県|0
55|Samsun|サムスン県|0
56|Siirt|スィイルト県|0
57|Sinop|スィノプ県|0
58|Sivas|スィヴァス県|0
59|Tekirdağ|テキルダー県|0
60|Tokat|トカト県|0
61|Trabzon|トラブゾン県|0
62|Tunceli|トゥンジェリ県|0
63|Şanlıurfa|シャンルウルファ県|0
64|Uşak|ウシャク県|0
65|Van|ヴァン県|0
66|Yozgat|ヨズガト県|0
67|Zonguldak|ゾングルダク県|0
68|Aksaray|アクサライ県|0
69|Bayburt|バイブルト県|0
70|Karaman|カラマン県|0
71|Kırıkkale|クルッカレ県|0
72|Batman|バトマン県|0
73|Şırnak|シュルナク県|0
74|Bartın|バルトゥン県|0
75|Ardahan|アルダハン県|0
76|Iğdır|ウードゥル県|0
77|Yalova|ヤロヴァ県|0
78|Karabük|カラビュック県|0
79|Kilis|キリス県|0
80|Osmaniye|オスマニエ県|0
81|Düzce|デュズジェ県|0`,
};

export { TR };
