// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Taiwan (TW): 22 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const TW: SubdivisionTable = {
  country: "TW",
  types: ["capital-district","city","county","municipality"],
  typesJa: ["市","市","県","市"],
  rows: `CHA|Changhua|彰化県|2
CYI|Chiayi City|嘉義市|1
CYQ|Chiayi County|嘉義県|2
HSQ|Hsinchu County|新竹県|2
HSZ|Hsinchu|新竹市|1
HUA|Hualien|花蓮県|2
ILA|Yilan|宜蘭県|2
KEE|Keelung|基隆市|1
KHH|Kaohsiung|高雄市|3
KIN|Kinmen|金門県|2
LIE|Lienchiang|連江県|2
MIA|Miaoli|苗栗県|2
NAN|Nantou|南投県|2
NWT|New Taipei|新北市|3
PEN|Penghu|澎湖県|2
PIF|Pingtung|屏東県|2
TAO|Taoyuan|桃園市|3
TNN|Tainan|台南市|3
TPE|Taipei|台北市|0
TTT|Taitung|台東県|2
TXG|Taichung|台中市|3
YUN|Yunlin|雲林県|2`,
};

export { TW };
