// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Ukraine (UA): 27 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place, Japanese names CLDR lacks

import type { SubdivisionTable } from "../../rows";

const UA: SubdivisionTable = {
  country: "UA",
  types: ["city","oblast","republic"],
  typesJa: [null,"州","自治共和国"],
  rows: `05|Vinnychchyna|ヴィーンヌィツャ州|1
07|Volyn|ヴォルィーニ州|1
09|Luhanshchyna|ルハーンシク州|1
12|Dnipropetrovshchyna|ドニプロペトロウシク州|1
14|Donechchyna|ドネツィク州|1
18|Zhytomyrshchyna|ジトームィル州|1
21|Zakarpattia|ザカルパッチャ州|1
23|Zaporizhzhya|ザポリージャ州|1
26|Prykarpattia|イヴァーノ＝フランキーウシク州|1
30|Kyiv|キエフ|0
32|Kyivshchyna|キエフ州|1
35|Kirovohradschyna|キロヴォフラード州|1
40|Sevastopol|セヴァストポリ|0
43|Crimea|クリミア自治共和国|2
46|Lvivshchyna|リヴィウ州|1
48|Mykolayivschyna|ムィコラーイウ州|1
51|Odeshchyna|オデッサ州|1
53|Poltavshchyna|ポルタヴァ州|1
56|Rivnenshchyna|リウネ州|1
59|Sumshchyna|スームィ州|1
61|Ternopilshchyna|テルノーピリ州|1
63|Kharkivshchyna|ハルキウ州|1
65|Khersonshchyna|ヘルソン州|1
68|Khmelnychchyna|フメリヌィーツィクィイ州|1
71|Cherkashchyna|チェルカースィ州|1
74|Chernihivshchyna|チェルニーヒウ州|1
77|Chernivtsi Oblast|チェルニウツィー州|1`,
};

export { UA };
