// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Uruguay (UY): 19 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const UY: SubdivisionTable = {
  country: "UY",
  types: ["department"],
  typesJa: ["県"],
  rows: `AR|Artigas|アルティガス県|0
CA|Canelones|カネロネス県|0
CL|Cerro Largo|セロ・ラルゴ県|0
CO|Colonia|コロニア県|0
DU|Durazno|ドゥラスノ県|0
FD|Florida|フロリダ県|0
FS|Flores|フロレス県|0
LA|Lavalleja|ラバジェハ県|0
MA|Maldonado|マルドナド県|0
MO|Montevideo|モンテビデオ県|0
PA|Paysandú|パイサンドゥ県|0
RN|Río Negro|リオ・ネグロ県|0
RO|Rocha|ロチャ県|0
RV|Rivera|リベラ県|0
SA|Salto|サルト県|0
SJ|San José|サン・ホセ県|0
SO|Soriano|ソリアノ県|0
TA|Tacuarembó|タクアレンボー県|0
TT|Treinta y Tres|トレインタ・イ・トレス県|0`,
};

export { UY };
