// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Uzbekistan (UZ): 14 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const UZ: SubdivisionTable = {
  country: "UZ",
  types: ["capital-district","region","republic"],
  typesJa: [null,"州","共和国"],
  rows: `AN|Andijan|アンディジャン州|1
BU|Bukhara|ブハラ州|1
FA|Fergana|フェルガナ州|1
JI|Jizzakh|ジザフ州|1
NG|Namangan|ナマンガン州|1
NW|Navoiy|ナヴァーイー州|1
QA|Qashqadaryo|カシュカダリヤ州|1
QR|Karakalpakstan|カラカルパクスタン共和国|2
SA|Samarqand|サマルカンド州|1
SI|Sirdaryo|シルダリヤ州|1
SU|Surxondaryo|スルハンダリヤ州|1
TK|Tashkent|タシュケント|0
TO|Tashkent Province|タシュケント州|1
XO|Xorazm|ホラズム州|1`,
};

export { UZ };
