// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Venezuela (VE): 25 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const VE: SubdivisionTable = {
  country: "VE",
  types: ["capital-district","state"],
  typesJa: [null,"州"],
  rows: `A|Capital|首都地区|0
B|Anzoátegui|アンソアテギ州|1
C|Apure|アプレ州|1
D|Aragua|アラグア州|1
E|Barinas|バリナス州|1
F|Bolívar|ボリバル州|1
G|Carabobo|カラボボ州|1
H|Cojedes|コヘデス州|1
I|Falcón|ファルコン州|1
J|Guárico|グアリコ州|1
K|Lara|ララ州|1
L|Mérida|メリダ州|1
M|Miranda|ミランダ州|1
N|Monagas|モナガス州|1
O|Nueva Esparta|ヌエバ・エスパルタ州|1
P|Portuguesa|ポルトゥゲサ州|1
R|Sucre|スクレ州|1
S|Táchira|タチラ州|1
T|Trujillo|トルヒージョ州|1
U|Yaracuy|ヤラクイ州|1
V|Zulia|スリア州|1
W|Federal Dependencies|ベネズエラ連邦保護領|0
X|Vargas|バルガス州|1
Y|Delta Amacuro|デルタアマクロ州|1
Z|Amazonas|アマソナス州|1`,
};

export { VE };
