// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Vanuatu (VU): 6 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const VU: SubdivisionTable = {
  country: "VU",
  types: ["province"],
  typesJa: ["州"],
  rows: `MAP|Malampa|マランパ州|0
PAM|Penama|ペナマ州|0
SAM|Sanma|サンマ州|0
SEE|Shefa|シェファ州|0
TAE|Tafea|タフェア州|0
TOB|Torba|トルバ州|0`,
};

export { VU };
