// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Samoa (WS): 11 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place, Japanese names CLDR lacks

import type { SubdivisionTable } from "../../rows";

const WS: SubdivisionTable = {
  country: "WS",
  types: ["district"],
  typesJa: [null],
  rows: `AA|A’ana|アアーナ|0
AL|Aiga-i-le-Tai|アイガイレタイ|0
AT|Atua|アトゥア|0
FA|Fa’asaleleaga|ファアセールリーガ|0
GE|Gaga’emauga|ガガイーモーガ|0
GI|Gaga’ifomauga|ガガイフォモーガ|0
PA|Palauli|パラウリ|0
SA|Satupa’itea|サチューパイテア|0
TU|Tuamasaga|ツアマサガ|0
VF|Va’a-o-Fonoti|バア＝オ＝フォノッティ|0
VS|Vaisigano|ベサイガーノ|0`,
};

export { WS };
