// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// South Africa (ZA): 9 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const ZA: SubdivisionTable = {
  country: "ZA",
  types: ["province"],
  typesJa: ["州"],
  rows: `EC|Eastern Cape|東ケープ州|0
FS|Free State|フリーステイト州|0
GP|Gauteng|ハウテン州|0
KZN|KwaZulu-Natal|クワズール・ナタール州|0
LP|Limpopo|リンポポ州|0
MP|Mpumalanga|ムプマランガ州|0
NC|Northern Cape|北ケープ州|0
NW|North West|北西州|0
WC|Western Cape|西ケープ州|0`,
};

export { ZA };
