// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// Zambia (ZM): 10 subdivisions, at level 1.
// Source: Unicode CLDR 48.2.0 (Unicode-3.0), https://raw.githubusercontent.com/unicode-org/cldr/release-48-2/common/subdivisions/en.xml (read 2026-10-09) and ja.xml
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-2026-10-09.json: kinds of place

import type { SubdivisionTable } from "../../rows";

const ZM: SubdivisionTable = {
  country: "ZM",
  types: ["province"],
  typesJa: ["州"],
  rows: `01|Western|西部州|0
02|Central|中央州|0
03|Eastern|東部州|0
04|Luapula|ルアプラ州|0
05|Northern|北部州|0
06|North-Western|北西州|0
07|Southern|南部州|0
08|Copperbelt|カッパーベルト州|0
09|Lusaka|ルサカ州|0
10|Muchinga|ムチンガ州|0`,
};

export { ZM };
