// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 7 subdivisions of Andorra (AD): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const AD: SubdivisionFactsTable = {
  country: "AD",
  rows: `02|Canillo|||42.57|1.6|5781|2023|121||42.57|1.6
03|Encamp|||42.52|1.57|12826|2023|74||42.54|1.58
04|La Massana|||42.54|1.52|11591|2023|65||42.54|1.52
05|Ordino|||42.55|1.53|5440|2023|90||42.55|1.53
06|Sant Julià de Lòria|||42.46|1.49|9915|2023|61||42.47|1.49
07|Andorra la Vella|アンドラ・ラ・ベリャ||42.51|1.52
08|Les Escaldes|レス・エスカルデス||42.51|1.54|15506|2023|30||42.51|1.54`,
};

export { AD };
