// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 7 subdivisions of United Arab Emirates (AE): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const AE: SubdivisionFactsTable = {
  country: "AE",
  rows: `AJ|Ajman|アジュマーン||25.4|55.48|504836|2017|259||25.4|55.5
AZ|Abu Dhabi|アブダビ||24.45|54.4|2908173|2016|73060||23.67|54
DU|Dubai|ドバイ||25.27|55.31|3825000|2025|4114||25.26|55.31
FU|Fujairah|フジャイラ市||25.12|56.33|256256|2019|1165||25.13|56.33
RK|Ras al-Khaimah|ラアス・アル＝ハイマ市||25.79|55.95|241000|2009|2486||25.78|55.95
SH|Sharjah|シャールジャ||25.34|55.41|1405843|2015|2590||25.35|55.43
UQ|Umm Al Quwain|ウンム・アル＝カイワイン市||25.56|55.56|73000|2015|777||25.55|55.55`,
};

export { AE };
