// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 12 subdivisions of Albania (AL): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const AL: SubdivisionFactsTable = {
  country: "AL",
  rows: `01|Berat|ベラト||40.7|19.95|115050|2022|1798||40.63|20.08
02|Durrës|ドゥラス||41.31|19.45|291325|2022|766||41.5|19.58
03|Elbasan|エルバサン||41.11|20.08|259112|2022|872||41|20.17
04|Fier|フィエル||40.72|19.55|278413|2022|1890||40.75|19.58
05|Gjirokastër|ジロカストラ||40.08|20.14|55278|2022|2884||40.17|20.17
06|Korçë|コルチャ||40.62|20.77|197303|2022|3711||40.58|20.67
07|Kukës|クケス||42.08|20.42|72768|2022|2374||42.17|20.33
08|Lezhë|レジャ||41.78|19.64|117283|2022|1620||41.75|19.83
09|Peshkopi|ペシュコピ||41.68|20.43|109585|2022|2586||41.58|20.25
10|Shkodër|シュコドラ||42.07|19.51|193009|2022|3562||42.17|19.75
11|Tirana|ティラナ||41.33|19.82|919511|2022|1652||41.25|19.75
12|Vlorë|ヴロラ||40.45|19.48|184955|2022|2706||40.17|19.75`,
};

export { AL };
