// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 18 subdivisions of Angola (AO): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const AO: SubdivisionFactsTable = {
  country: "AO",
  rows: `BGO|Dande|||-8.58|13.66|716335|2024|20310||-8.78|13.98
BGU|Benguela|ベンゲラ||-12.55|13.42|2597638|2024|39826||-12.67|14.02
BIE|Kuito|クイト||-12.38|16.93|2264874|2024|70314||-12.52|17.57
CAB|Cabinda|カビンダ||-5.57|12.2|903370|2024|7270||-4.93|12.41
CCU|Menongue|メノングエ||-14.66|17.68|534002|2014|199049||-16.08|19.5
CNN|Ondjiva|オンジヴァ||-17.07|15.73|1806417|2024|87342||-16.7|16.05
CNO|N'dalatando|ヌダラタンド||-9.3|14.92|659097|2024|24110||-9.02|15.07
CUS|Sumbe|スンベ||-11.21|13.84|2327981|2024|55600||-10.63|14.5
HUA|Huambo|ウアンボ||-12.77|15.73|2691902|2024|34274||-12.5|15.67
HUI|Lubango|ルバンゴ||-14.92|13.5|3302866|2024|79022||-14.25|14.83
LNO|Dundo|ドゥンド||-7.38|20.84|1742217|2024|103760||-8.28|19.6
LSU|Saurimo|サウリモ||-9.66|20.39|893936|2024|77637||-10.32|20.82
LUA|Luanda|ルアンダ||-8.84|13.23|8816297|2024|18826||-8.98|13.28
MAL|Malanje|マランジェ||-9.54|16.34|1298250|2024|97602||-9.53|16.35
MOX|Luena|ルエナ||-11.78|19.91|574253|2024|126432||-11.79|19.91
NAM|Moçâmedes|モザメデス||-15.2|12.15|815708|2024|57091||-15.2|12.15
UIG|Uíge|ウイジェ||-7.61|15.06|2017921|2024|58698||-7.62|15.05
ZAI|M'banza-Kongo|ンバンザ＝コンゴ||-6.27|14.25|682658|2024|40130||-6.27|14.23`,
};

export { AO };
