// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 11 subdivisions of Barbados (BB): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const BB: SubdivisionFactsTable = {
  country: "BB",
  rows: `01||||||54336|2010|57||13.08|-59.53
02||||||5139|2010|36||13.23|-59.57
03||||||19767|2010|44||13.13|-59.53
04||||||28498|2010|31||13.22|-59.62
05||||||8963|2010|34||13.17|-59.48
06||||||6620|2010|26||13.2|-59.53
07||||||9758|2010|36||13.3|-59.62
08||||||88529|2010|39||13.12|-59.6
09||||||11300|2010|34||13.25|-59.62
10||||||30662|2010|60||13.12|-59.47
11||||||14249|2010|34||13.18|-59.58`,
};

export { BB };
