// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 4 subdivisions of Bahrain (BH): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const BH: SubdivisionFactsTable = {
  country: "BH",
  rows: `13|Manama|マナーマ||26.22|50.58|534939|2020|68||26.24|50.58
14||||||298244|2020|438||25.92|50.55
15|Al-Muharraq|ムハッラク||26.25|50.61|263373|2020|57||26.25|50.62
17||||||375648|2020|175||26.12|50.48`,
};

export { BH };
