// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 18 subdivisions of Burundi (BI): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const BI: SubdivisionFactsTable = {
  country: "BI",
  rows: `BB|Bubanza|ブバンザ||-3.08|29.4|338023|2008|1089.04||-3.15|29.37
BL|Isale|||-3.34|29.48|555933|2008|1319.12||-3.38|29.43
BM|Bujumbura|ブジュンブラ||-3.38|29.36|497166|2008|86.52||-3.38|29.36
BR|Bururi|ブルリ||-3.93|29.62|574013|2008|2456.12||-3.9|29.58
CA|Cankuzo|カンクゾ||-3.22|30.55|228873|2008|1964.54||-3.21|30.61
CI|Cibitoke|チビトケ||-2.89|29.12|460435|2008|1635.52||-2.83|29.17
GI|Gitega|ギテガ||-3.43|29.93|725223|2008|4546.3||-3.47|29.96
KI|Kirundo|キルンド||-2.58|30.1|628256|2008|1703.34||-2.55|30.09
KR|Karuzi|カルジ||-3.1|30.17|436443|2008|1457.4||-3.13|30.08
KY|Kayanza|カヤンザ||-2.92|29.62|585412|2008|1233.24||-2.92|29.62
MA|Makamba|マカンバ||-4.13|29.8|430899|2008|1959.6||-4.26|29.82
MU|Muramvya|ムランヴィヤ||-3.25|29.6|292589|2008|695.52||-3.25|29.63
MW|Mwaro|ムワロ||-3.53|29.7|273143|2008|839.6||-3.51|29.7
MY|Muyinga|ムインガ||-2.85|30.33|632409|2008|1836.26||-2.82|30.32
NG|Ngozi|ンゴジ||-2.9|29.82|660717|2008|1473.86||-2.91|29.83
RM|Rumonge|ルモンゲ||-3.97|29.43|352026|2008|1079.72||-3.97|29.43
RT|Rutana|ルタナ||-3.92|30.01|333510|2008|1959.45||-3.88|30.16
RY|Ruyigi|ルイギ||-3.47|30.25|400530|2008|2338.88||-3.53|30.29`,
};

export { BI };
