// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 12 subdivisions of Benin (BJ): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const BJ: SubdivisionFactsTable = {
  country: "BJ",
  rows: `AK|Natitingou|ナティティングー||10.3|1.37|||20499||10.3|1.37
AL|Kandi|カンディ||11.13|2.94|867463|2013|26242||11.13|2.94
AQ|Ouidah|ウィダー||6.37|2.08|||3233||6.67|2.25
BO|Parakou|パラクー||9.35|2.62|||25856||9.35|2.62
CO|Dassa-Zoumé|ダサ＝ズメ||7.75|2.18|||13931||7.93|1.97
DO|Djougou|ジューグー||9.7|1.67|||11126||9.7|1.67
KO||||||741895|2013|2404||6.96|1.8
LI|Cotonou|コトヌー||6.37|2.42|678874|2013|79||6.37|2.43
MO|Lokossa|ロコッサ||6.63|1.72|||1605||6.63|1.72
OU|Porto-Novo|ポルトノボ||6.48|2.62|1096850|2013|1281||6.5|2.6
PL|Pobè|ポベ||6.97|2.68|||3264||6.97|2.68
ZO|Abomey|アボメイ||7.19|1.99|||5243||7.18|1.98`,
};

export { BJ };
