// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 4 subdivisions of Brunei (BN): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const BN: SubdivisionFactsTable = {
  country: "BN",
  rows: `BE|Kuala Belait|クアラブライト||4.58|114.19|73200|2018|2727||4.42|114.58
BM|Bandar Seri Begawan|バンダルスリブガワン||4.92|114.92|307000|2018|570||4.9|114.9
TE|Bangar Town|バンガル||4.71|115.07|10900|2018|1304||4.58|115.17
TU|Tutong|プカン・ツトン||4.81|114.66|51300|2018|1166||4.58|114.67`,
};

export { BN };
