// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 9 subdivisions of Bolivia (BO): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const BO: SubdivisionFactsTable = {
  country: "BO",
  rows: `B|Trinidad|トリニダ||-14.83|-64.9|488260|2024|213564||-14|-65
C|Cochabamba|コチャバンバ||-17.39|-66.16|2016357|2024|55631||-17.33|-65.5
H|Sucre|スクレ||-19.05|-65.26|606027|2024|51524||-20|-64.42
L|La Paz|ラパス||-16.5|-68.13|3030917|2024|133985||-15|-68.35
N|Cobija|コビハ||-11.02|-68.75|134194|2024|63827||-11.18|-67.18
O|Oruro|オルロ||-17.97|-67.12|571471|2024|53588||-18.67|-67.67
P|Potosí|ポトシ||-19.59|-65.75|861292|2024|118218||-20.67|-66.67
S|Santa Cruz de la Sierra|サンタ・クルス・デ・ラ・シエラ||-17.79|-63.2|3122605|2024|370621||-17.33|-61.5
T|Tarija|タリハ||-21.53|-64.73|534210|2024|37623||-21.53|-64.73`,
};

export { BO };
