// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 20 subdivisions of Bhutan (BT): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const BT: SubdivisionFactsTable = {
  country: "BT",
  rows: `11|Paro|パロ||27.43|89.42|46316|2017|1693||27.5|89.33
12|Tsimasham|||26.96|89.54|68966|2017|1991||27|89.5
13|Ha|ハ||27.38|89.28|13655|2017|1319||27.25|89.17
14|Samtse|サムツェ||26.87|89.1|62590|2017|1725||27|89.08
15|Thimphu|ティンプー||27.47|89.63|138736|2017|1617||27.58|89.58
21|Damphu|ダンプー||27.02|90.1|22376|2017|632||26.92|90.08
22|Daga|ダガ||27.12|89.87|24965|2017|1387||27|89.92
23|Punakha|プナカ||27.62|89.87|28740|2017|845||27.62|89.87
24|Wangdue Phodrang|ワンデュ・ポダン||27.47|89.9|42186|2017|4181||27.5|90.17
31|Sarpang|||26.89|90.27|46004|2017|2048||26.88|90.27
32|Trongsa|トンサ||27.52|90.5|19960|2017|1815||27.52|90.5
33|Jakar|ジャカル||27.56|90.73|17820|2017|2490||27.75|90.67
34|Zhemgang|シェムガン||27.23|90.65|17763|2017|2146||27|90.75
41|Trashigang|タシガン||27.33|91.55|45518|2017|2171||27.25|91.67
42|Mongar|||27.27|91.24|37150|2017|||27.17|91.17
43|Pemagatsel|||27.03|91.45|23632|2017|593||27|91.25
44|Lhuntse|ルンツェ||27.65|91.15|14437|2017|2881||27.67|91
45|Samdrup Jongkhar|サムドゥプ・ジョンカル||26.8|91.5|35079|2017|2207||26.92|91.62
GA|Gasa Dzong|ガサ||27.9|89.73|3952|2017|3117.74||28|90
TY|Trashiyangtse|タシ・ヤンツェ||27.58|91.47|17300|2017|1459||27.67|91.42`,
};

export { BT };
