// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 6 subdivisions of Belize (BZ): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const BZ: SubdivisionFactsTable = {
  country: "BZ",
  rows: `BZ|Belize City|ベリーズシティ||17.5|-88.19|113630|2022|4204||17.25|-88.17
CY|San Ignacio|サン・イグナシオ||17.16|-89.07|99105|2022|5338||16.83|-88.92
CZL|Corozal|コロザル||18.4|-88.4|45310|2022|1860||18.25|-88.33
OW|Orange Walk Town|オレンジウォーク||18.07|-88.56|54152|2022|4737||17.83|-88.83
SC|Dangriga|ダンリガ||16.97|-88.22|46342|2022|2176||16.83|-88.5
TOL|Punta Gorda|プンタゴルタ||16.1|-88.8|38944|2022|4649||16.33|-88.75`,
};

export { BZ };
