// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 13 subdivisions of Canada (CA): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const CA: SubdivisionFactsTable = {
  country: "CA",
  rows: `AB|Edmonton|エドモントン||53.53|-113.5|4262635|2021|661848||54.5|-115
BC|Victoria|ビクトリア||48.42|-123.37|5000879|2021|944735||54.5|-124.5
MB|Winnipeg|ウィニペグ||49.9|-97.14|1342153|2021|647797||55|-97
NB||||||775610|2021|72908||46.6|-66
NL|St. John's|セイント・ジョンズ||47.56|-52.71|510550|2021|405212||53|-60
NS|Halifax|ハリファックス||44.65|-63.57|969383|2021|55283||45|-63
NT|Yellowknife|イエローナイフ||62.44|-114.4|41070|2021|1346106||67|-121
NU|Iqaluit|イカルイト||63.75|-68.52|36858|2021|2038722||67.35|-90.9
ON|Toronto|トロント||43.67|-79.39|14223942|2021|1076395||50|-85
PE|Charlottetown|シャーロットタウン||46.24|-63.13|154331|2021|5620||46.4|-63.2
QC|Quebec City|ケベック市||46.82|-71.22|8501833|2021|1542056||52|-72
SK|Regina|レジャイナ||50.45|-104.61|1132505|2021|651900||55|-106
YT|Whitehorse|ホワイトホース||60.72|-135.06|40232|2021|482443||60.72|-135.05`,
};

export { CA };
