// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 17 subdivisions of Central African Republic (CF): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const CF: SubdivisionFactsTable = {
  country: "CF",
  rows: `AC|Bossangoa|ボサンゴア||6.48|17.45|369220|2003|50250||7|18
BB|N'Délé|ンデレ||8.41|20.65|43229|2003|58200||8.42|20.67
BGF||||||889231|2020|||4.37|18.56
BK|Mobaye|モバイエ||4.32|21.18|249150|2003|17604||5|21.5
HK|Bria|ブリア||6.54|21.99|90316|2003|86650||7|23
HM|Obo|オボ||5.4|26.49|57602|2003|55530||6|26
HS|Berbérati|ベルベラティ||4.27|15.78|364795|2003|30203||4.5|16
KB|Kaga-Bandoro|ガガ＝バンドロ||7|19.18|117816|2003|19996||7.08|19.25
KG|Sibut|シブート||5.74|19.09|118420|2003|17204||5.75|19.08
LB|Mbaïki|ムバイキ||3.88|18|246875|2003|19235||4|18
MB|Bangassou|バンガスー||4.74|22.82|164009|2003|61150||5|23.5
MP|Bimbo|||4.33|18.52|356725|2003|31835||5|18
NM|Bouar|ブワル||5.95|15.6|233666|2003|26600||5.5|15.5
OP|Bozoum|ボズム||6.32|16.38|430506|2003|32100||7|16
SE|Nola|ノラ||3.52|16.05|101074|2003|19412||3.5|16.08
UK|Bambari|バンバリ||5.77|20.68|276710|2003|49900||6|21
VK|Birao|ビラオ||10.29|22.78|52255|2003|46500||10.33|22.75`,
};

export { CF };
