// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 12 subdivisions of Congo - Brazzaville (CG): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const CG: SubdivisionFactsTable = {
  country: "CG",
  rows: `11|Madingou|マディング||-4.16|13.55|363850|2023|12265||-4.15|13.55
12|Kinkala|キンカラ||-4.36|14.76|394532|2023|32510||-3.73|15.05
13|Ouésso|ウェッソ||1.61|16.05|209701|2023|55800||1.62|16.05
14|Djambala|ジャンバラ||-2.54|14.75|283421|2023|38400||-2.54|14.75
15|Ewo|エウォ||-0.87|14.82|119328|2023|26600||-0.87|14.82
16||||||||||-4.62|12
2|Sibiti|シビティ||-3.69|13.35|100559|2023|20950||-0.87|14.82
5|Loango, Republic of Congo|ロアンゴ||-4.66|11.81|97362|2023|12517||-4.23|11.93
7|Impfondo|アンフォンド||1.62|18.06|355570|2023|66044||1.63|18.07
8|Owando|オワンド||-0.48|15.9|316599|2023|48250||-0.48|15.9
9|Dolisie|ドリシー||-4.2|12.68|334863|2023|25942||-4.2|12.67
BZV`,
};

export { CG };
