// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 14 subdivisions of Côte d’Ivoire (CI): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const CI: SubdivisionFactsTable = {
  country: "CI",
  rows: `AB
BS|San-Pédro|サン＝ペドロ||4.73|-6.63|||25800||4.75|-6.64
CM|Abengourou|アバングールー||6.73|-3.5|||14173||6.73|-3.48
DN|Odienné|オディエンヌ||9.5|-7.57|||21600||9.5|-7.42
GD|Gagnoa|ガニョア||6.13|-5.93|1605286||17580||6.13|-5.93
LC|Dimbokro|ディンボクロ||6.65|-4.71|||28500||6.65|-4.7
LG|Dabou|||5.33|-4.38|||23280||5.93|-4.22
MG|Man|マン||7.41|-7.55|||31050||7.4|-7.55
SM|Daloa|ダロア||6.87|-6.45|||23940||6.88|-6.45
SV|Korhogo|コロゴ||9.46|-5.63|||40210||9.42|-5.62
VB|Bouaké|ブアケ||7.68|-5.03|||71.79||8.13|-5.1
WR|Séguéla|セグエラ||7.96|-6.67|||43853||8.48|-6.6
YM||||||340234|2021|2075||6.82|-5.27
ZZ|Bondoukou|ボンドゥク||8.04|-2.8|1344865|2021|38251||8.62|-3.15`,
};

export { CI };
