// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 16 subdivisions of Chile (CL): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const CL: SubdivisionFactsTable = {
  country: "CL",
  rows: `AI|Coyhaique|コイハイケ||-45.57|-72.07|100745|2024|108494.4||-45.57|-72.07
AN|Antofagasta|アントファガスタ||-23.65|-70.4|635416|2024|126049.1||-23.65|-70.4
AP|Arica|アリカ||-18.48|-70.32|244569|2024|16873.3||-18.48|-70.31
AR|Temuco|テムコ||-38.74|-72.59|1010423|2024|31842.3||-38.9|-72.67
AT|Copiapó|コピアポ||-27.37|-70.33|299180|2024|75176.2||-27.37|-70.33
BI|Concepción|コンセプシオン||-36.83|-73.05|1613059|2024|23890.2||-36.77|-73.06
CO|La Serena|ラ・セレナ||-29.9|-71.25|832864|2024|40579.9||-29.91|-71.25
LI|Rancagua|ランカグア||-34.17|-70.74|987228|2024|16387||-34.17|-70.74
LL|Puerto Montt|プエルトモント||-41.47|-72.94|890284|2024|48583.6||-41.47|-72.94
LR|Valdivia|バルディビア||-39.81|-73.25|398230|2024|18429.5||-39.81|-73.24
MA|Punta Arenas|プンタ・アレーナス||-53.16|-70.91|166537|2024|132291.1||-53.16|-70.92
ML|Talca|||-35.43|-71.6|1123008|2024|30296.1||-35.43|-71.67
NB|Chillán|チヤン||-36.61|-72.1|512289|2024|13178.5||-36.62|-71.95
RM|Santiago|サンティアゴ||-33.44|-70.65|7400741|2024|15403.2||-33.44|-70.65
TA|Iquique|イキケ||-20.21|-70.15|369806|2024|42225.8||-20.28|-69.33
VS|Valparaíso|バルパライソ||-33.05|-71.62|1896053|2024|16396.1||-33.05|-71.62`,
};

export { CL };
