// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 10 subdivisions of Cameroon (CM): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const CM: SubdivisionFactsTable = {
  country: "CM",
  rows: `AD|Ngaoundéré|ヌガウンデレ||7.32|13.58|838689|2007|63701||7.32|13.58
CE|Yaoundé|ヤウンデ||3.86|11.52|2797212|2007|68953||3.86|11.52
EN|Maroua|マルア||10.59|14.32|3142883|2007|34263||10.59|14.33
ES|Bertoua|ベルトゥア||4.58|13.68|875949|2007|109002||4.58|13.68
LT|Douala|ドゥアラ||4.05|9.7|2294540|2007|20248||4.05|9.7
NO|Garoua|ガルア||9.3|13.4|1409445|2007|66090||9.32|13.4
NW|Bamenda|バメンダ||5.96|10.15|2095538|2007|17300||5.96|10.15
OU|Bafoussam|バフーサム||5.47|10.42|2269136|2007|13892||5.48|10.42
SU|Ebolowa|エボロワ||2.92|11.15|633082|2007|47191||2.92|11.15
SW|Buea|ブエア||4.17|9.23|1419269|2007|25410||4.15|9.24`,
};

export { CM };
