// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 16 subdivisions of Cuba (CU): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const CU: SubdivisionFactsTable = {
  country: "CU",
  rows: `01|Pinar del Río|ピナール・デル・リオ||22.41|-83.67|575545|2022|8884.51||22.41|-83.67
03|Havana|ハバナ||23.14|-82.36|2137847|2022|7743.3||23.1|-82.4
04|Matanzas|マタンサス||23.05|-81.57|690113|2010|11798.02||23.05|-81.58
05|Santa Clara|サンタ・クララ||22.41|-79.95|803562|2010|8413.13||22.41|-79.95
06|Cienfuegos|シエンフエゴス||22.15|-80.44|405481|2010|4186.6||22.15|-80.44
07|Sancti Spíritus|サンクティ・スピリトゥス||21.93|-79.44|465468|2010|6779.81||21.93|-79.44
08|Ciego de Ávila|シエゴ・デ・アビラ||21.85|-78.76|422576|2010|6946.9||21.85|-78.76
09|Camagüey|カマグエイ||21.38|-77.92|756064|2022|15386||21.38|-77.91
10|Las Tunas|ラス・トゥーナス||20.97|-76.95|536027|2010|6595.25||20.96|-76.95
11|Holguin|オルギン||20.89|-76.26|1037161|2010|9209.71||20.88|-76.27
12|Bayamo|バヤモ||20.38|-76.64|835675|2010|8376.79||20.38|-76.65
13|Santiago de Cuba|サンティアゴ・デ・クーバ||20.02|-75.83|1047015|2010|6234.16||20.02|-75.81
14|Guantánamo|グアンタナモ||20.14|-75.21|510863|2010|6164.47||20.13|-75.2
15|Artemisa|アルテミサ||22.81|-82.76|512819|2022|4004.27||22.82|-82.77
16|San José de las Lajas|サン・ホセ・デ・ラス・ラハス||22.97|-82.16|380274|2011|3732.73||22.97|-82.15
99|Nueva Gerona|ヌエバ・ヘローナ||21.88|-82.8|86420|2010|2419||21.75|-82.85`,
};

export { CU };
