// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 19 subdivisions of Fiji (FJ): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const FJ: SubdivisionFactsTable = {
  country: "FJ",
  rows: `01|Ba|バ||-17.53|177.68|231760|2007|2634||-17.53|177.68
02||||||||||-16.78|178.6
03||||||||||-16.67|179.42
04|Ba|バ||-17.53|177.68|10167|2007|478||-19.05|178.25
05|Tubou|||-18.23|-178.8|10683|2007|487||-18.33|-178.5
06|Levuka|レブカ||-17.68|178.84|16461|2007|411||-17.67|178.8
07||||||||||-16.5|179.25
08|Sigatoka|シンガトカ||-18.15|177.5|58387|2007|2385||-18|177.67
09||||||||1666||-17.83|178.25
10||||||||||-18.05|178.13
11|Vaileka|||-17.37|178.15|||||-17.5|178.17
12||||||||||-18.08|178.33
13||||||18249|2007|830||-18.17|178
14||||||||||-17.83|178.5
C|Suva|スバ||-18.13|178.43|||||-18|178.33
E|Levuka|レブカ||-17.68|178.84|37311|2007|1376||-18.5|180
N|Labasa|ランバサ||-16.43|179.37|||||-16.5|179.5
R||||||||46||-12.5|177.08
W|Lautoka|ラウトカ||-17.62|177.45|||||-18|177.5`,
};

export { FJ };
