// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 4 subdivisions of Micronesia (FM): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const FM: SubdivisionFactsTable = {
  country: "FM",
  rows: `KSA|Tofol|トフォール||5.33|163.01|5092|2023|110||5.33|163
PNI|Kolonia|コロニア||6.96|158.21|36196|2010|371.6||6.85|158.22
TRK|Weno|ウェノ||7.44|151.87|33885|2023|116.2||7.42|151.78
YAP|Colonia|コロニア||9.52|138.13|10739|2023|119.54||9.52|138.12`,
};

export { FM };
