// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 16 subdivisions of Ghana (GH): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const GH: SubdivisionFactsTable = {
  country: "GH",
  rows: `AA|Accra|アクラ||5.56|-0.2|5455692|2021|3245||5.75|0
AF|Goaso|ゴアソ||6.8|-2.52|||||7|-2.45
AH|Kumasi|クマシ||6.7|-1.63|||24389||6.75|-1.5
BE|Techiman|テチマン||7.59|-1.94|||||7.75|-1.05
BO|Sunyani|スンヤニ||7.33|-2.33|||||7.33|-2.33
CP|Cape Coast|ケープ・コースト||5.1|-1.25|||9826||5.5|-1
EP|Koforidua|コフォリドゥア||6.09|-0.26|||19323||6.5|-0.5
NE|Nalerigu|ナレリグ||10.53|-0.37|||||10.52|-0.37
NP|Tamale|タマレ||9.41|-0.85|||70384||9.45|-0.1
OT|Dambai|ダンバイ||8.07|0.18|742700|2019|||7.9|0.3
SV|Damongo|ダモンゴ||9.08|-1.82|||||9.08|-1.82
TV|Ho|ホ||6.6|0.47|1878316|2009|20570||6.4|0.5
UE|Bolgatanga|ボルガタンガ||10.79|-0.85|1273700|2019|8842||10.75|-0.75
UW|Wa|ワ||10.07|-2.5|||18476||10.33|-2.25
WN|Wiawso|ウィアソー||6.21|-2.49|||||6.3|-2.8
WP|Sekondi-Takoradi|セコンディ・タコラディ||4.92|-1.77|||23921||5.45|-2.25`,
};

export { GH };
