// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 5 subdivisions of Greenland (GL): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const GL: SubdivisionFactsTable = {
  country: "GL",
  rows: `AV|Ilulissat|イルリサット||69.22|-51.1|10820|2021|522700||74.27|-51.53
KU|Qaqortoq|カコトック||60.72|-46.03|6292|2022|32000||61|-45
QE|Sisimiut|シシミュート||66.94|-53.67|9179|2025|115500||66.5|-48
QT|Aasiaat|アシアート||68.71|-52.87|6176|2021|62400||68.2|-51.93
SM|Nuuk|ヌーク||64.17|-51.73|24643|2026|531900||66|-40`,
};

export { GL };
