// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 6 subdivisions of Gambia (GM): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const GM: SubdivisionFactsTable = {
  country: "GM",
  rows: `B||||||31356|2013|12.2||13.45|-16.58
L||||||||1618||13.4|-15.7
M||||||||2894.3||13.57|-14.96
N||||||||2256||13.49|-15.93
U|Basse Santa Su|バセ・サンタ・ス||13.32|-14.22|198773|2010|2070||13.39|-14.18
W|Brikama|ブリカマ||13.27|-16.65|||1764||13.25|-16.32`,
};

export { GM };
