// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 18 subdivisions of Honduras (HN): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const HN: SubdivisionFactsTable = {
  country: "HN",
  rows: `AT|La Ceiba|ラ・セイバ||15.78|-86.79|436252|2013|4372||15.78|-86.79
CH|Choluteca|チョルテカ市||13.31|-87.2|437618|2013|4360||13.31|-87.2
CL|Trujillo|トルヒーリョ||15.92|-85.95|309926|2013|8249||15.92|-85.95
CM|Comayagua|コマヤグア||14.45|-87.64|493466|2013|5124||14.45|-87.64
CP|Santa Rosa de Copán|サンタ・ロサ・デ・コパン||14.77|-88.78|371057|2013|3242||14.77|-88.78
CR|San Pedro Sula|サン・ペドロ・スーラ||15.51|-88.03|1562394|2013|3923||15.51|-88.03
EP|Yuscarán|ユスカラン||13.94|-86.85|444507|2013|7489||13.94|-86.85
FM|Tegucigalpa|テグシガルパ||14.11|-87.2|1508906|2013|8619||14.11|-87.2
GD|Puerto Lempira|プエルト・レンピラ||15.27|-83.77|90765|2013|16997||15.27|-83.77
IB|Coxen Hole|コクスン・ホール||16.32|-86.54|62557|2013|236||16.32|-86.54
IN|La Esperanza|ラ・エスペランサ||14.31|-88.18|232553|2013|3123||14.31|-88.18
LE|Gracias|グラシアス||14.59|-88.58|321179|2013|4228||14.59|-88.58
LP|La Paz|ラパス||14.32|-87.68|198926|2013|2525||14.32|-87.68
OC|Ocotepeque|||14.44|-89.18|146030|2013|1630||14.44|-89.18
OL|Juticalpa|フティカルパ||14.67|-86.22|520761|2013|23905||14.67|-86.22
SB|Santa Bárbara|||14.92|-88.24|421337|2013|5024||14.92|-88.24
VA|Nacaome|ナカオメ||13.53|-87.49|174511|2013|1665||13.53|-87.49
YO|Yoro|ヨロ||15.14|-87.12|570595|2013|7781||15.14|-87.12`,
};

export { HN };
