// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 6 subdivisions of Israel (IL): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const IL: SubdivisionFactsTable = {
  country: "IL",
  rows: `D|Beersheba|ベエルシェバ||31.25|34.79|1272100|2017|14185||30.67|34.83
HA|Haifa|ハイファ||32.82|35|966700|2014|864||32.58|35
JM|Jerusalem|エルサレム||31.78|35.23|1034200|2014|652||31.75|35.04
M|Ramla|ラムラ||31.93|34.86|2115800|2017|1293||31.93|34.87
TA|Tel Aviv|テルアビブ||32.08|34.78|1350000|2014|186||32.08|34.8
Z|Nof HaGalil|ナザレ・イリト||32.71|35.32|1448100|2018|4473||32.83|35.33`,
};

export { IL };
