// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 19 subdivisions of Iraq (IQ): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const IQ: SubdivisionFactsTable = {
  country: "IQ",
  rows: `AN|Ramadi|ラマーディー||33.43|43.3|1561400|2011|135000||32.9|41.6
AR|Erbil|アルビール||36.19|44.01|1532081|2009|12000||36.18|44.03
BA|Basra|バスラ||30.52|47.81|2405434|2009|19070||30.37|47.37
BB|Hillah|ヒッラ||32.48|44.43|2000000|2014|5800||32.62|44.55
BG|Baghdad|バグダード||33.32|44.37|9780429|2024|204.2||33.33|44.43
DA|Duhok|ドホーク||36.85|42.98|1072324|2009|10000||37.05|43.15
DI|Bagdad|バアクーバ||33.74|44.64|1371035|2009|14700||33.88|45.07
DQ|Nasiriyah|ナーシリーヤ||31.04|46.26|2000000|2012|12900||31.23|46.32
KA|Karbala|カルバラー||32.62|44.03|1013254|2009|5030||32.45|43.8
KI|Kirkuk|キルクーク||35.47|44.4|1325853|2009|10500||35.37|44.13
KR
MA|Amarah|アマーラ||31.83|47.15|922890|2009|16070||31.9|47.03
MU|Samawah|サマーワ||31.32|45.28|683126|2009|51740||30.2|45.35
NA|Najaf|ナジャフ||32.03|44.34|1285500|2011|28820||31.12|43.8
NI|Mosul|モースル||36.34|43.13|3106948|2009|36700||36|42.47
QA|Al Diwaniyah|ディーワーニーヤ||31.99|44.92|1077614|2009|8150||31.85|45.05
SD|Tikrit|ティクリート||34.6|43.68|1337786|2009|26000||34.45|43.58
SU|Sulaymaniyah|スレイマニヤ||35.55|45.43|1694895|2009|20000||35.52|45.32
WA|Kut|クート||32.51|45.82|1149059|2015|17150||32.5|45.82`,
};

export { IQ };
