// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 14 subdivisions of Jamaica (JM): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const JM: SubdivisionFactsTable = {
  country: "JM",
  rows: `01|Kingston|キングストン||17.97|-76.79|89186|2022|25||17.97|-76.8
02|Half Way Tree|ハーフ・ウェイ・ツリー||18.01|-76.8|583718|2022|455||18.02|-76.9
03|Morant Bay|モラント湾||17.88|-76.41|94485|2022|742.8||17.9|-76.43
04|Port Antonio|ポート・アントニオ||18.18|-76.45|84972|2022|814||18.13|-76.53
05|Port Maria La luz|マリア港||18.37|-76.89|116498|2022|610||18.32|-76.9
06|Saint Ann's Bay|聖アン湾||18.43|-77.2|175310|2022|1212.6||18.2|-77.47
07|Falmouth|ファルマウス||18.49|-77.66|77427|2022|874||18.38|-77.63
08|Montego Bay|モンテゴ・ベイ||18.47|-77.92|188656|2022|595||18.38|-77.88
09|Lucea|ルセア||18.45|-78.17|69780|2022|430||18.42|-78.13
10|Savanna-la-Mar|サバナラマル||18.22|-78.13|146205|2022|807||18.23|-78.15
11|Black River|ブラック・リバー||18.03|-77.85|153201|2022|1212.4||18.05|-77.78
12|Mandeville|マンデヴィル||18.03|-77.5|193694|2022|830||18.05|-77.53
13|May Pen|メイ・ペン||17.95|-77.25|258643|2022|1196||17.73|-77.15
14|Spanish Town|スパニッシュ・タウン||18|-76.95|542763|2022|1192||18|-77`,
};

export { JM };
