// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 12 subdivisions of Jordan (JO): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const JO: SubdivisionFactsTable = {
  country: "JO",
  rows: `AJ|Ajloun|アジュルン||32.33|35.75|181000|2016|419.6||32.34|35.75
AM|Amman|アンマン||31.93|35.93|4007526|2015|7579.2||31.95|35.93
AQ|Aqaba|アカバ||29.53|35.01|||6900||29.52|35.01
AT|Tafilah|タフィラ||30.84|35.6|10000||2114||30.84|35.61
AZ|Zarqa|ザルカ||32.08|36.1|||4761.3||31.83|36.83
BA|Salt|サルト||32.04|35.73|491709|2015|1120.4||32.06|35.77
IR|Irbid|イルビド||32.56|35.85|||1571.8||32.55|35.86
JA|Jerash|ジェラシュ||32.27|35.89|237059|2015|409.8||32.28|35.91
KA|Al-Karak|カラク||31.18|35.7|316629|2015|3217||31.16|35.76
MA|Mafraq|マフラク||32.34|36.2|549948|2015|26550.6||32.27|36.16
MD|Madaba|マダバ||31.72|35.8|189192|2015|939.7||31.61|35.69
MN|Ma'an|マアーン||30.19|35.73|175200|2019|33832.3||30.2|35.73`,
};

export { JO };
