// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 9 subdivisions of Kyrgyzstan (KG): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const KG: SubdivisionFactsTable = {
  country: "KG",
  rows: `B|Batken|バトケン||40.06|70.82|594700|2025|16995||39.83|71.5
C|Bishkek|ビシュケク||42.87|74.57|1102100||20200||42.5|74.5
GB||||||1191000|2025|127||42.87|74.57
GO||||||375400|2025|182.5||40.53|72.78
J|Manas|ジャララバード||40.94|72.99|1358500|2025|33700||41.25|72.25
N|Naryn|ナルン||41.43|76|314900|2025|45200||41.5|75.5
O|Osh|オシ||40.53|72.78|1514900|2025|29200||40|73
T|Talas|タラス||42.52|72.23|280500|2025|11400||42.5|72.5
Y|Karakol|カラコル||42.49|78.39|549800|2025|43100||42|78`,
};

export { KG };
