// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 3 subdivisions of Kiribati (KI): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const KI: SubdivisionFactsTable = {
  country: "KI",
  rows: `G|South Tarawa|サウス・タラワ||1.33|172.97|108145|2020|279.23||0|174
L|Banana|バナナ||1.97|-157.39|11252|2020|||-2|-156.5
P|Kanton Island|カントン島||-2.81|-171.68|41|2020|27.92||-3.67|-172.33`,
};

export { KI };
