// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 16 subdivisions of St. Kitts & Nevis (KN): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const KN: SubdivisionFactsTable = {
  country: "KN",
  rows: `01|Nichola Town|ニコラタウン||17.38|-62.75|1922|2011|17.97||17.37|-62.76
02|Sandy Point Town|サンディ・ポイント||17.35|-62.83|2626|2011|12.74||17.38|-62.84
03|Basseterre|バセテール||17.3|-62.73|12635|2011|28.6||17.29|-62.69
04|Market Shop|マーケット・ショップ||17.13|-62.57|2496|2011|18.7||17.13|-62.55
05|Newcastle|ニューカッスル||17.2|-62.58|2038|2011|31.5||17.18|-62.57
06|Dieppe Bay Town|ディエップベイタウン||17.42|-62.82|2962|2011|24.25||17.39|-62.8
07|Figtree|フィグツリー||17.12|-62.6|3827|2011|21.7||17.13|-62.6
08|Cayon|ケイオン||17.35|-62.73|3435|2011|14.72||17.36|-62.76
09|Saint Paul Capisterre|セントポール・カピステール||17.4|-62.82|2432|2011|12.66||17.39|-62.84
10|Charlestown|チャールズタウン||17.14|-62.63|1847|2011|3.6||17.14|-62.61
11|Monkey Hill|モンキーヒル||17.32|-62.73|4670|2011|19.74||17.34|-62.73
12|Cotton Ground|コットン・グラウンド||17.17|-62.62|2069|2011|18.2||17.17|-62.61
13|Middle Island|ミドルアイランド||17.32|-62.8|2657|2022|23.55||17.36|-62.81
15|Trinity|||17.3|-62.77|1701|2011|14.7||17.33|-62.77
K|Basseterre|バセテール||17.3|-62.73|34918|2011|168||17.32|-62.75
N|Charlestown|チャールズタウン||17.14|-62.63|12277|2011|93||17.15|-62.58`,
};

export { KN };
