// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 13 subdivisions of North Korea (KP): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const KP: SubdivisionFactsTable = {
  country: "KP",
  rows: `01||||||2863000|2015|3194||39.02|125.75
02|Pyongsong|平城市||39.25|125.85|4051696|2008|12330||39.25|125.85
03|Sinuiju|新義州市||40.1|124.4|2728662|2008|12191||40.1|124.4
04|Kanggye|江界市||40.97|126.6|1299830|2008|16613||40.97|126.59
05|Haeju|海州市||38.03|125.72|2310485|2008|8450||38.03|125.72
06|Sariwon|沙里院市||38.5|125.76|2113672|2008|8154||38.51|125.76
07|Wonsan|元山市||39.15|127.45|1477582|2008|11255||39.15|127.45
08|Hamhung|咸興市||39.92|127.53|3066013|2008|18970||40.24|127.53
09|Chongjin|清津市||41.78|129.78|2327362|2008|20345||41.9|129.41
10|Hyesan|恵山市||41.4|128.18|719269|2008|14317||41.4|128.18
13||||||196954|2008|746||42.34|130.38
14||||||366815|2008|1180||38.73|125.4
15||||||308440|2008|||37.97|126.55`,
};

export { KP };
