// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 17 subdivisions of South Korea (KR): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const KR: SubdivisionFactsTable = {
  country: "KR",
  rows: `11|Jung District|中区||37.56|126.97|9668465|2020|605.25||37.56|126.99
26|Yeonje District|蓮堤区||35.18|129.08|3453198|2018|769.83||35.18|129.07
27||||||2376044|2023|1499.53||35.87|128.6
28||||||3049315|2025|1046.81||37.46|126.65
29||||||1409624|2024|501.18||35.17|126.92
30||||||1475221|2018|539.96||36.35|127.39
31||||||1127553|2024|1060.19||35.55|129.32
41|Suwon|水原市||37.29|127.01|13103188|2018|10172.07||37.5|127.25
42|Chuncheon|春川市||37.87|127.73|1539274|2024|16873.51||37.5|128.25
43|Cheongju|清州市||36.64|127.49|1595058|2022|7407.22||36.63|127.49
44|Hongseong County|洪城郡||36.6|126.66|2181416|2018|8204||36.66|126.67
45|Jeonju|全州市||35.82|127.15|1769607|2022|8067||35.82|127.11
46|Muan County|務安郡||34.96|126.44|1790352|2018|12309.03||34.82|126.46
47|Andong|安東市||36.57|128.72|2546960|2024|19029||36.58|128.51
48|Changwon|昌原市||35.23|128.68|3350350|2018|10538||35.24|128.69
49|Jeju|済州市||33.51|126.52|670837|2024|1848||33.37|126.53
50||||||391984|2025|465||36.49|127.28`,
};

export { KR };
