// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 6 subdivisions of Kuwait (KW): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const KW: SubdivisionFactsTable = {
  country: "KW",
  rows: `AH|Al Ahmadi|アハマディ||29.09|48.07|682582|2010|5120||29.08|48.08
FA|Farwaniya|ファルワーニーヤ||29.28|47.96|||190||29.28|47.96
HA|Hawally|ハワッリー||29.33|48.03|||82||29.33|48.03
JA|Al Jahra|ジャハラー||29.35|47.68|||11230||29.34|47.66
KU||||||||200||29.37|47.98
MU|Mubarak Al-Kabeer|||29.19|48.08|||100||29.26|48.06`,
};

export { KW };
