// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 18 subdivisions of Laos (LA): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const LA: SubdivisionFactsTable = {
  country: "LA",
  rows: `AT|Attapư̄|アッタプー||14.8|106.83|139628|2015|10320||14.8|106.83
BK|Ban Houayxay|フアイサーイ郡||20.28|100.41|179243|2015|6196||20.3|100.42
BL|Pakxan|パークサン郡||18.38|103.67|315956|2020|14863||18.38|103.65
CH|Pāksē|パークセー郡||15.12|105.78|694023|2015|15415||14.88|105.84
HO|Xam Neua|サムヌア||20.41|104.05|310976|2020|16500||20.33|103.83
KH|Thakhèk|ターケーク郡||17.4|104.8|433570|2020|16315||17.5|105.33
LM|Lūang Namthā|ルアンナムター郡||20.95|101.4|199090|2020|9325||20.96|101.39
LP|Luang Prabang|ルアンパバーン郡||19.89|102.13|467157|2020|16875||20.21|102.62
OU|Mư̄ang Sai|サイ郡||20.69|101.98|345425|2020|15370||20.7|101.82
PH|Phongsālī|ポンサーリー郡||21.68|102.1|177989|2015|16925||21.68|102.1
SL|Sālavan|サーラワン||15.72|106.42|396942|2015|10691||15.87|106.35
SV|Savannakhet|カイソーン・ポムウィハーン郡||16.55|104.75|969697|2015|21774||16.54|105.78
VI|Phōnhōng|ポンホーン郡||18.41|102.39|388833|2005|15927||18.64|102.32
VT|Vientiane|ヴィエンチャン||17.98|102.63|||3920||18.14|102.51
XA|Sainyabūlī|||19.25|101.75|423496|2020|16389||19.25|101.75
XE|Sekong|セコン||15.4|106.7|113048|2015|7665||15.5|107
XI|Phōnsavan|ポーンサワン郡||19.45|103.2|267172|2020|16358||19.42|103.5
XS||||||85168|2015|8300||18.91|103.09`,
};

export { LA };
