// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 10 subdivisions of Lesotho (LS): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const LS: SubdivisionFactsTable = {
  country: "LS",
  rows: `A|Maseru|マセル||-29.31|27.48|519186|2016|4279||-29.5|28
B|Butha-Buthe|ブータ・ブーテ||-28.77|28.25|118242|2016|1767||-28.83|28.5
C|Hlotse|フロツェ||-28.87|28.04|337521|2016|2828||-29|28
D|Teyateyaneng|テヤテヤネング||-29.15|27.73|262616|2016|2222||-29.17|27.92
E|Mafeteng|マフェテング||-29.82|27.25|178222|2016|2119||-29.83|27.92
F|Mohale's Hoek|モハレス・フーク||-30.15|27.47|165590|2016|3530||-30.17|27.67
G|Quthing|クティング||-30.4|27.7|115469|2016|2916||-30.42|28
H|Qacha's Nek|クァクハスネック||-30.12|28.69|74566|2016|2349||-30|28.75
J|Mokhotlong|モコトロング||-29.29|29.07|100442|2016|4075||-29.33|29
K|Thaba-Tseka|ターバ・ツェーカ||-29.52|28.61|135347|2016|4270||-29.5|28.67`,
};

export { LS };
