// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 17 subdivisions of Monaco (MC): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const MC: SubdivisionFactsTable = {
  country: "MC",
  rows: `CL|Monaco|モナコ||43.73|7.42|||0.19||43.73|7.41
CO||||||3694|2008|0.3||43.73|7.42
FO||||||||0.33||43.73|7.42
GA
JE||||||||0.23||43.73|7.41
LA||||||||0.22||43.75|7.43
MA
MC||||||||0.28||43.74|7.43
MG||||||3131|2008|0.12||43.74|7.42
MO||||||975|2008|0.2||43.73|7.42
MU||||||||||43.74|7.43
PH||||||||||43.74|7.43
SD||||||||0.02||43.74|7.42
SO
SP||||||||||43.74|7.42
SR
VR`,
};

export { MC };
