// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 11 subdivisions of Mali (ML): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const ML: SubdivisionFactsTable = {
  country: "ML",
  rows: `1|Kayes|カイ||14.45|-11.44|||119743||14.12|-10.57
10|Taoudenni|タウデニ||22.63|-3.95|18160|2009|323326||22.7|-4
2|Koulikoro|クリコロ||12.87|-7.57|||90120||13.94|-7.62
3|Sikasso|シカソ||11.32|-5.67|2625919|2009|70280||11.2|-7.1
4|Ségou|セグー||13.43|-6.22|2336255|2009|64821||13.37|-5.27
5|Mopti|モプティ||14.49|-4.19|2037330|2009|79017||14.5|-3.19
6|Timbuktu|トンブクトゥ||16.77|-3|681691|2009|56.44||16.3|-3
7|Gao|ガオ||16.27|-0.05|544120|2009|170572||17.1|0.35
8|Kidal|キダル||18.43|1.4|83192|2022|151450||19.97|0.75
9|Ménaka|メナカ||15.92|2.4|||81040||16.7|2.7
BKO||||||4227569|2023|245||12.65|-7.99`,
};

export { ML };
