// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 15 subdivisions of Myanmar (Burma) (MM): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const MM: SubdivisionFactsTable = {
  country: "MM",
  rows: `01|Sagaing|サガイン||21.88|95.98|6015590|2024|93702.48||21.5|95.62
02|Bago|バゴー||17.34|96.5|4453691|2024|39404.43||17.33|96.49
03|Magway|マグウェ||20.15|94.95|4078504|2024|44820.58||20.25|94.75
04|Mandalay|マンダレー||21.97|96.08|6283663|2024|30888.09||21|95.75
05|Dawei|ダウェイ||14.04|98.19|1380567|2024|43344.91||13|98.75
06|Yangon|ヤンゴン||16.8|96.16|7370010|2024|10276.71||17|96.17
07|Pathein|パテイン||16.77|94.73|5546281|2024|35031.88||16.83|95.17
11|Myitkyina|ミッチーナー||25.39|97.39|2197283|2024|89041||26|97.5
12|Loikaw|ロイコー||19.67|97.21|296903|2024|11731.5||19.25|97.33
13|Hpa-An|パアン||16.89|97.63|1490968|2024|30382.8||17|97.75
14|Hakha|||22.64|93.61|373024|2024|36019||22|93.5
15|Mawlamyine|モーラミャイン||16.48|97.63|1717166|2024|12296.6||16.17|97.67
16|Sittwe|シットウェ||20.14|92.9|2466385|2024|36778||19.5|94
17|Taunggyi|タウンジー||20.78|97.04|6517377|2024|155801||21.5|98
18||||||1129344|2024|7054.37||19.75|96.1`,
};

export { MM };
