// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 15 subdivisions of Mauritania (MR): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const MR: SubdivisionFactsTable = {
  country: "MR",
  rows: `01|Néma|ネマ||16.61|-7.26|625643|2023|182267||16.61|-7.26
02|Ayoun el Atrous|アヨウン・エル・アトロウス||16.66|-9.6|403091|2023|50248||16.66|-9.62
03|Kiffa|キファ||16.62|-11.4|451804|2023|35984||16.62|-11.4
04|Kaédi|カエディ||16.15|-13.5|442490|2023|13600||16.05|-12.82
05|Aleg|アレグ||17.05|-13.92|391310|2023|33329||17.06|-13.91
06|Rosso|ロッソ||16.51|-15.8|323903|2023|65764||16.51|-15.8
07|Atar|アタール||20.52|-13.05|71623|2023|222107||20.52|-13.05
08|Nouadhibou|ヌアディブ||20.91|-17.05|184459|2023|37793||20.91|-17.05
09|Tidjikja|ティジクジャ||18.55|-11.43|||98186||18.55|-11.43
10|Sélibaby|セリバビ||15.16|-12.18|363075|2023|10300||15.38|-12.35
11|Zouérat|ズエラット||22.73|-12.47|79129|2023|252900||24|-9
12|Akjoujt|アクジュジト||19.74|-14.38|29484|2023|31582||19.74|-14.38
13|Tevragh Zeina|テヴラ＝ゼイナ||18.09|-15.98|204881|2023|146||18.09|-15.97
14|Dar Naim|ダル＝ナイム||18.1|-15.92|614465|2023|306||18.09|-15.92
15|Arafat|||18.05|-15.97|627415|2023|341.8||18.06|-15.95`,
};

export { MR };
