// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 12 subdivisions of Mauritius (MU): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const MU: SubdivisionFactsTable = {
  country: "MU",
  rows: `AG||||||||24||-10.41|56.63
BL||||||76627||259||-20.33|57.42
CC||||||||1.3||-16.58|59.62
FL||||||140294||297.9||-20.23|57.72
GP||||||115546||260.3||-20.4|57.64
MO||||||81288||230.5||-20.25|57.57
PA|Triolet|トリオレット||-20.05|57.55|||178.7||-20.12|57.58
PL|Port Louis|ポートルイス||-20.16|57.5|||44||-20.17|57.52
PW|Beau Bassin-Rose Hill|ボー・バッサン＝ローズ・ヒル||-20.23|57.47|385034||203.3||-20.3|57.48
RO|Port Mathurin|ポート・マチュリン||-19.68|63.42|41669||109||-19.72|63.42
RR||||||||147.6||-20.05|57.63
SA|Souillac|||-20.52|57.52|70471|2010|244.8||-20.47|57.5`,
};

export { MU };
