// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 31 subdivisions of Malawi (MW): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const MW: SubdivisionFactsTable = {
  country: "MW",
  rows: `BA|Balaka Township|バラカ||-14.98|34.96|||2193||-15|35
BL|Blantyre|ブランタイヤ||-15.79|35.01|||1785||-15.5|35
C|Lilongwe|リロングウェ||-13.99|33.77|||35592||-13.62|33.53
CK|Chikwawa|チクワワ||-16.04|34.8|||||-16.17|34.75
CR|Chiradzulu|チラズル||-15.67|35.14|||767||-15.7|35.17
CT|Chitipa|チティパ||-9.7|33.27|||4288||-9.7|33.27
DE|Dedza|デッザ||-14.38|34.33|||3624||-14.17|34.33
DO|Dowa|ドーワ||-13.66|33.93|||3041||-13.58|34
KR|Karonga|カロンガ||-9.93|33.93|269890|2008|3355||-10|33.75
KS|Kasungu|カスング||-13.03|33.48|||7878||-13|33.42
LI|Lilongwe|リロングウェ||-13.99|33.77|||5757||-14|33.58
LK|Likoma|リコマ||-12.07|34.72|||18||-12.08|34.67
MC|Mchinji|ムチンジ||-13.8|32.88|||3356||-13.75|33.08
MG|Mangochi|マンゴチ||-14.47|35.26|||6273||-14.48|35.25
MH|Machinga|マチンガ||-15.18|35.3|||3771||-14.92|35.67
MU|Mulanje|ムランジェ||-16.03|35.5|||2056||-16|35.58
MW|Mwanza|ムワンザ||-15.61|34.52|||2259||-15.58|34.58
MZ|Mzimba|ムジンバ||-11.9|33.59|||10430||-11.5|33.5
N|Mzuzu|ムズズ||-11.45|34.03|1698502|2008|26931||-11.2|33.8
NB|Nkhata Bay|カタベイ||-11.6|34.3|||4071||-11.5|34
NE|Neno|ネノ||-15.4|34.65|||1554||-15.45|34.7
NI|Ntchisi|ンチシ||-13.35|33.92|||1655||-13.33|34
NK|Nkhotakota|コタコタ||-12.92|34.3|||4259||-13|34.08
NS|Nsanje|ンサンジェ||-16.92|35.27|||1942||-16.75|35.17
NU|Ntcheu|ンチェウ||-14.82|34.63|||3424||-14.75|34.75
PH|Phalombe|パロンベ||-15.8|35.65|429450|2018|1394||-15.67|35.67
RU|Rumphi|ルンピ||-11.02|33.85|||4071||-10.75|33.83
S|Blantyre|ブランタイヤ||-15.79|35.01|||31753||-15.67|34.97
SA|Salima|サリマ||-13.78|34.45|||2196||-13.75|34.5
TH|Thyolo|チョロ||-16.07|35.13|||1715||-16.17|35.17
ZO|Zomba|ゾンバ||-15.39|35.32|||2580||-15.17|35.5`,
};

export { MW };
