// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 11 subdivisions of Mozambique (MZ): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const MZ: SubdivisionFactsTable = {
  country: "MZ",
  rows: `A|Lichinga|リシンガ||-13.3|35.25|1865976|2017|122827||-13.25|36.5
B|Chimoio|シモイオ||-19.12|33.45|1911237|2017|62272||-19.5|33.25
G|Xai-Xai|シャイシャイ||-25.05|33.65|1446654|2017|75334||-23.75|32.75
I|Inhambane|イニャンバネ市||-23.86|35.38|1496824|2017|68775||-23|34.5
L|Matola|マトラ||-25.97|32.47|2507098|2017|22693||-25.5|32.33
MPM||||||1133200|2023|346.77||-25.97|32.57
N|Nampula|ナンプラ||-15.12|39.27|6102867|2017|79010||-15.25|39.5
P|Pemba|ペンバ||-12.97|40.52|2333278|2017|78778||-12.75|39.5
Q|Quelimane|ケリマネ||-17.88|36.89|5110787|2017|103478||-17|37
S|Beira|ベイラ||-19.83|34.85|2221803|2017|68018||-19|34.75
T|Tete|||-16.16|33.59|2551826|2017|98417||-15.5|32.5`,
};

export { MZ };
