// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 17 subdivisions of Norway (NO): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const NO: SubdivisionFactsTable = {
  country: "NO",
  rows: `03||||||717710|2024|480.75|2020|59.91|10.74
11|Stavanger|||58.97|5.73|499417|2024|||58.97|5.71
15|Molde|||62.74|7.16|265392|2019|||62.74|7.16
18|Bodø|ボードー||67.28|14.38|243385|2019|||66.83|14.67
21|Longyearbyen|ロングイェールビーン||78.22|15.63|2668||61022||78.16|15.86
22||||||18|2010|377||70.98|-8.53
31|Sarpsborg|サルプスボルグ||59.29|11.2|297520|2019|5077.26|2018|59.33|11.33
32|Oslo|オスロ||59.91|10.74|749207|2026|5891.73||60|11
33|Drammen|||59.74|10.2|272981|2026|15053.83|2018|60.5|9.5
34|Hamar|ハーマル||60.79|11.07|371054|2019|||61.5|10.67
39|Tønsberg|||59.27|10.41|251078|2019|4118.98|2018|59.31|10.22
40|Skien|||59.21|9.61|173318|2019|16157.79|2018|59.33|8.5
42||||||323930|2026|||58.15|8
46|Bergen|ベルゲン||60.39|5.32|633117|2019|||60.92|6.45
50||||||464060|2019|||63.43|10.39
55|Tromsø|トロムソ||69.65|18.96|167207|2019|41132.81|2018|69.16|19.4
56|Vadsø|||70.07|29.75|75288|2026|74293.69|2018|70.12|27.59`,
};

export { NO };
