// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 14 subdivisions of Nauru (NR): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const NR: SubdivisionFactsTable = {
  country: "NR",
  rows: `01||||||1300|2004|1.1||-0.53|166.91
02|Anabar|||-0.51|166.95|||1.5||-0.52|166.95
03||||||||1||-0.51|166.94
04||||||||3.1||-0.53|166.95
05||||||834|2004|1.2||-0.51|166.93
06||||||970|2004|0.5||-0.54|166.91
07||||||1000|2004|2.6||-0.53|166.92
08|Arijejen|||-0.53|166.91|2396|2005|0.9||-0.52|166.91
09||||||||1.2||-0.5|166.94
10||||||||1.1||-0.52|166.96
11||||||1400|2004|3.1||-0.55|166.94
12||||||460|2004|1.6||-0.52|166.92
13||||||333|2004|0.8||-0.52|166.92
14||||||747|2011|1.5||-0.55|166.92`,
};

export { NR };
