// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 11 subdivisions of Oman (OM): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const OM: SubdivisionFactsTable = {
  country: "OM",
  rows: `BJ|Rustaq|ルスタク||23.39|57.42|465550|2020|5320||23.39|57.42
BS|Sohar|ソハール||24.34|56.73|784681|2020|7900||24.34|56.73
BU||||||121802|2020|7460||24.25|55.78
DA|Nizwa|ニズワ||22.93|57.53|478501|2020|31900||22|57
MA|Muscat|マスカット||23.61|58.59|1302440|2020|3500||23.61|58.54
MU|Khasab|ハサブ||26.18|56.25|49062|2020|1800||26|56.3
SJ|Sur|スール||22.57|59.53|315445|2020|12000||22.57|59.53
SS|Ibra|イブラー||22.68|58.55|271822|2020|21100||22.68|58.55
WU|Haima|ハイマー||19.96|56.28|52344|2020|79700||20|56
ZA|Ibri|イブリー||23.24|56.5|213043|2020|37000||23.24|56.5
ZU|Salalah|サラーラ||17.02|54.09|416458|2020|99300||18|54`,
};

export { OM };
