// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 14 subdivisions of Panama (PA): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const PA: SubdivisionFactsTable = {
  country: "PA",
  rows: `1|Bocas del Toro|ボカスデルトロ||9.33|-82.25|159228|2023|4657.2||9.34|-82.24
10|La Chorrera|ラ・チョレラ||8.88|-79.78|653665|2023|2880||8.88|-79.78
2|Penonomé|ペノノメ||8.52|-80.36|268264|2023|4927||8.5|-80.5
3|Colón City|コロン||9.36|-79.9|281956|2023|4891||9.17|-80.17
4|David|ダビッド||8.44|-82.42|471071|2023|6490.9||8.43|-82.43
5|La Palma|||8.41|-78.15|54235|2023|11892.5||8.41|-77.92
6|Chitré|チトレ||7.97|-80.43|122071|2023|2362||7.83|-80.67
7|Las Tablas|ラス・タブラス||7.77|-80.28|98466|2023|3809.4||7.6|-80.45
8|Panama City|パナマ市||8.97|-79.53|1439575|2023|75517||9|-79.17
9|Santiago de Veraguas|サンティアゴ・デ・ベラグアス||8.11|-80.97|259791|2023|10587.5||8|-81
EM|Unión Chocó|ウニオン・チョコ||8.08|-77.56|12358|2023|4365.5||8.53|-77.54
KY|El Porvenir|||9.56|-78.95|33109|2010|2358.2||9.3|-78.34
NB||||||156747|2010|6814.2||8.77|-81.73
NT|Sieyic|シーイク||9.38|-82.65|||||9.24|-82.74`,
};

export { PA };
