// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 22 subdivisions of Papua New Guinea (PG): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const PG: SubdivisionFactsTable = {
  country: "PG",
  rows: `CPK|Kundiawa|クンディアワ||-6.02|144.8|376473||6134||-6.33|144.92
CPM|Port Moresby|ポートモレスビー||-9.48|147.15|||29998||-10|148
EBR|Kokopo|ココポ||-4.35|152.27|||15724||-5.17|151.75
EHG|Goroka|ゴロカ||-6.08|145.38|579825|2011|11157||-6.5|145.67
EPW|Wabag|ワバック||-5.48|143.7|571060|2021|11704||-5.5|143.5
ESW||||||450530||43671||-4.33|143.25
GPK|Kerema|ケレマ||-7.96|145.77|158197||34472||-7.33|145
HLA|Tari|||||||10498||-6|142.83
JWK||||||||4798||-6|144.58
MBA|Alotau|アロタウ||-10.32|150.43|||14345||-10.25|150
MPL|Lae|ラエ||-6.73|147|||33705||-6.83|146.67
MPM|Madang|マダン||-5.22|145.8|||28886||-5.17|145.33
MRL|Lorengau|ローレンガウ||-2.02|147.27|||2000||-2.08|147
NCD||||||317374|2012|240||-9.48|147.15
NIK|Kavieng|カビエン||-2.57|150.8|||||-3|151.5
NPP|Popondetta|ポポンデッタ||-8.77|148.23|||22735||-9|148.08
NSB||||||367093|2024|9384||-6|155
SAN|Vanimo|ヴァニモ||-2.68|141.3|||35820||-3.67|141.5
SHM|Mendi|メンディ||-6.15|143.66|510245|2011|15098||-6.17|143.33
WBK|Kimbe|キンベ||-5.56|150.16|||20387||-5.83|150
WHM|Mount Hagen|マウントハーゲン||-5.87|144.22|||4299||-5.67|144.5
WPD|Daru|ダル||-9.08|143.2|||98189||-7.33|142`,
};

export { PG };
