// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 7 subdivisions of Pakistan (PK): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const PK: SubdivisionFactsTable = {
  country: "PK",
  rows: `BA|Quetta|クエッタ||30.2|67.02|13162222|2014|347190||30.12|67.01
GB|Gilgit|ギルギット||35.92|74.31|1155755|2011|72971||35.35|75.9
IS|Islamabad|イスラマバード||33.7|73.04|||1165.5||33.74|73.15
JK|Muzaffarabad|ムザファラバード||34.37|73.47|4567982|2008|13297||33.94|73.76
KP|Peshawar|ペシャーワル||34.01|71.57|26896829|2011|74521||34.34|72.18
PB|Lahore|ラホール||31.55|74.34|127688922|2023|205344||31.33|74.21
SD|Karachi|カラチ||24.86|67.01|55245497||140914||24.87|67.05`,
};

export { PK };
