// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 16 subdivisions of Palestinian Territories (PS): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const PS: SubdivisionFactsTable = {
  country: "PS",
  rows: `BTH|Bethlehem|ベツレヘム||31.7|35.21|||660||31.65|35.3
DEB|Deir al-Balah|デイル・アル＝バラフ||31.42|34.35|208716||56||31.42|34.35
GZA|Gaza City|ガザ||31.51|34.46|524001||70||31.52|34.45
HBN|Hebron|ヘブロン||31.54|35.1|711223|2017|997||31.5|35.1
JEM|Jerusalem|エルサレム||31.78|35.23|600000|2007|331.6||31.8|35.3
JEN|جنين|ジェニン||32.46|35.3|256619|2007|583||32.46|35.3
JRH|Jericho|エリコ||31.86|35.46|42320|2007|593||32.02|35.45
KYS|Khan Yunis|ハーンユーニス||31.34|34.3|351934|2016|108||31.35|34.3
NBS|Nablus|ナーブルス||32.22|35.26|388321|2017|605||32.24|35.29
NGZ||||||270246|2007|61||31.52|34.54
QQA|Qalqilya|カルキルヤー||32.19|34.97|121671|2021|166||32.19|35.07
RBH|Ramallah|ラマッラー||31.9|35.2|290401|2006|844||31.93|35.2
RFH|Rafah|ラファフ||31.29|34.25|173372|2007|64||31.3|34.25
SLT|Salfit|サルフィート||32.08|35.18|75444|2017|204||32.12|35.09
TBS|Tubas|チュバス||32.32|35.37|50261|2007|402||32.32|35.49
TKM|Tulkarm|トゥルカレム||32.31|35.03|200000|2022|268||32.31|35.03`,
};

export { PS };
