// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 20 subdivisions of Portugal (PT): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const PT: SubdivisionFactsTable = {
  country: "PT",
  rows: `01|Aveiro|||40.64|-8.66|77916|2018|||40.64|-8.65
02|Beja|||38.02|-7.86|||||38.02|-7.87
03|Braga|||41.55|-8.42|181919|2018|||41.54|-8.42
04|Bragança|||41.81|-6.76|33586|2018|||41.81|-6.76
05|Castelo Branco|||39.82|-7.49|52192|2018|||39.82|-7.49
06|Coimbra|||40.21|-8.43|133724|2018|3947||40.21|-8.43
07|Évora|||38.57|-7.9|52454|2018|||38.57|-7.91
08|Faro (city)|||37.03|-7.92|60974|2018|||37.02|-7.93
09|Guarda|||40.54|-7.27|39103|2018|||40.54|-7.27
10|Leiria|||39.74|-8.81|124857|2018|||39.74|-8.81
11|Lisbon|リスボン||38.71|-9.14|2135992||2800||38.7|-9.18
12|Portalegre|ポルタレグレ||39.32|-7.42|22359|2018|6065||39.29|-7.43
13|Porto|||41.16|-8.63|1817172||2395||41.15|-8.61
14|Santarém|||39.23|-8.68|57398|2018|6747||39.23|-8.68
15|Setúbal|||38.52|-8.89|115758|2018|5064||38.52|-8.89
16|Viana do Castelo|||41.69|-8.83|84636|2018|||41.7|-8.83
17|Vila Real|||41.3|-7.74|49868|2018|4328||41.3|-7.75
18|Viseu|||40.66|-7.91|96991|2018|||40.66|-7.91
20||||||236440|2021|2322||38.62|-28.03
30|Funchal|フンシャル||32.65|-16.92|250769|2021|801||32.75|-17`,
};

export { PT };
