// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 18 subdivisions of Paraguay (PY): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const PY: SubdivisionFactsTable = {
  country: "PY",
  rows: `1|Concepción|コンセプシオン||-23.4|-57.44|204536|2022|18051||-23|-57
10|Ciudad del Este|シウダー・デル・エステ||-25.52|-54.62|784839|2022|14895||-25.51|-54.61
11|Areguá|アレグア||-25.3|-57.42|1866562|2022|2465||-25.3|-57.42
12|Pilar|||-26.86|-58.3|85749|2022|12147||-26.67|-57.92
13|Pedro Juan Caballero|ペドロ・フアン・カバリェロ市||-22.57|-55.72|173770|2022|12933||-22.53|-55.75
14|Saltos del Guairá|サルト・デル・グアイラ||-24.06|-54.31|189128|2022|14667||-24.22|-55.14
15|Villa Hayes|ビージャ・アイェス||-25.09|-57.53|126880|2022|72907||-23.78|-58.61
16|Fuerte Olimpo|フエルテ・オリンポ||-21.04|-57.87|17608|2022|82349||-20.5|-59
19|Filadelfia|||-22.33|-60.02|68595|2022|91669||-21.52|-60.7
2|San Pedro de Ycuamandiyú|||-24.1|-57.08|341895|2022|20002||-24.1|-57.08
3|Caacupé|カアクペ||-25.39|-57.14|271475|2022|4948||-25.38|-57.13
4|Villarrica|ビジャリカ||-25.75|-56.44|180121|2022|3846||-25.75|-56.43
5|Coronel Oviedo|コロネル・オビエド||-25.45|-56.44|430142|2022|11474||-25.2|-55.83
6|Caazapá|カアサパ||-26.18|-56.37|140060|2022|9496||-26.2|-56.38
7|Encarnación|エンカルナシオン||-27.33|-55.87|436966|2022|16525||-27.33|-55.88
8|San Juan Bautista|||-26.63|-57.17|114542|2022|9556||-26.63|-57.17
9|Paraguarí|パラグアリ||-25.63|-57.15|199430|2022|8705||-25.63|-57.15
ASU||||||462241|2022|117||-25.28|-57.63`,
};

export { PY };
