// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 5 subdivisions of Rwanda (RW): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const RW: SubdivisionFactsTable = {
  country: "RW",
  rows: `01||||||1745555|2022|730||-1.95|30.11
02|Rwamagana|ルワマガナ||-1.95|30.44|3563145|2022|9813||-1.75|30.5
03|Byumba hospital|ビュンバ||-1.58|30.07|2038511|2022|3276||-1.57|29.91
04|Kibuye|キブエ||-2.06|29.35|2896484|2022|5882||-2.38|29.21
05|Nyanza|ニャンザ||-2.35|29.75|3002699|2022|6118||-2.62|29.61`,
};

export { RW };
