// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 13 subdivisions of Saudi Arabia (SA): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const SA: SubdivisionFactsTable = {
  country: "SA",
  rows: `01|Riyadh|リヤド||24.65|46.71|6777146|2010|412000||23|45.5
02|Mecca|メッカ||21.42|39.83|5117422|2011|153148||21.5|41
03|Medina|マディーナ||24.47|39.61|2132679|2017|151990||25|39.5
04|Dammam|ダンマーム||26.43|50.1|4105780|2010|672522||22.5|51
05|Burayda|ブライダ||26.33|43.97|961428|2014|58046||26.36|43.97
06|Ha'il|ハーイル||27.52|41.68|467338|2014|103887||27|42
07|Tabuk|タブーク||28.4|36.58|527440|2011|108000||28|37
08|Arar|アルアル||30.98|41.02|245345|2014|111797||30|42.5
09|Jizan|ジザン||16.89|42.56|1567547|2017|13457||17.5|42.5
10|Najran|ナジュラーン||17.49|44.13|392638|2014|119000||17.49|44.13
11|Al Bahah|バーハ||20.01|41.47|476172|2017|9921||20|41.5
12|Sakakah|サカーカ||29.97|40.2|508475|2017|100212||29.5|39.5
14|Abha|アブハ||18.22|42.5|2211875|2017|81000||19|43`,
};

export { SA };
