// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 10 subdivisions of Solomon Islands (SB): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const SB: SubdivisionFactsTable = {
  country: "SB",
  rows: `CE|Tulagi|||-9.1|160.15|||615||-9.07|160.22
CH|Taro Island|タロ島||-6.71|156.4|||3837||-7|156.96
CT||||||84520|2017|22||-9.43|159.95
GU|Honiara|ホニアラ||-9.43|159.95|93613|2009|5336||-9.75|160
IS|Buala|ブアラ||-8.17|159.62|||4136||-8|159.02
MK|Kirakira|キラキラ||-10.45|161.92|||3188||-10.56|161.79
ML|Auki|アウキ||-8.77|160.7|||4225||-9|160.98
RB|Tigoa|ティゴア||-11.56|160.07|||671||-11.55|160.08
TE|Lata|||-10.72|165.8|21362|2009|895||-10.75|167
WE|Gizo|||31.8|34.94|||5475||-8|157`,
};

export { SB };
