// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 18 subdivisions of Sudan (SD): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const SD: SubdivisionFactsTable = {
  country: "SD",
  rows: `DC|Zalingei|ザリンゲイ||12.9|23.48|751400|2018|||12.91|23.47
DE|Ed Daein|ダイーン||11.43|26.15|||||11.17|26.5
DN|Al-Fashir|エル＝ファーシル||13.63|25.35|1583179||296420||17.74|25.5
DS|Nyala|ニャラ||12.05|24.88|3765800|2018|127300||11.52|25.03
DW|Geneina|ジュナイナ||13.45|22.45|||79460||13.55|22.71
GD|Al Qadarif|ガダーレフ||14.03|35.38|1348378|2008|75263||13.86|34.93
GK|Al-Fulah|フラーフ||11.8|28.4|1800000|2023|106000||12|28.15
GZ|Wad Madani|ワドメダニ||14.4|33.51|4926555|2017|27549||14.5|33.5
KA|Kassala|カッサラ||15.45|36.4|2519100|2018|36710||16.23|35.71
KH|Khartoum|ハルツーム||15.6|32.53|7993900|2017|22142||15.64|32.35
KN|El-Obeid|オベイド||13.18|30.22|2216200|2018|185302||14.37|29.53
KS|Kaduqli|カードゥクリー||11.02|29.72|1300700|2018|79470||11.13|29.88
NB|Ad-Damazin|ダマジン||11.77|34.35|1108400|2018|45844||11.35|34.13
NO|Dongola|ドンゴラ||19.18|30.48|936300|2018|348765||17.62|29.42
NR|Ad-Damir|ダーマル||17.59|33.96|1472257|2017|122123||18.38|33.67
NW|Rabak|ラバク||13.15|32.73|2493900|2018|39701||13.45|32.33
RS|Port Sudan|ポートスーダン||19.62|37.22|1482100|2018|218887||19.06|35.64
SI|Singa|シンガ||13.15|33.93|1918700|2018|37844||12.94|34.19`,
};

export { SD };
