// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 5 subdivisions of Singapore (SG): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const SG: SubdivisionFactsTable = {
  country: "SG",
  rows: `01||||||||||1.29|103.85
02||||||||||1.37|103.95
03||||||||||1.3|103.82
04||||||||||1.32|103.9
05||||||||||1.32|103.72`,
};

export { SG };
