// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 8 subdivisions of Slovakia (SK): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const SK: SubdivisionFactsTable = {
  country: "SK",
  rows: `BC|Banská Bystrica|バンスカー・ビストリツァ||48.74|19.15|607581|2025|9453.97|2025|48.73|19.15
BL|Bratislava|ブラチスラヴァ||48.15|17.11|739635|2025|2052.61|2025|48.14|17.11
KI|Košice|コシツェ||48.72|21.25|777933|2025|6754.27|2025|48.72|21.86
NI|Nitra|ニトラ||48.31|18.09|661995|2025|6343.72|2025|48.31|18.09
PV|Prešov|プレショフ||49|21.23|810075|2025|8972.65|2025|49|21.24
TA|Trnava|トルナヴァ||48.38|17.59|565462|2025|4146.29|2025|48.38|17.59
TC|Trenčín|トレンチーン||48.89|18.04|562536|2025|4501.81|2025|48.89|18.04
ZI|Žilina|ジリナ||49.22|18.73|684190|2025|6808.41|2025|49.22|18.74`,
};

export { SK };
