// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 14 subdivisions of Senegal (SN): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const SN: SubdivisionFactsTable = {
  country: "SN",
  rows: `DB|Diourbel|ジュルベル||14.65|-16.23|2080811|2023|4789||14.74|-16.06
DK|Dakar|ダカール||14.67|-17.43|3896564|2023|550||14.72|-17.47
FK|Fatick|ファティック||14.34|-16.41|908858|2023|||14.34|-16.41
KA|Kaffrine|カフリン||14.1|-15.55|821287|2023|11181||14.1|-15.55
KD|Kolda|コルダ||12.9|-14.94|916513|2023|||12.9|-14.94
KE|Kédougou|ケドゥグ||12.56|-12.18|245288|2023|16896||12.56|-12.17
KL|Kaolack|カオラック||14.14|-16.08|1338671|2023|5357||14.17|-16.08
LG|Nguer Malal|||15.62|-16.22|1127119|2023|24847||15.61|-16.23
MT|Matam|マタム||15.62|-13.33|833657|2023|29616||15.66|-13.26
SE|Sédhiou|セディウ||12.71|-15.56|590784|2023|7350||12.7|-15.56
SL|Saint-Louis|サン＝ルイ||16.03|-16.5|1204863|2023|19034||16.03|-16.5
TC|Tambacounda|タンバクンダ||13.77|-13.67|988193|2023|42706||13.77|-13.67
TH|Thiès|ティエス||14.79|-16.92|2467523|2023|6601||14.79|-16.94
ZG|Ziguinchor|ジガンショール||12.59|-16.27|612343|2023|7339||12.56|-16.26`,
};

export { SN };
