// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 18 subdivisions of Somalia (SO): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const SO: SubdivisionFactsTable = {
  country: "SO",
  rows: `AW|Borama|ボラマ||9.93|43.18|1450000|2014|16294||10.8|43.35
BK|Hudur|フドゥール||4.12|43.89|||||4.35|43.55
BN|Mogadishu|モガディシュ||2.04|45.34|1650227|2014|370||2.05|45.26
BR|Bosaso|ボサソ||11.28|49.18|||70088||10.83|50.18
BY|Baidoa|バイドア||3.12|43.65|||||3.07|43.84
GA|Dusmareb|ドゥサマレブ||5.54|46.39|||||5.34|46.62
GE|Garbahaareey|ガーバハレ||3.35|42.27|||85389||2.44|41.48
HI|Beledweyne|ベレトウェイン||4.74|45.2|||90000||4.78|45.45
JD|Bu'ale|ブアレ||1.08|42.58|||||0.98|42.65
JH|Kismayo|キスマヨ||-0.36|42.55|643|2008|42876||0.43|41.6
MU|Galkayo|ガルカイヨ||6.77|47.43|||||6.11|47.99
NU|Garowe|ガローウェ||8.4|48.48|||26180||8.35|48.72
SA
SD|Jowhar|ジョハール||2.78|45.5|514900||22.66||2.82|46.1
SH|Merca|マルカ||1.72|44.77|||25285||1.77|44.39
SO|Las Anod|ラス・アノド||8.48|47.36|115306|2007|39240||8.4|47.69
TO|Burao|ブラオ||9.53|45.53|941832|2007|30426||8.61|46.25
WO|Hargeisa|ハルゲイサ||9.57|44.06|1242003||17429||9.33|44.42`,
};

export { SO };
