// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 10 subdivisions of Suriname (SR): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const SR: SubdivisionFactsTable = {
  country: "SR",
  rows: `BR|Brokopondo|ブロコポンド||5.07|-54.97|8340||7364||4.77|-55.13
CM|Nieuw Amsterdam|ニウ・アムステルダム||5.88|-55.08|||2353||5.87|-54.92
CR|Totness|トトネス||5.88|-56.33|||3902||5.76|-56.28
MA|Albina|アルビーナ||5.5|-54.05|18294|2012|4627||5.77|-54.32
NI|Nieuw Nickerie|ニウ・ニッケリー||5.93|-56.97|||5353||5.77|-56.87
PM|Paramaribo|パラマリボ||5.87|-55.17|242946|2004|182||5.82|-55.17
PR|Onverwacht|オンフェルワハト||5.59|-55.19|||5393||5.43|-55.34
SA|Groningen|フローニンゲン||5.78|-55.47|||3636||5.78|-55.62
SI||||||37065|2012|130567||3.78|-56.03
WA|Lelydorp|レリードルプ||5.7|-55.22|||443||5.8|-55.26`,
};

export { SR };
