// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 10 subdivisions of South Sudan (SS): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const SS: SubdivisionFactsTable = {
  country: "SS",
  rows: `BN|Aweil|アウェル||8.77|27.4|720898|2008|33558||8.73|26.9
BW|Wau|ワーウ||7.7|27.98|333431|2008|91079.95||7.88|25.87
EC|Juba|ジュバ||4.85|31.58|1103592|2008|43033||4.35|31.2
EE|Torit|||4.42|32.57|906126|2008|82542||4.75|33.18
EW|Yambio|ヤンビオ||4.57|28.42|619029|2008|79342.66||5.32|28.4
JG|Bor|ボー||6.22|31.55|1358602|2008|122479||7.4|32.07
LK|Rumbek|ルンベク||6.8|29.68|695730|2008|43595.08||6.77|28.88
NU|Malakal|マラカル||9.53|31.65|1385478|2017|77773||9.53|32.67
UY|Bentiu|ベンティーウ||9.25|29.8|585801|2008|35956||9|29.7
WR|Kuajok|クアジョク||8.31|27.99|972928|2008|31027||8.39|28.25`,
};

export { SS };
