// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 7 subdivisions of São Tomé & Príncipe (ST): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const ST: SubdivisionFactsTable = {
  country: "ST",
  rows: `01|São Tomé|サントメ||0.34|6.73|80647|2024|16.5||0.33|6.73
02|Santana|サンタナ||0.25|6.74|20794|2024|119||0.22|6.7
03|São João dos Angolares|ドナ・エウゲニア||0.13|6.65|7424|2024|267||0.08|6.58
04|Neves|ネヴィス||0.36|6.55|17129|2024|230||0.28|6.5
05|Guadalupe|グアダルーペ||0.37|6.63|23086|2024|105||0.37|6.67
06|Trindade|トリンダージ||0.3|6.67|50697|2024|122||0.25|6.67
P|Santo António|サント・アントニオ||1.64|7.42|9830|2024|142||1.62|7.4`,
};

export { ST };
