// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 14 subdivisions of El Salvador (SV): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const SV: SubdivisionFactsTable = {
  country: "SV",
  rows: `AH|Ahuachapán|アワチャパン||13.92|-89.85|348880|2024|1240||13.92|-89.85
CA|Sensuntepeque|センスンテペケ||13.88|-88.63|143049|2024|1104||13.88|-88.63
CH|Chalatenango|チャラテナンゴ||14.04|-88.94|185930|2024|2017||14.04|-88.94
CU||||||244901|2024|756.2||13.72|-88.93
LI|Santa Tecla|サンタ・テクラ||13.67|-89.29|765879|2024|1653||13.67|-89.29
MO|San Francisco Gotera|サン・フランシスコ・ゴテラ||13.7|-88.11|169784|2024|1447||13.7|-88.11
PA|Zacatecoluca|サカテコルーカ||13.51|-88.87|318374|2024|1224||13.51|-88.87
SA|Santa Ana|サンタ・アナ||13.99|-89.56|552938|2024|2023||13.99|-89.56
SM|San Miguel|サンミゲル||13.48|-88.18|447634|2024|2077||13.48|-88.18
SO|Sonsonate|ソンソナーテ||13.72|-89.73|470455|2024|1226||13.72|-89.73
SS|San Salvador|サンサルバドル||13.7|-89.19|1563371|2024|886.1||13.7|-89.19
SV|San Vicente|サン・ビセンテ||13.64|-88.78|161857|2024|1184||13.64|-88.78
UN|La Unión|ラ・ウニオン||13.34|-87.84|224375|2024|2074||13.34|-87.84
US|Usulután|ウスルタン||13.34|-88.44|325494|2024|2130||13.34|-88.44`,
};

export { SV };
