// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 6 subdivisions of Turkmenistan (TM): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const TM: SubdivisionFactsTable = {
  country: "TM",
  rows: `A|Arkadag|アルカダグ||38.07|58.07|886845|2022|97160||38.5|59
B|Balkanabat|バルカナバート||39.51|54.37|529895|2022|139270||40|55
D|Daşoguz|ダショグズ||41.82|59.98|1550354|2022|73430||41|58.5
L|Türkmenabat|テュルクメナバート||39.1|63.57|1447298|2022|93730||39|63
M|Mary|マル||37.6|61.83|1613386|2022|87150||37|62
S||||||1030063|2022|765||37.95|58.38`,
};

export { TM };
