// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 15 subdivisions of Trinidad & Tobago (TT): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const TT: SubdivisionFactsTable = {
  country: "TT",
  rows: `ARI||||||33807|2011|12||10.63|-61.28
CHA||||||83489|2011|||10.51|-61.41
CTT|Couva|クーヴァ||10.42|-61.45|||||10.42|-61.45
DMN|Diego Martin|ディエゴ・マーティン||10.71|-61.56|||126||10.72|-61.57
MRC||||||||||10.3|-61.01
PED||||||||246.91||10.2|-61.45
POS||||||49031|2025|12||10.67|-61.52
PRT|Princes Town|プリンセス・タウン||10.27|-61.38|||||10.27|-61.38
PTF||||||19056|2000|23.88||10.17|-61.67
SFO||||||55419|2000|18.64||10.28|-61.47
SGE||||||||927||10.57|-61.13
SIP||||||||510.48||10.13|-61.5
SJL|San Juan|||10.65|-61.45|||898.94||10.65|-61.48
TOB||||||60874|2011|300||11.25|-60.67
TUP||||||||||10.63|-61.38`,
};

export { TT };
