// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 9 subdivisions of U.S. Outlying Islands (UM): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const UM: SubdivisionFactsTable = {
  country: "UM",
  rows: `67||||||0|2018|2.67||16.73|-169.53
71||||||14|2014|||28.21|-177.35
76||||||0|2018|5.4||18.4|-75.01
79||||||100|2017|7.1||19.3|166.63
81||||||0|2018|2.1||0.19|-176.48
84||||||0|2015|2.6||0.81|-176.62
86||||||0|2015|4.75||-0.37|-160
89||||||0|2015|0.01||6.38|-162.42
95||||||0|2018|3.9||5.88|-162.08`,
};

export { UM };
