// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 19 subdivisions of Uruguay (UY): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const UY: SubdivisionFactsTable = {
  country: "UY",
  rows: `AR|Artigas|アルティガス||-30.4|-56.46|77246|2023|11938.54||-30.62|-56.95
CA|Canelones|カネローネス||-34.52|-56.28|608956|2023|4527.22||-34.52|-56.28
CL|Melo|メロ||-32.37|-54.17|91021|2023|13641.47||-32.37|-54.17
CO|Colonia del Sacramento|コロニア・デル・サクラメント||-34.45|-57.81|135797|2023|6108.31||-34.12|-57.68
DU|Durazno|ドゥラスノ||-33.38|-56.53|62010|2023|12231.26||-33.04|-56.03
FD|Florida|フロリダ||-34.1|-56.21|70324|2023|10410.41||-34.1|-56.22
FS|Trinidad|トリニダ||-33.51|-56.9|26271|2023|5144.58||-33.6|-56.83
LA|Minas|ミナス||-34.37|-55.24|59175|2023|10037.77||-34.38|-55.24
MA|Maldonado|マルドナド||-34.91|-54.96|212841|2023|4799.73||-34.63|-54.88
MO|Montevideo|モンテビデオ||-34.91|-56.19|1302954|2023|530|2023|-34.88|-56.18
PA||||||121838|2023|13968.61||-32.07|-57.33
RN|Fray Bentos|フライ・ベントス||-33.12|-58.31|57338|2023|9532.87||-33.12|-58.3
RO|Rocha|ロチャ||-34.48|-54.33|80710|2023|10539.66||-33.93|-54
RV|Rivera|リベラ||-30.9|-55.54|109300|2023|9329.47||-31.5|-55.25
SA|Salto|サルト||-31.39|-57.96|136195|2023|14011.93||-31.32|-57.04
SJ|San José de Mayo|サン・ホセ・デ・マジョ||-34.34|-56.71|119718|2023|5014.61||-34.34|-56.71
SO|Mercedes|メルセデス||-33.25|-58.03|83684|2023|8994.93||-33.52|-57.75
TA|Tacuarembó|タクアレンボー||-31.71|-55.98|96013|2023|15973.31||-32.11|-55.76
TT|Treinta y Tres|トレインタ・イ・トレス||-33.23|-54.39|47705|2023|9290.83||-33.23|-54.38`,
};

export { UY };
