// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 6 subdivisions of St. Vincent & Grenadines (VC): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const VC: SubdivisionFactsTable = {
  country: "VC",
  rows: `01|Georgetown|||13.29|-61.12|||149||13.29|-61.12
02|Layou|ラヨー||13.2|-61.27|||29||13.2|-61.27
03|Chateaubelair|チャトーベレア||13.29|-61.24|||80.29||13.28|-61.24
04|Kingstown|キングスタウン||13.16|-61.23|||52||13.16|-61.23
05|Barrouallie|バローアリー||13.24|-61.27|||37||13.23|-61.27
06|Port Elizabeth|||13.01|-61.23|9200|2000|44.03||13.02|-61.23`,
};

export { VC };
