// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 25 subdivisions of Venezuela (VE): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const VE: SubdivisionFactsTable = {
  country: "VE",
  rows: `A|Caracas|カラカス||10.51|-66.91|||1930||10.47|-67
B||||||1440875|2011|43300||8.95|-64.25
C|San Fernando de Apure|サン・フェルナンド・デ・アプレ||7.89|-67.47|587056|2015|76500||7.13|-69
D|Maracay|マラカイ||10.25|-67.6|1839075|2017|7014||9.95|-67.05
E|Barinas|バリナス||8.63|-70.22|||35200||8.13|-69.42
F|Ciudad Bolívar|シウダ・ボリバル||8.1|-63.55|2069064|2015|240528||5.95|-63.33
G|Valencia|バレンシア||10.17|-68|2843161|2016|4650||10.18|-67.97
H|San Carlos|||9.65|-68.58|500420|2017|1480||9.35|-68.32
I|Coro|コロとその港||11.39|-69.68|902847|2011|24800||11.41|-69.68
J|San Juan de Los Morros|サン・ファン・デ・ロス・モーロス||9.89|-67.34|964264|2018|64986||8.7|-66.6
K|Barquisimeto|バルキシメト||10.07|-69.35|2142583|2023|19800||10.07|-69.86
L|Mérida|メリダ||8.57|-71.18|||11300||8.52|-71.27
M|Los Teques|ロス・テケス||10.34|-67.04|||7950||10.25|-66.42
N|Maturín|マトゥリン||9.74|-63.19|905443|2011|28900||9.42|-63.07
O|La Asunción|ラ・アスンシオン||11.03|-63.86|491610|2011|1150||11|-64
P|Guanare|グアナレ||9.04|-69.75|||15200||9.1|-69.27
R|Cumaná|クマナ||10.45|-64.17|896291|2011|11800||10.55|-63.2
S|San Cristóbal|||7.77|-72.23|||11100||7.83|-72.08
T|Trujillo|トルヒーヨ||9.37|-70.44|||7400||9.42|-70.5
U|San Felipe|||10.34|-68.75|499049|2005|7100||10.3|-68.7
V|Maracaibo|マラカイボ||10.63|-71.63|4323467||50230||9.83|-72.25
W||||||2155|2011
X|La Guaira|ラ・グアイラ||10.6|-66.93|||1496||10.57|-66.87
Y|Tucupita|トゥクピタ||9.06|-62.05|167676|2011|40200||8.7|-61.15
Z|Puerto Ayacucho|プエルト・アヤクーチョ||5.66|-67.63|176614|2023|177617||3.5|-66`,
};

export { VE };
