// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 6 subdivisions of Vanuatu (VU): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const VU: SubdivisionFactsTable = {
  country: "VU",
  rows: `MAP|Lakatoro|ラカトロ||-16.11|167.42|36727|2009|2779||-16.25|167.75
PAM|Saratamata|||-15.29|167.99|||1198||-15.5|168
SAM|Luganville|ルーガンビル||-15.51|167.17|||4248||-15.33|166.75
SEE|Port Vila|ポートビラ||-17.73|168.32|||1455||-17.33|168.5
TAE|Isangel|イサンゲル||-19.55|169.27|32540|2009|1628||-19.5|169.5
TOB|Sola|||-13.88|167.55|||882||-13.75|167.5`,
};

export { VU };
