// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The facts about the 10 subdivisions of Zimbabwe (ZW): capitals, population, area, coordinates.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-facts-2026-10-09.json

import type { SubdivisionFactsTable } from "../../rows";

const ZW: SubdivisionFactsTable = {
  country: "ZW",
  rows: `BU|Bulawayo|ブラワヨ||-20.17|28.57|||||-20.17|28.58
HA||||||||872||-17.85|31.06
MA|Mutare|ムタレ||-18.97|32.67|||36459||-19|32.5
MC|Bindura|ビンドゥラ||-17.3|31.33|1166928|2013|28347||-17|31
ME|Marondera|マロンデラ||-18.18|31.55|||32230||-17.5|32
MI|Gweru|グウェル||-19.45|29.82|||49166||-19|30
MN||||||827645|2022|75025||-19|27.5
MS|Gwanda|グワンダ||-20.95|29.02|||54172||-21|29.5
MV|Masvingo|マシンゴ||-20.07|30.83|||56566||-21|31
MW|Chinhoyi|チノイ||-17.35|30.2|||57441||-17|29.5`,
};

export { ZW };
