// The demo page's own words, in the two languages it speaks. A `{name}` in a line is filled in when it is shown.
// docs/strings-ja.md lists these beside each other, and a test keeps that list true (`pnpm docs:make` rewrites it).
export const WORDS = {
  en: {
    pageApi: "API reference",
    pitch: "Every country and its states, provinces and prefectures, with ISO 3166 codes and names in English and Japanese. Type in any panel and the answer appears, from the package's own data.",
    name: "Kuni (国) is Japanese for “country”, and also for the region somebody comes from.",
    nameLink: "About the name",
    input: "Type",
    examples: "Try",
    call: "The call",
    moreTitle: "Using it",
    moreText: "Each panel above is the package itself. The countries are the main entry; one country's subdivisions are an entry of their own, or loaded when they are wanted. Each line below is all it takes.",
    foot: "Everything is looked up in your browser from the package's own data. Nothing leaves this page.",
    missing: "none",
    // find
    find_title: "Find a country",
    find_blurb: "Type a country's name in English or Japanese (in kana too), its own name, a name it is also known by (Holland, UK, 米国) or a code. Case, accents and width do not matter.",
    find_codes: "Codes",
    find_name_en: "English",
    find_name_ja: "Japanese",
    find_reading: "Reading",
    find_short: "Short name",
    find_local: "Own name",
    find_calling: "Calling code",
    find_currency: "Currency",
    find_continent: "Continent",
    find_capital: "Capital",
    find_tld: "Domain",
    find_zones: "Time zones",
    find_divisions: "Divided into",
    find_none: "No country goes by that name. Try Germany, ドイツ, Holland or JP.",
    // list
    list_title: "Subdivisions of a country",
    list_blurb: "Pick a country. Its subdivisions are loaded when they are wanted, each with its code and both names. Where no source has a Japanese name, it says so rather than guess one.",
    list_country: "Country",
    list_level: "Level",
    level_1: "First",
    level_all: "All",
    col_code: "Code",
    col_en: "English",
    col_ja: "Japanese",
    list_count: "{count} subdivisions; the main kind is {type}.",
    list_count_plain: "{count} subdivisions.",
    list_gaps: "{gaps} of them have no Japanese name in any source.",
    list_full: "Every one has a Japanese name.",
    list_none: "This country has no subdivisions in ISO 3166-2.",
    // code
    code_title: "Look up a code",
    code_blurb: "Type an ISO 3166-2 code such as JP-13, CA-ON or US-NY, or a country's own code (JP, JPN, 392), in either case.",
    code_code: "Code",
    code_country: "Country",
    code_name_en: "English",
    code_name_ja: "Japanese",
    code_kind: "Kind",
    code_level: "Level",
    code_parent: "Inside",
    code_reading: "Reading",
    code_none: "Not a code here. Try JP-13, CA-ON, US-NY or FR-75C.",
    // views
    views: "Views",
    tab_lookup: "Look up",
    tab_country: "Country",
    tab_compare: "Compare",
    tab_table: "All countries",
    tab_groupings: "Groupings",
    tab_quiz: "Quiz",
    tab_form: "Form widget",
    tab_quality: "Data quality",
    find_more: "Everything about {name} →",
    download: "Download",
    download_csv: "Download as CSV, for a spreadsheet",
    download_json: "Download as JSON, for a program",
    download_txt: "Download as plain text, in columns",
    copy: "Copy",
    copied: "Copied",
    copy_failed: "Could not copy",
    // search
    search_title: "Search by code",
    search_blurb: "Every country that uses a calling code, a currency or a domain: +1 is the whole North American plan, EUR twenty-odd countries.",
    search_by: "Search by",
    search_none: "No country uses that. Try +81, EUR or .jp.",
    search_count: "{count} countries",
    // country
    title_country: "A country, all of it",
    blurb_country: "Everything Kuni knows of one country: its names with their readings, its outline (drawn by Chizu) with the capital marked, its figures with the year each is for, its neighbours, the groupings it is in, and the time now in each of its time zones.",
    help_country: "Pick a country. Its neighbours and groupings are links to their own pages.",
    outline_loading: "Drawing the outline…",
    outline_none: "Chizu draws no outline of this one on its own.",
    outline_of: "The outline of {name}, with its capital marked",
    outline_credit: "Outline: Chizu, from Natural Earth (public domain). The dot is the capital.",
    fact_population: "Population",
    fact_area: "Area",
    fact_density: "Density",
    fact_borders: "Land borders",
    fact_driving: "Drives on the",
    fact_week: "Week starts",
    fact_units: "Units, paper, clock",
    fact_point: "Coordinates",
    fact_groupings: "Belongs to",
    none_capital: "none",
    none_population: "no permanent population",
    none_roads: "no public roads",
    no_borders: "none: an island, or islands",
    as_of_year: " ({year})",
    land_only: ", the land only",
    per_km2: "{value} per km²",
    drives_left: "left",
    drives_right: "right",
    drives_left_short: "left",
    drives_right_short: "right",
    day_mon: "Monday",
    day_sun: "Sunday",
    day_sat: "Saturday",
    day_fri: "Friday",
    measure_metric: "metric",
    measure_US: "US customary",
    measure_UK: "metric, with miles and pints",
    clock_12: "12-hour clock",
    clock_24: "24-hour clock",
    zones_title: "Time zones, {count}",
    zones_short: "Time zones",
    zones_note: "The time now there, from this device's own clock and time-zone rules; nothing is fetched.",
    zone: "Zone",
    zone_now: "Now",
    // compare
    title_compare: "Compare two countries",
    blurb_compare: "Two countries side by side, with how many times bigger one is than the other and how far apart their capitals are.",
    help_compare: "Pick the two countries to compare, or swap them.",
    compare_a: "One",
    compare_b: "The other",
    swap: "Swap",
    compare_scale: "Each outline fills its own box, so the two are not drawn to one scale.",
    compare_diff: "Difference",
    times: "×{value}",
    km_apart: "{value} km apart",
    neighbours_yes: "neighbours",
    same: "the same",
    differ: "different",
    // table
    title_table: "Every country",
    blurb_table: "All 250 countries in one table. Type to filter, narrow by continent or by grouping, press a heading to sort, and download what is on show.",
    help_table_filter: "Type part of a name, in English or Japanese, a code or a capital.",
    help_table_narrow: "Keep one continent, or the members of one grouping.",
    filter: "Filter",
    grouping: "Grouping",
    all_continents: "Every continent",
    all_groupings: "Every country",
    col_country: "Country",
    col_area: "Area (km²)",
    col_subdivision: "Subdivision",
    table_count: "{count} countries on show.",
    // groupings
    title_groupings: "Groupings",
    blurb_groupings: "Continents, UN regions, international bodies, informal groupings such as the Middle East, and the regions inside a country, each with its members, its definition and its source. For a body, its members on any day.",
    help_grouping: "Pick a grouping. Members are links to their own pages.",
    help_grouping_day: "For an international body, pick a day to see its members on that day.",
    on_day: "On",
    today: "Today",
    kind_continent: "Continents",
    kind_m49: "UN M49 regions",
    kind_membership: "International bodies",
    kind_informal: "Informal groupings",
    kind_subdivision: "Regions inside a country",
    informal: "informal",
    source: "Source",
    as_of: "as of {day}",
    inside: "Inside",
    since: "Member since",
    members_now: "{count} members now.",
    members_on: "{count} members on {day}.",
    others: "Not members",
    former: "Former memberships",
    status_candidate: "candidate",
    status_associate: "associate",
    status_observer: "observer",
    status_suspended: "suspended",
    // quiz
    title_quiz: "Quiz",
    blurb_quiz: "Capitals, the country a state or prefecture is in, and calling codes. Each round comes from a seed: share the link and a friend gets the same questions.",
    help_quiz: "Choose what to be asked.",
    help_quiz_seed: "Start a new round, or copy the link to this one.",
    quiz_kind: "Ask",
    quiz_capital: "Capitals",
    quiz_subdivision: "Which country?",
    quiz_calling: "Calling codes",
    quiz_new: "New round",
    quiz_capital_q: "What is the capital of {name}?",
    quiz_subdivision_q: "Which country is {name} in?",
    quiz_calling_q: "Whose calling code is {code}?",
    quiz_number: "Question {number} · seed {seed}",
    quiz_choices: "The choices",
    quiz_right: "Right!",
    quiz_wrong: "Not this time: it is {name}.",
    quiz_next: "Next question",
    quiz_streak: "in a row",
    quiz_best: "best in a row",
    quiz_right_count: "right",
    quiz_note: "Map quizzes are Chizu's. The best streak is kept on this device only.",
    // form
    title_form: "A country and region form widget",
    blurb_form: "The select a sign-up form needs: a country, then its states, provinces or prefectures, in English or Japanese. Copy the code to use it in a page of your own.",
    help_form_lang: "The widget's own language, which need not be the page's.",
    help_form_typed: "Type a country the way people do (UK, Holland, どいつ) and the select follows.",
    form_lang: "Widget language",
    form_typed: "Typed",
    form_typed_found: "That is {name} ({code}).",
    form_typed_none: "No country goes by that name.",
    form_submits: "What the form would send",
    form_code: "The code",
    form_lists: "The lists",
    form_lists_countries: "Every country's code and names:",
    form_lists_regions: "This country's regions, with their kinds:",
    // quality
    title_quality: "Data quality, in the open",
    blurb_quality: "What is known, what is missing and why, and where the sources disagree. Nothing missing is filled with a guess.",
    q_ja_first: "first-level subdivisions with a Japanese name",
    q_disagree: "Japanese names where CLDR and Wikidata disagree",
    q_overrides: "names corrected by hand",
    q_fact_gaps: "facts missing, each with its reason",
    q_gaps_title: "Subdivisions with no Japanese name",
    q_gaps_text: "{count} subdivisions have a Japanese name in no source, so theirs is null rather than a guess. By country:",
    q_missing: "Without a Japanese name",
    q_disagree_title: "Where CLDR and Wikidata disagree",
    q_disagree_text: "Kuni keeps CLDR's name; the list is for a reader of Japanese to judge.",
    q_cldr: "CLDR (kept)",
    q_wikidata: "Wikidata",
    q_overrides_title: "Corrected by hand",
    q_overrides_text: "Names a reviewer found wrong or out of date, and the reason for each.",
    q_kept: "Kept",
    q_why: "Why",
    q_questions_title: "Open questions",
    q_questions_text: "Left for a native reader of Japanese.",
    q_facts_title: "Facts no source gives",
    q_facts_text: "Each missing fact is a decision, with its reason.",
    q_fact: "Fact",
    q_field_population: "Population",
    q_field_capital: "Capital",
    q_field_capitalPoint: "Capital's coordinates",
    q_field_drivingSide: "Driving side",
    q_field_borders: "Land borders",
    q_subfacts_title: "Facts about subdivisions",
    q_subfacts_text: "How many subdivisions have each fact, and why the rest are null.",
    q_borders_title: "Borders Wikidata states that are not kept",
    q_borders_text: "Wikidata does not say whether a border is on land or at sea; these are not confirmed by Natural Earth's outlines, so they are left out.",
    q_bodies_title: "International bodies, checked against Wikidata",
    q_bodies_text: "Each body's members are its own published list; this is how Wikidata compares.",
    copy_link: "Copy the link",
    copy_code: "Copy the code",
    kindone_continent: "continent",
    kindone_m49: "UN M49 region",
    kindone_membership: "international body",
    kindone_informal: "informal grouping",
    kindone_subdivision: "regions inside a country",
    q_islands: "Beside these, {count} countries have no land border, each listed with its reason: islands, and Antarctica. Their borders are an empty list, which is a fact, not a gap.",
    also_called: "Also called",
  },
  ja: {
    pageApi: "API（英語）",
    pitch: "世界の国と、その州・県・省などの行政区画を、ISO 3166 のコードと英語・日本語の名前で調べられます。どのパネルも、入力するとパッケージ自身のデータからすぐに結果を表示します。",
    name: "「国（くに）」は国家のことであり、生まれ育った土地のことでもあります。",
    nameLink: "名前について（英語）",
    input: "入力",
    examples: "例",
    call: "呼び出し",
    moreTitle: "使い方",
    moreText: "上のパネルはどれも、このパッケージをそのまま動かしています。国のデータはメインのエントリーポイントにあり、国ごとの行政区画は国別のエントリーポイントから取り込むか、必要になったときに読み込みます。どれも、下のとおり1行で書けます。",
    foot: "検索はすべて、パッケージ自身のデータを使ってお使いのブラウザ内で行っています。入力した内容がこのページの外に送られることはありません。",
    missing: "なし",
    // find
    find_title: "国を探す",
    find_blurb: "英語か日本語の国名（かなでも可）、現地語の国名、別名（Holland、UK、米国など）、コードのいずれかを入力します。大文字と小文字、アクセント記号、全角と半角は区別しません。",
    find_codes: "コード",
    find_name_en: "英語名",
    find_name_ja: "日本語名",
    find_reading: "読み",
    find_short: "略称",
    find_local: "現地語名",
    find_calling: "国番号",
    find_currency: "通貨",
    find_continent: "大陸",
    find_capital: "首都",
    find_tld: "ドメイン",
    find_zones: "タイムゾーン",
    find_divisions: "行政区画",
    find_none: "その名前の国は見つかりませんでした。Germany、ドイツ、Holland、JP などで試してみてください。",
    // list
    list_title: "国の行政区画",
    list_blurb: "国を選ぶと、その国の行政区画をその場で読み込み、コードと英語名・日本語名を一覧にします。どの資料にも日本語名がないものは、推測で補わずに「なし」と表示します。",
    list_country: "国",
    list_level: "階層",
    level_1: "第一級",
    level_all: "すべて",
    col_code: "コード",
    col_en: "英語名",
    col_ja: "日本語名",
    list_count: "{count}件。主な種類は「{type}」です。",
    list_count_plain: "{count}件。",
    list_gaps: "そのうち{gaps}件は、どの資料にも日本語名がありません。",
    list_full: "すべてに日本語名があります。",
    list_none: "この国には ISO 3166-2 の行政区画がありません。",
    // code
    code_title: "コードで探す",
    code_blurb: "JP-13、CA-ON、US-NY のような ISO 3166-2 のコード、または国のコード（JP、JPN、392）を入力します。大文字でも小文字でもかまいません。",
    code_code: "コード",
    code_country: "国",
    code_name_en: "英語名",
    code_name_ja: "日本語名",
    code_kind: "種類",
    code_level: "階層",
    code_parent: "上位の区画",
    code_reading: "読み",
    code_none: "該当するコードがありません。JP-13、CA-ON、US-NY、FR-75C などで試してみてください。",
    // views
    views: "表示",
    tab_lookup: "調べる",
    tab_country: "国のページ",
    tab_compare: "比べる",
    tab_table: "すべての国",
    tab_groupings: "グループ",
    tab_quiz: "クイズ",
    tab_form: "フォーム部品",
    tab_quality: "データの品質",
    find_more: "{name}について詳しく見る →",
    download: "ダウンロード",
    download_csv: "表計算ソフト用のCSVでダウンロード",
    download_json: "プログラム用のJSONでダウンロード",
    download_txt: "列をそろえたテキストでダウンロード",
    copy: "コピー",
    copied: "コピーしました",
    copy_failed: "コピーできませんでした",
    // search
    search_title: "コードで探す",
    search_blurb: "国番号・通貨・ドメインから、それを使っている国をすべて探します。+1 は北米の多くの国と地域、EUR は20か国あまりで使われています。",
    search_by: "検索の種類",
    search_none: "その国番号・通貨・ドメインを使っている国はありません。+81、EUR、.jp などで試してみてください。",
    search_count: "{count}か国",
    // country
    title_country: "ひとつの国のすべて",
    blurb_country: "ひとつの国についてKuniが持つ情報をすべて表示します。読みがなつきの国名、首都に印をつけた輪郭（Chizuで描画）、対象年つきの統計、隣国、所属するグループ、各タイムゾーンの現在時刻です。",
    help_country: "国を選びます。隣国やグループを押すと、そのページに移ります。",
    outline_loading: "輪郭を描いています…",
    outline_none: "Chizuには、この国・地域だけの輪郭はありません。",
    outline_of: "{name}の輪郭（首都に印）",
    outline_credit: "輪郭：Chizu（元データはNatural Earth、パブリックドメイン）。点は首都です。",
    fact_population: "人口",
    fact_area: "面積",
    fact_density: "人口密度",
    fact_borders: "陸で国境を接する国",
    fact_driving: "車の通行",
    fact_week: "週の始まり",
    fact_units: "単位・用紙・時刻表記",
    fact_point: "座標",
    fact_groupings: "所属",
    none_capital: "なし",
    none_population: "定住人口なし",
    none_roads: "公道なし",
    no_borders: "なし（島国・島しょ地域）",
    as_of_year: "（{year}年）",
    land_only: "（陸地のみ）",
    per_km2: "1 km²あたり{value}人",
    drives_left: "左側通行",
    drives_right: "右側通行",
    drives_left_short: "左",
    drives_right_short: "右",
    day_mon: "月曜日",
    day_sun: "日曜日",
    day_sat: "土曜日",
    day_fri: "金曜日",
    measure_metric: "メートル法",
    measure_US: "ヤード・ポンド法（米国）",
    measure_UK: "メートル法（マイル・パイントも使用）",
    clock_12: "12時間制",
    clock_24: "24時間制",
    zones_title: "タイムゾーン（{count}つ）",
    zones_short: "タイムゾーン",
    zones_note: "この端末の時計とタイムゾーンの規則から計算した現地の現在時刻です。通信はしていません。",
    zone: "ゾーン",
    zone_now: "現在時刻",
    // compare
    title_compare: "2つの国を比べる",
    blurb_compare: "2つの国を並べて比べます。どちらが何倍大きいか、首都どうしが何km離れているかも表示します。",
    help_compare: "比べる2つの国を選びます。左右を入れ替えることもできます。",
    compare_a: "1つ目",
    compare_b: "2つ目",
    swap: "入れ替え",
    compare_scale: "輪郭はそれぞれの枠いっぱいに描いているので、縮尺はそろっていません。",
    compare_diff: "差",
    times: "{value}倍",
    km_apart: "{value} km 離れています",
    neighbours_yes: "隣国どうし",
    same: "同じ",
    differ: "違う",
    // table
    title_table: "すべての国の一覧",
    blurb_table: "250の国と地域をひとつの表にまとめています。入力して絞り込み、大陸やグループで絞り、見出しを押して並べ替え、表示中の行をダウンロードできます。",
    help_table_filter: "英語か日本語の名前の一部、コード、首都名を入力します。",
    help_table_narrow: "大陸、またはグループの加盟国だけを表示します。",
    filter: "絞り込み",
    grouping: "グループ",
    all_continents: "すべての大陸",
    all_groupings: "すべての国",
    col_country: "国",
    col_area: "面積（km²）",
    col_subdivision: "行政区画",
    table_count: "{count}か国を表示中。",
    // groupings
    title_groupings: "国のグループ",
    blurb_groupings: "大陸、国連の地域区分、国際機関、中東のような非公式のグループ、国内の地方区分を、加盟国・定義・出典とともに表示します。国際機関は、日付を指定してその日の加盟国も見られます。",
    help_grouping: "グループを選びます。加盟国を押すと、その国のページに移ります。",
    help_grouping_day: "国際機関の場合、日付を選ぶとその日の加盟国を表示します。",
    on_day: "日付",
    today: "今日",
    kind_continent: "大陸",
    kind_m49: "国連M49の地域",
    kind_membership: "国際機関",
    kind_informal: "非公式のグループ",
    kind_subdivision: "国内の地方区分",
    informal: "非公式",
    source: "出典",
    as_of: "{day}時点",
    inside: "上位の区分",
    since: "加盟日",
    members_now: "現在のメンバー数：{count}",
    members_on: "{day}時点のメンバー数：{count}",
    others: "加盟国以外",
    former: "過去の加盟",
    status_candidate: "加盟候補国",
    status_associate: "準加盟国",
    status_observer: "オブザーバー",
    status_suspended: "資格停止中",
    // quiz
    title_quiz: "クイズ",
    blurb_quiz: "首都、州や県の所属国、国番号のクイズです。問題はシード値から作るので、リンクを送れば友だちにも同じ問題が出ます。",
    help_quiz: "出題の種類を選びます。",
    help_quiz_seed: "新しく始めるか、このラウンドへのリンクをコピーします。",
    quiz_kind: "出題",
    quiz_capital: "首都",
    quiz_subdivision: "どこの国？",
    quiz_calling: "国番号",
    quiz_new: "新しく始める",
    quiz_capital_q: "{name}の首都は？",
    quiz_subdivision_q: "{name}はどの国にある？",
    quiz_calling_q: "国番号 {code} の国は？",
    quiz_number: "第{number}問 ・ シード {seed}",
    quiz_choices: "選択肢",
    quiz_right: "正解！",
    quiz_wrong: "残念、正解は{name}です。",
    quiz_next: "次の問題",
    quiz_streak: "連続正解",
    quiz_best: "最長連続正解",
    quiz_right_count: "正解数",
    quiz_note: "地図クイズはChizuにあります。最高記録はこの端末にだけ保存されます。",
    // form
    title_form: "国と地域を選ぶフォーム部品",
    blurb_form: "登録フォームに必要な選択欄です。国を選ぶと、その国の州・省・都道府県などが選べます。英語と日本語に対応しています。コードをコピーすれば自分のページで使えます。",
    help_form_lang: "フォーム部品の言語です。ページの言語と別に選べます。",
    help_form_typed: "UK、Holland、どいつ のように、ふだん使う名前で国名を入力すると、選択欄がその国に切り替わります。",
    form_lang: "部品の言語",
    form_typed: "入力",
    form_typed_found: "{name}（{code}）です。",
    form_typed_none: "その名前の国は見つかりませんでした。",
    form_submits: "フォームが送信する値",
    form_code: "コード",
    form_lists: "一覧",
    form_lists_countries: "すべての国のコードと名前：",
    form_lists_regions: "この国の地域と種類：",
    // quality
    title_quality: "データの品質を公開",
    blurb_quality: "分かっていること、欠けていることとその理由、資料どうしの食い違いを公開しています。欠けている値を推測で埋めることはしません。",
    q_ja_first: "日本語名がある第一級行政区画",
    q_disagree: "CLDRとWikidataで日本語名が異なるもの",
    q_overrides: "手作業で訂正した名前",
    q_fact_gaps: "理由つきで欠けている情報",
    q_gaps_title: "日本語名のない行政区画",
    q_gaps_text: "{count}件の行政区画は、どの資料にも日本語名がないため、推測せずnullにしています。国別の件数：",
    q_missing: "日本語名なし",
    q_disagree_title: "CLDRとWikidataの食い違い",
    q_disagree_text: "KuniはCLDRの名前を採用しています。この一覧は、日本語を読める方が判断するためのものです。",
    q_cldr: "CLDR（採用）",
    q_wikidata: "Wikidata",
    q_overrides_title: "手作業による訂正",
    q_overrides_text: "確認者が誤りや古い表記と判断した名前と、その理由です。",
    q_kept: "採用",
    q_why: "理由",
    q_questions_title: "未解決の問題",
    q_questions_text: "日本語を母語とする方の判断を待っています。",
    q_facts_title: "どの資料にもない情報",
    q_facts_text: "欠けている情報には、それぞれ理由を記しています。",
    q_fact: "項目",
    q_field_population: "人口",
    q_field_capital: "首都",
    q_field_capitalPoint: "首都の座標",
    q_field_drivingSide: "車の通行",
    q_field_borders: "陸上の国境",
    q_subfacts_title: "行政区画の情報",
    q_subfacts_text: "各項目がある行政区画の数と、残りがnullである理由です。",
    q_borders_title: "Wikidataにあるが採用しなかった国境",
    q_borders_text: "Wikidataは国境が陸上か海上かを区別していません。以下はNatural Earthの輪郭で確認できなかったため、採用していません。",
    q_bodies_title: "国際機関の加盟国とWikidataの照合",
    q_bodies_text: "加盟国は各機関が公表している一覧に基づいています。Wikidataとの違いを示します。",
    copy_link: "リンクをコピー",
    copy_code: "コードをコピー",
    kindone_continent: "大陸",
    kindone_m49: "国連M49の地域",
    kindone_membership: "国際機関",
    kindone_informal: "非公式のグループ",
    kindone_subdivision: "国内の地方区分",
    q_islands: "このほか、{count}の国と地域は陸上の国境がなく、それぞれ理由を記しています（島国・島しょ地域と南極）。国境は空のリストで、欠けている値ではありません。",
    also_called: "別名：",
  },
};
