// The demo page's own words, in the two languages it speaks. A `{name}` in a line is filled in when it is shown.
// docs/strings-ja.md lists these beside each other, and a test keeps that list true (`pnpm docs:make` rewrites it).
export const WORDS = {
  en: {
    pageApi: "API reference",
    pitch: "Every country and its states, provinces and prefectures, with ISO 3166 codes and names in English and Japanese. Type in any panel and the answer appears, from the package's own data.",
    name: "Kuni (国) is Japanese for “country”, and also for the region somebody comes from.",
    nameLink: "About the name",
    input: "Type",
    examples: "Try",
    call: "The call",
    moreTitle: "Using it",
    moreText: "Each panel above is the package itself. The countries are the main entry; one country's subdivisions are an entry of their own, or loaded when they are wanted. Each line below is all it takes.",
    foot: "Everything is looked up in your browser from the package's own data. Nothing leaves this page.",
    missing: "none",
    // find
    find_title: "Find a country",
    find_blurb: "Type a country's name in English or Japanese (in kana too), its own name, a name it is also known by (Holland, UK, 米国) or a code. Case, accents and width do not matter.",
    find_codes: "Codes",
    find_name_en: "English",
    find_name_ja: "Japanese",
    find_reading: "Reading",
    find_short: "Short name",
    find_local: "Own name",
    find_calling: "Calling code",
    find_currency: "Currency",
    find_continent: "Continent",
    find_capital: "Capital",
    find_tld: "Domain",
    find_zones: "Time zones",
    find_divisions: "Divided into",
    find_none: "No country goes by that name. Try Germany, ドイツ, Holland or JP.",
    // list
    list_title: "Subdivisions of a country",
    list_blurb: "Pick a country. Its subdivisions are loaded when they are wanted, each with its code and both names. Where no source has a Japanese name, it says so rather than guess one.",
    list_country: "Country",
    list_level: "Level",
    level_1: "First",
    level_all: "All",
    col_code: "Code",
    col_en: "English",
    col_ja: "Japanese",
    list_count: "{count} subdivisions; the main kind is {type}.",
    list_count_plain: "{count} subdivisions.",
    list_gaps: "{gaps} of them have no Japanese name in any source.",
    list_full: "Every one has a Japanese name.",
    list_none: "This country has no subdivisions in ISO 3166-2.",
    // code
    code_title: "Look up a code",
    code_blurb: "Type an ISO 3166-2 code such as JP-13, CA-ON or US-NY, or a country's own code (JP, JPN, 392), in either case.",
    code_code: "Code",
    code_country: "Country",
    code_name_en: "English",
    code_name_ja: "Japanese",
    code_kind: "Kind",
    code_level: "Level",
    code_parent: "Inside",
    code_reading: "Reading",
    code_none: "Not a code here. Try JP-13, CA-ON, US-NY or FR-75C.",
  },
  ja: {
    pageApi: "API（英語）",
    pitch: "世界の国と、その州・県・省などの行政区画を、ISO 3166 のコードと英語・日本語の名前で調べられます。どのパネルも、入力するとパッケージ自身のデータからすぐに結果を表示します。",
    name: "「国（くに）」は国家のことであり、生まれ育った土地のことでもあります。",
    nameLink: "名前について（英語）",
    input: "入力",
    examples: "例",
    call: "呼び出し",
    moreTitle: "使い方",
    moreText: "上のパネルはどれも、このパッケージをそのまま動かしています。国のデータはメインのエントリーポイントにあり、国ごとの行政区画は国別のエントリーポイントから取り込むか、必要になったときに読み込みます。どれも、下のとおり1行で書けます。",
    foot: "検索はすべて、パッケージ自身のデータを使ってお使いのブラウザ内で行っています。入力した内容がこのページの外に送られることはありません。",
    missing: "なし",
    // find
    find_title: "国を探す",
    find_blurb: "英語か日本語の国名（かなでも可）、現地語の国名、別名（Holland、UK、米国など）、コードのいずれかを入力します。大文字と小文字、アクセント記号、全角と半角は区別しません。",
    find_codes: "コード",
    find_name_en: "英語名",
    find_name_ja: "日本語名",
    find_reading: "読み",
    find_short: "略称",
    find_local: "現地語名",
    find_calling: "国番号",
    find_currency: "通貨",
    find_continent: "大陸",
    find_capital: "首都",
    find_tld: "ドメイン",
    find_zones: "タイムゾーン",
    find_divisions: "行政区画",
    find_none: "その名前の国は見つかりませんでした。Germany、ドイツ、Holland、JP などで試してみてください。",
    // list
    list_title: "国の行政区画",
    list_blurb: "国を選ぶと、その国の行政区画をその場で読み込み、コードと英語名・日本語名を一覧にします。どの資料にも日本語名がないものは、推測で補わずに「なし」と表示します。",
    list_country: "国",
    list_level: "階層",
    level_1: "第一級",
    level_all: "すべて",
    col_code: "コード",
    col_en: "英語名",
    col_ja: "日本語名",
    list_count: "{count}件。主な種類は「{type}」です。",
    list_count_plain: "{count}件。",
    list_gaps: "そのうち{gaps}件は、どの資料にも日本語名がありません。",
    list_full: "すべてに日本語名があります。",
    list_none: "この国には ISO 3166-2 の行政区画がありません。",
    // code
    code_title: "コードで探す",
    code_blurb: "JP-13、CA-ON、US-NY のような ISO 3166-2 のコード、または国のコード（JP、JPN、392）を入力します。大文字でも小文字でもかまいません。",
    code_code: "コード",
    code_country: "国",
    code_name_en: "英語名",
    code_name_ja: "日本語名",
    code_kind: "種類",
    code_level: "階層",
    code_parent: "上位の区画",
    code_reading: "読み",
    code_none: "該当するコードがありません。JP-13、CA-ON、US-NY、FR-75C などで試してみてください。",
  },
};
