// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/ad: the 7 subdivisions of Andorra, as a list.

import { AD } from "../data/subdivisions/ad.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Andorra, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(AD);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
