// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/ae: the 7 subdivisions of United Arab Emirates, as a list.

import { AE } from "../data/subdivisions/ae.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of United Arab Emirates, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(AE);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
