// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/am: the 11 subdivisions of Armenia, as a list.

import { AM } from "../data/subdivisions/am.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Armenia, in code order, every level: 11. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/am";
 *
 * subdivisions.length;    // 11
 * subdivisions[0].code;   // "AM-AG"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(AM);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
