// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/ao: the 18 subdivisions of Angola, as a list.

import { AO } from "../data/subdivisions/ao.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Angola, in code order, every level: 18. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/ao";
 *
 * subdivisions.length;    // 18
 * subdivisions[0].code;   // "AO-BGO"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(AO);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
