// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/ao: the 18 subdivisions of Angola, as a list.

import { AO } from "../data/subdivisions/ao.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Angola, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(AO);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
