// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/at: the 9 subdivisions of Austria, as a list.

import { AT } from "../data/subdivisions/at.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Austria, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(AT);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
