// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/az: the 78 subdivisions of Azerbaijan, as a list.

import { AZ } from "../data/subdivisions/az.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Azerbaijan, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(AZ);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
