// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/ba: the 3 subdivisions of Bosnia & Herzegovina, as a list.

import { BA } from "../data/subdivisions/ba.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Bosnia & Herzegovina, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(BA);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
