// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/bb: the 11 subdivisions of Barbados, as a list.

import { BB } from "../data/subdivisions/bb.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Barbados, in code order, every level: 11. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/bb";
 *
 * subdivisions.length;    // 11
 * subdivisions[0].code;   // "BB-01"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(BB);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
