// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/bd: the 72 subdivisions of Bangladesh, as a list.

import { BD } from "../data/subdivisions/bd.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Bangladesh, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(BD);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
