// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/be: the 13 subdivisions of Belgium, as a list.

import { BE } from "../data/subdivisions/be.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Belgium, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(BE);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
