// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/bf: the 58 subdivisions of Burkina Faso, as a list.

import { BF } from "../data/subdivisions/bf.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Burkina Faso, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(BF);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
