// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/bg: the 28 subdivisions of Bulgaria, as a list.

import { BG } from "../data/subdivisions/bg.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Bulgaria, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(BG);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
