// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/bi: the 18 subdivisions of Burundi, as a list.

import { BI } from "../data/subdivisions/bi.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Burundi, in code order, every level: 18. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/bi";
 *
 * subdivisions.length;    // 18
 * subdivisions[0].code;   // "BI-BB"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(BI);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
