// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/bj: the 12 subdivisions of Benin, as a list.

import { BJ } from "../data/subdivisions/bj.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Benin, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(BJ);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
