// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/bn: the 4 subdivisions of Brunei, as a list.

import { BN } from "../data/subdivisions/bn.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Brunei, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(BN);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
