// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/bs: the 32 subdivisions of Bahamas, as a list.

import { BS } from "../data/subdivisions/bs.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Bahamas, in code order, every level: 32. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/bs";
 *
 * subdivisions.length;    // 32
 * subdivisions[0].code;   // "BS-AK"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(BS);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
