// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/bs: the 32 subdivisions of Bahamas, as a list.

import { BS } from "../data/subdivisions/bs.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Bahamas, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(BS);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
