// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/bt: the 20 subdivisions of Bhutan, as a list.

import { BT } from "../data/subdivisions/bt.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Bhutan, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(BT);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
