// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/bw: the 16 subdivisions of Botswana, as a list.

import { BW } from "../data/subdivisions/bw.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Botswana, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(BW);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
