// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/bw: the 16 subdivisions of Botswana, as a list.

import { BW } from "../data/subdivisions/bw.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Botswana, in code order, every level: 16. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/bw";
 *
 * subdivisions.length;    // 16
 * subdivisions[0].code;   // "BW-CE"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(BW);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
