// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/bz: the 6 subdivisions of Belize, as a list.

import { BZ } from "../data/subdivisions/bz.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Belize, in code order, every level: 6. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/bz";
 *
 * subdivisions.length;    // 6
 * subdivisions[0].code;   // "BZ-BZ"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(BZ);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
