// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/cf: the 17 subdivisions of Central African Republic, as a list.

import { CF } from "../data/subdivisions/cf.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Central African Republic, in code order, every level: 17. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/cf";
 *
 * subdivisions.length;    // 17
 * subdivisions[0].code;   // "CF-AC"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(CF);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
