// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/ci: the 14 subdivisions of Côte d’Ivoire, as a list.

import { CI } from "../data/subdivisions/ci.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Côte d’Ivoire, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(CI);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
