// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/cl: the 16 subdivisions of Chile, as a list.

import { CL } from "../data/subdivisions/cl.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Chile, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(CL);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
