// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/cm: the 10 subdivisions of Cameroon, as a list.

import { CM } from "../data/subdivisions/cm.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Cameroon, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(CM);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
