// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/cu: the 16 subdivisions of Cuba, as a list.

import { CU } from "../data/subdivisions/cu.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Cuba, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(CU);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
