// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/cv: the 24 subdivisions of Cape Verde, as a list.

import { CV } from "../data/subdivisions/cv.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Cape Verde, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(CV);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
