// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/cy: the 6 subdivisions of Cyprus, as a list.

import { CY } from "../data/subdivisions/cy.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Cyprus, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(CY);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
