// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/dj: the 6 subdivisions of Djibouti, as a list.

import { DJ } from "../data/subdivisions/dj.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Djibouti, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(DJ);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
