// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/do: the 42 subdivisions of Dominican Republic, as a list.

import { DO } from "../data/subdivisions/do.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Dominican Republic, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(DO);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
