// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/dz: the 58 subdivisions of Algeria, as a list.

import { DZ } from "../data/subdivisions/dz.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Algeria, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(DZ);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
