// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/er: the 6 subdivisions of Eritrea, as a list.

import { ER } from "../data/subdivisions/er.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Eritrea, in code order, every level: 6. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/er";
 *
 * subdivisions.length;    // 6
 * subdivisions[0].code;   // "ER-AN"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(ER);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
