// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/et: the 13 subdivisions of Ethiopia, as a list.

import { ET } from "../data/subdivisions/et.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Ethiopia, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(ET);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
