// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/fi: the 19 subdivisions of Finland, as a list.

import { FI } from "../data/subdivisions/fi.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Finland, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(FI);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
