// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/fj: the 19 subdivisions of Fiji, as a list.

import { FJ } from "../data/subdivisions/fj.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Fiji, in code order, every level: 19. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/fj";
 *
 * subdivisions.length;    // 19
 * subdivisions[0].code;   // "FJ-01"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(FJ);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
