// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/fj: the 19 subdivisions of Fiji, as a list.

import { FJ } from "../data/subdivisions/fj.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Fiji, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(FJ);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
