// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/fm: the 4 subdivisions of Micronesia, as a list.

import { FM } from "../data/subdivisions/fm.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Micronesia, in code order, every level: 4. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/fm";
 *
 * subdivisions.length;    // 4
 * subdivisions[0].code;   // "FM-KSA"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(FM);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
