// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/fr: the 124 subdivisions of France, as a list.

import { FR } from "../data/subdivisions/fr.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of France, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(FR);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
