// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/ga: the 9 subdivisions of Gabon, as a list.

import { GA } from "../data/subdivisions/ga.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Gabon, in code order, every level: 9. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/ga";
 *
 * subdivisions.length;    // 9
 * subdivisions[0].code;   // "GA-1"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(GA);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
