// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/gd: the 7 subdivisions of Grenada, as a list.

import { GD } from "../data/subdivisions/gd.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Grenada, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(GD);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
