// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/ge: the 12 subdivisions of Georgia, as a list.

import { GE } from "../data/subdivisions/ge.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Georgia, in code order, every level: 12. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/ge";
 *
 * subdivisions.length;    // 12
 * subdivisions[0].code;   // "GE-AB"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(GE);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
