// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/gh: the 16 subdivisions of Ghana, as a list.

import { GH } from "../data/subdivisions/gh.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Ghana, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(GH);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
