// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/gl: the 5 subdivisions of Greenland, as a list.

import { GL } from "../data/subdivisions/gl.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Greenland, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(GL);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
