// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/gm: the 6 subdivisions of Gambia, as a list.

import { GM } from "../data/subdivisions/gm.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Gambia, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(GM);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
