// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/gn: the 41 subdivisions of Guinea, as a list.

import { GN } from "../data/subdivisions/gn.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Guinea, in code order, every level: 41. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/gn";
 *
 * subdivisions.length;    // 41
 * subdivisions[0].code;   // "GN-B"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(GN);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
