// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/gr: the 14 subdivisions of Greece, as a list.

import { GR } from "../data/subdivisions/gr.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Greece, in code order, every level: 14. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/gr";
 *
 * subdivisions.length;    // 14
 * subdivisions[0].code;   // "GR-69"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(GR);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
