// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/gw: the 12 subdivisions of Guinea-Bissau, as a list.

import { GW } from "../data/subdivisions/gw.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Guinea-Bissau, in code order, every level: 12. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/gw";
 *
 * subdivisions.length;    // 12
 * subdivisions[0].code;   // "GW-BA"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(GW);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
