// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/hr: the 21 subdivisions of Croatia, as a list.

import { HR } from "../data/subdivisions/hr.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Croatia, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(HR);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
