// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/id: the 45 subdivisions of Indonesia, as a list.

import { ID } from "../data/subdivisions/id.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Indonesia, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(ID);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
