// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/id: the 45 subdivisions of Indonesia, as a list.

import { ID } from "../data/subdivisions/id.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Indonesia, in code order, every level: 45. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/id";
 *
 * subdivisions.length;    // 45
 * subdivisions[0].code;   // "ID-AC"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(ID);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
