// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/ie: the 30 subdivisions of Ireland, as a list.

import { IE } from "../data/subdivisions/ie.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Ireland, in code order, every level: 30. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/ie";
 *
 * subdivisions.length;    // 30
 * subdivisions[0].code;   // "IE-C"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(IE);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
