// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/ie: the 30 subdivisions of Ireland, as a list.

import { IE } from "../data/subdivisions/ie.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Ireland, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(IE);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
