// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/in: the 36 subdivisions of India, as a list.

import { IN } from "../data/subdivisions/in.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of India, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(IN);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
