// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/iq: the 19 subdivisions of Iraq, as a list.

import { IQ } from "../data/subdivisions/iq.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Iraq, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(IQ);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
