// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/it: the 126 subdivisions of Italy, as a list.

import { IT } from "../data/subdivisions/it.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Italy, in code order, every level: 126. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/it";
 *
 * subdivisions.length;    // 126
 * subdivisions[0].code;   // "IT-21"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(IT);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
