// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/jo: the 12 subdivisions of Jordan, as a list.

import { JO } from "../data/subdivisions/jo.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Jordan, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(JO);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
