// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/ke: the 47 subdivisions of Kenya, as a list.

import { KE } from "../data/subdivisions/ke.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Kenya, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(KE);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
