// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/kg: the 9 subdivisions of Kyrgyzstan, as a list.

import { KG } from "../data/subdivisions/kg.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Kyrgyzstan, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(KG);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
