// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/kh: the 25 subdivisions of Cambodia, as a list.

import { KH } from "../data/subdivisions/kh.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Cambodia, in code order, every level: 25. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/kh";
 *
 * subdivisions.length;    // 25
 * subdivisions[0].code;   // "KH-1"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(KH);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
