// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/km: the 3 subdivisions of Comoros, as a list.

import { KM } from "../data/subdivisions/km.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Comoros, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(KM);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
