// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/kp: the 13 subdivisions of North Korea, as a list.

import { KP } from "../data/subdivisions/kp.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of North Korea, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(KP);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
