// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/kr: the 17 subdivisions of South Korea, as a list.

import { KR } from "../data/subdivisions/kr.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of South Korea, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(KR);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
