// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/lb: the 8 subdivisions of Lebanon, as a list.

import { LB } from "../data/subdivisions/lb.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Lebanon, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(LB);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
