// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/lc: the 10 subdivisions of St. Lucia, as a list.

import { LC } from "../data/subdivisions/lc.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of St. Lucia, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(LC);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
