// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/li: the 11 subdivisions of Liechtenstein, as a list.

import { LI } from "../data/subdivisions/li.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Liechtenstein, in code order, every level: 11. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/li";
 *
 * subdivisions.length;    // 11
 * subdivisions[0].code;   // "LI-01"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(LI);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
