// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/li: the 11 subdivisions of Liechtenstein, as a list.

import { LI } from "../data/subdivisions/li.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Liechtenstein, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(LI);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
