// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/lk: the 34 subdivisions of Sri Lanka, as a list.

import { LK } from "../data/subdivisions/lk.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Sri Lanka, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(LK);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
