// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/lr: the 15 subdivisions of Liberia, as a list.

import { LR } from "../data/subdivisions/lr.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Liberia, in code order, every level: 15. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/lr";
 *
 * subdivisions.length;    // 15
 * subdivisions[0].code;   // "LR-BG"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(LR);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
