// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/lu: the 12 subdivisions of Luxembourg, as a list.

import { LU } from "../data/subdivisions/lu.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Luxembourg, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(LU);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
