// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/md: the 37 subdivisions of Moldova, as a list.

import { MD } from "../data/subdivisions/md.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Moldova, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(MD);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
