// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/mg: the 6 subdivisions of Madagascar, as a list.

import { MG } from "../data/subdivisions/mg.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Madagascar, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(MG);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
