// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/mh: the 26 subdivisions of Marshall Islands, as a list.

import { MH } from "../data/subdivisions/mh.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Marshall Islands, in code order, every level: 26. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/mh";
 *
 * subdivisions.length;    // 26
 * subdivisions[0].code;   // "MH-ALK"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(MH);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
