// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/ml: the 11 subdivisions of Mali, as a list.

import { ML } from "../data/subdivisions/ml.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Mali, in code order, every level: 11. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/ml";
 *
 * subdivisions.length;    // 11
 * subdivisions[0].code;   // "ML-1"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(ML);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
