// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/mm: the 15 subdivisions of Myanmar (Burma), as a list.

import { MM } from "../data/subdivisions/mm.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Myanmar (Burma), in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(MM);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
