// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/mt: the 68 subdivisions of Malta, as a list.

import { MT } from "../data/subdivisions/mt.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Malta, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(MT);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
