// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/mt: the 68 subdivisions of Malta, as a list.

import { MT } from "../data/subdivisions/mt.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Malta, in code order, every level: 68. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/mt";
 *
 * subdivisions.length;    // 68
 * subdivisions[0].code;   // "MT-01"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(MT);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
