// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/mu: the 12 subdivisions of Mauritius, as a list.

import { MU } from "../data/subdivisions/mu.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Mauritius, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(MU);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
