// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/mw: the 31 subdivisions of Malawi, as a list.

import { MW } from "../data/subdivisions/mw.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Malawi, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(MW);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
