// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/mx: the 32 subdivisions of Mexico, as a list.

import { MX } from "../data/subdivisions/mx.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Mexico, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(MX);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
