// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/my: the 16 subdivisions of Malaysia, as a list.

import { MY } from "../data/subdivisions/my.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Malaysia, in code order, every level: 16. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/my";
 *
 * subdivisions.length;    // 16
 * subdivisions[0].code;   // "MY-01"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(MY);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
