// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/my: the 16 subdivisions of Malaysia, as a list.

import { MY } from "../data/subdivisions/my.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Malaysia, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(MY);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
