// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/mz: the 11 subdivisions of Mozambique, as a list.

import { MZ } from "../data/subdivisions/mz.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Mozambique, in code order, every level: 11. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/mz";
 *
 * subdivisions.length;    // 11
 * subdivisions[0].code;   // "MZ-A"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(MZ);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
