// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/na: the 14 subdivisions of Namibia, as a list.

import { NA } from "../data/subdivisions/na.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Namibia, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(NA);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
