// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/na: the 14 subdivisions of Namibia, as a list.

import { NA } from "../data/subdivisions/na.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Namibia, in code order, every level: 14. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/na";
 *
 * subdivisions.length;    // 14
 * subdivisions[0].code;   // "NA-CA"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(NA);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
