// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/ng: the 37 subdivisions of Nigeria, as a list.

import { NG } from "../data/subdivisions/ng.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Nigeria, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(NG);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
