// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/ni: the 17 subdivisions of Nicaragua, as a list.

import { NI } from "../data/subdivisions/ni.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Nicaragua, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(NI);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
