// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/nr: the 14 subdivisions of Nauru, as a list.

import { NR } from "../data/subdivisions/nr.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Nauru, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(NR);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
