// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/om: the 11 subdivisions of Oman, as a list.

import { OM } from "../data/subdivisions/om.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Oman, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(OM);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
