// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/pa: the 14 subdivisions of Panama, as a list.

import { PA } from "../data/subdivisions/pa.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Panama, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(PA);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
