// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/pe: the 26 subdivisions of Peru, as a list.

import { PE } from "../data/subdivisions/pe.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Peru, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(PE);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
