// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/pg: the 22 subdivisions of Papua New Guinea, as a list.

import { PG } from "../data/subdivisions/pg.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Papua New Guinea, in code order, every level: 22. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/pg";
 *
 * subdivisions.length;    // 22
 * subdivisions[0].code;   // "PG-CPK"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(PG);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
