// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/ph: the 99 subdivisions of Philippines, as a list.

import { PH } from "../data/subdivisions/ph.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Philippines, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(PH);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
