// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/pl: the 16 subdivisions of Poland, as a list.

import { PL } from "../data/subdivisions/pl.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Poland, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(PL);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
