// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/ps: the 16 subdivisions of Palestinian Territories, as a list.

import { PS } from "../data/subdivisions/ps.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Palestinian Territories, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(PS);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
