// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/pt: the 20 subdivisions of Portugal, as a list.

import { PT } from "../data/subdivisions/pt.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Portugal, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(PT);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
