// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/pw: the 16 subdivisions of Palau, as a list.

import { PW } from "../data/subdivisions/pw.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Palau, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(PW);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
