// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/qa: the 8 subdivisions of Qatar, as a list.

import { QA } from "../data/subdivisions/qa.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Qatar, in code order, every level: 8. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/qa";
 *
 * subdivisions.length;    // 8
 * subdivisions[0].code;   // "QA-DA"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(QA);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
