// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/qa: the 8 subdivisions of Qatar, as a list.

import { QA } from "../data/subdivisions/qa.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Qatar, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(QA);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
