// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/ro: the 42 subdivisions of Romania, as a list.

import { RO } from "../data/subdivisions/ro.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Romania, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(RO);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
