// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/rs: the 32 subdivisions of Serbia, as a list.

import { RS } from "../data/subdivisions/rs.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Serbia, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(RS);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
