// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/rw: the 5 subdivisions of Rwanda, as a list.

import { RW } from "../data/subdivisions/rw.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Rwanda, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(RW);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
