// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/sb: the 10 subdivisions of Solomon Islands, as a list.

import { SB } from "../data/subdivisions/sb.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Solomon Islands, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(SB);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
