// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/sc: the 27 subdivisions of Seychelles, as a list.

import { SC } from "../data/subdivisions/sc.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Seychelles, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(SC);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
