// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/sg: the 5 subdivisions of Singapore, as a list.

import { SG } from "../data/subdivisions/sg.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Singapore, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(SG);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
