// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/sk: the 8 subdivisions of Slovakia, as a list.

import { SK } from "../data/subdivisions/sk.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Slovakia, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(SK);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
