// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/so: the 18 subdivisions of Somalia, as a list.

import { SO } from "../data/subdivisions/so.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Somalia, in code order, every level: 18. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/so";
 *
 * subdivisions.length;    // 18
 * subdivisions[0].code;   // "SO-AW"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(SO);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
