// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/ss: the 10 subdivisions of South Sudan, as a list.

import { SS } from "../data/subdivisions/ss.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of South Sudan, in code order, every level: 10. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/ss";
 *
 * subdivisions.length;    // 10
 * subdivisions[0].code;   // "SS-BN"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(SS);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
