// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/sv: the 14 subdivisions of El Salvador, as a list.

import { SV } from "../data/subdivisions/sv.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of El Salvador, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(SV);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
