// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/sz: the 4 subdivisions of Eswatini, as a list.

import { SZ } from "../data/subdivisions/sz.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Eswatini, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(SZ);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
