// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/tg: the 5 subdivisions of Togo, as a list.

import { TG } from "../data/subdivisions/tg.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Togo, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(TG);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
