// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/th: the 78 subdivisions of Thailand, as a list.

import { TH } from "../data/subdivisions/th.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Thailand, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(TH);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
