// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/th: the 78 subdivisions of Thailand, as a list.

import { TH } from "../data/subdivisions/th.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Thailand, in code order, every level: 78. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/th";
 *
 * subdivisions.length;    // 78
 * subdivisions[0].code;   // "TH-10"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(TH);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
