// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/tj: the 5 subdivisions of Tajikistan, as a list.

import { TJ } from "../data/subdivisions/tj.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Tajikistan, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(TJ);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
