// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/tl: the 13 subdivisions of Timor-Leste, as a list.

import { TL } from "../data/subdivisions/tl.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Timor-Leste, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(TL);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
