// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/tt: the 15 subdivisions of Trinidad & Tobago, as a list.

import { TT } from "../data/subdivisions/tt.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Trinidad & Tobago, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(TT);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
