// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/tw: the 22 subdivisions of Taiwan, as a list.

import { TW } from "../data/subdivisions/tw.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Taiwan, in code order, every level: 22. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/tw";
 *
 * subdivisions.length;    // 22
 * subdivisions[0].code;   // "TW-CHA"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(TW);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
