// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/vc: the 6 subdivisions of St. Vincent & Grenadines, as a list.

import { VC } from "../data/subdivisions/vc.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of St. Vincent & Grenadines, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(VC);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
