// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/vc: the 6 subdivisions of St. Vincent & Grenadines, as a list.

import { VC } from "../data/subdivisions/vc.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of St. Vincent & Grenadines, in code order, every level: 6. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/vc";
 *
 * subdivisions.length;    // 6
 * subdivisions[0].code;   // "VC-01"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(VC);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
