// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/wf: the 3 subdivisions of Wallis & Futuna, as a list.

import { WF } from "../data/subdivisions/wf.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Wallis & Futuna, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(WF);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
