// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/wf: the 3 subdivisions of Wallis & Futuna, as a list.

import { WF } from "../data/subdivisions/wf.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

/**
 * The subdivisions of Wallis & Futuna, in code order, every level: 3. Also the default export.
 *
 * @example
 * ```ts
 * import subdivisions from "@johnmorrisdotca/kuni/subdivisions/wf";
 *
 * subdivisions.length;    // 3
 * subdivisions[0].code;   // "WF-AL"
 * ```
 */
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(WF);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
