// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/ws: the 11 subdivisions of Samoa, as a list.

import { WS } from "../data/subdivisions/ws.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Samoa, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(WS);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
