// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/za: the 9 subdivisions of South Africa, as a list.

import { ZA } from "../data/subdivisions/za.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of South Africa, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(ZA);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
