// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/zm: the 10 subdivisions of Zambia, as a list.

import { ZM } from "../data/subdivisions/zm.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Zambia, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(ZM);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
