// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivisions/zw: the 10 subdivisions of Zimbabwe, as a list.

import { ZW } from "../data/subdivisions/zw.data";
import { expandSubdivisions } from "../rows";
import type { Subdivision } from "../types";

// The subdivisions of Zimbabwe, in code order, every level.
const SUBDIVISIONS: readonly Subdivision[] = expandSubdivisions(ZW);

export default SUBDIVISIONS;
export { SUBDIVISIONS };
