// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/ad: the facts about the 7 subdivisions of Andorra.

import { AD } from "../data/subdivision-facts/ad.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Andorra, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(AD);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
