// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/al: the facts about the 12 subdivisions of Albania.

import { AL } from "../data/subdivision-facts/al.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Albania, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(AL);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
