// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/am: the facts about the 11 subdivisions of Armenia.

import { AM } from "../data/subdivision-facts/am.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Armenia, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(AM);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
