// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/ao: the facts about the 18 subdivisions of Angola.

import { AO } from "../data/subdivision-facts/ao.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Angola, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(AO);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
