// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/ar: the facts about the 24 subdivisions of Argentina.

import { AR } from "../data/subdivision-facts/ar.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Argentina, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/ar";
 *
 * facts.length;    // 24
 * facts[0].code;   // "AR-A"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(AR);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
