// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/au: the facts about the 8 subdivisions of Australia.

import { AU } from "../data/subdivision-facts/au.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Australia, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(AU);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
