// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/az: the facts about the 78 subdivisions of Azerbaijan.

import { AZ } from "../data/subdivision-facts/az.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Azerbaijan, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/az";
 *
 * facts.length;    // 78
 * facts[0].code;   // "AZ-ABS"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(AZ);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
