// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/ba: the facts about the 3 subdivisions of Bosnia & Herzegovina.

import { BA } from "../data/subdivision-facts/ba.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Bosnia & Herzegovina, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(BA);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
