// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/bb: the facts about the 11 subdivisions of Barbados.

import { BB } from "../data/subdivision-facts/bb.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Barbados, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(BB);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
