// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/bd: the facts about the 72 subdivisions of Bangladesh.

import { BD } from "../data/subdivision-facts/bd.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Bangladesh, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(BD);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
