// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/be: the facts about the 13 subdivisions of Belgium.

import { BE } from "../data/subdivision-facts/be.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Belgium, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/be";
 *
 * facts.length;    // 13
 * facts[0].code;   // "BE-BRU"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(BE);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
