// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/bh: the facts about the 4 subdivisions of Bahrain.

import { BH } from "../data/subdivision-facts/bh.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Bahrain, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(BH);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
