// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/bj: the facts about the 12 subdivisions of Benin.

import { BJ } from "../data/subdivision-facts/bj.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Benin, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/bj";
 *
 * facts.length;    // 12
 * facts[0].code;   // "BJ-AK"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(BJ);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
