// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/bn: the facts about the 4 subdivisions of Brunei.

import { BN } from "../data/subdivision-facts/bn.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Brunei, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/bn";
 *
 * facts.length;    // 4
 * facts[0].code;   // "BN-BE"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(BN);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
