// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/bo: the facts about the 9 subdivisions of Bolivia.

import { BO } from "../data/subdivision-facts/bo.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Bolivia, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/bo";
 *
 * facts.length;    // 9
 * facts[0].code;   // "BO-B"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(BO);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
