// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/bq: the facts about the 3 subdivisions of Caribbean Netherlands.

import { BQ } from "../data/subdivision-facts/bq.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Caribbean Netherlands, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/bq";
 *
 * facts.length;    // 3
 * facts[0].code;   // "BQ-BO"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(BQ);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
