// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/bw: the facts about the 16 subdivisions of Botswana.

import { BW } from "../data/subdivision-facts/bw.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Botswana, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(BW);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
