// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/bz: the facts about the 6 subdivisions of Belize.

import { BZ } from "../data/subdivision-facts/bz.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Belize, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(BZ);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
