// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/cf: the facts about the 17 subdivisions of Central African Republic.

import { CF } from "../data/subdivision-facts/cf.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Central African Republic, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/cf";
 *
 * facts.length;    // 17
 * facts[0].code;   // "CF-AC"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(CF);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
