// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/cl: the facts about the 16 subdivisions of Chile.

import { CL } from "../data/subdivision-facts/cl.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Chile, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/cl";
 *
 * facts.length;    // 16
 * facts[0].code;   // "CL-AI"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(CL);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
