// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/cm: the facts about the 10 subdivisions of Cameroon.

import { CM } from "../data/subdivision-facts/cm.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Cameroon, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/cm";
 *
 * facts.length;    // 10
 * facts[0].code;   // "CM-AD"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(CM);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
