// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/cr: the facts about the 7 subdivisions of Costa Rica.

import { CR } from "../data/subdivision-facts/cr.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Costa Rica, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/cr";
 *
 * facts.length;    // 7
 * facts[0].code;   // "CR-A"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(CR);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
