// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/cu: the facts about the 16 subdivisions of Cuba.

import { CU } from "../data/subdivision-facts/cu.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Cuba, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/cu";
 *
 * facts.length;    // 16
 * facts[0].code;   // "CU-01"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(CU);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
