// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/cy: the facts about the 6 subdivisions of Cyprus.

import { CY } from "../data/subdivision-facts/cy.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Cyprus, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/cy";
 *
 * facts.length;    // 6
 * facts[0].code;   // "CY-01"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(CY);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
