// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/cz: the facts about the 90 subdivisions of Czechia.

import { CZ } from "../data/subdivision-facts/cz.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Czechia, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(CZ);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
