// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/dj: the facts about the 6 subdivisions of Djibouti.

import { DJ } from "../data/subdivision-facts/dj.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Djibouti, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/dj";
 *
 * facts.length;    // 6
 * facts[0].code;   // "DJ-AR"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(DJ);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
