// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/do: the facts about the 42 subdivisions of Dominican Republic.

import { DO } from "../data/subdivision-facts/do.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Dominican Republic, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(DO);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
