// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/ec: the facts about the 24 subdivisions of Ecuador.

import { EC } from "../data/subdivision-facts/ec.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Ecuador, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/ec";
 *
 * facts.length;    // 24
 * facts[0].code;   // "EC-A"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(EC);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
