// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/eg: the facts about the 27 subdivisions of Egypt.

import { EG } from "../data/subdivision-facts/eg.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Egypt, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/eg";
 *
 * facts.length;    // 27
 * facts[0].code;   // "EG-ALX"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(EG);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
