// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/et: the facts about the 13 subdivisions of Ethiopia.

import { ET } from "../data/subdivision-facts/et.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Ethiopia, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(ET);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
