// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/fj: the facts about the 19 subdivisions of Fiji.

import { FJ } from "../data/subdivision-facts/fj.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Fiji, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(FJ);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
