// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/fr: the facts about the 124 subdivisions of France.

import { FR } from "../data/subdivision-facts/fr.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of France, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(FR);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
