// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/ga: the facts about the 9 subdivisions of Gabon.

import { GA } from "../data/subdivision-facts/ga.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Gabon, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/ga";
 *
 * facts.length;    // 9
 * facts[0].code;   // "GA-1"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(GA);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
