// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/gb: the facts about the 221 subdivisions of United Kingdom.

import { GB } from "../data/subdivision-facts/gb.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of United Kingdom, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/gb";
 *
 * facts.length;    // 221
 * facts[0].code;   // "GB-ABC"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(GB);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
