// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/gd: the facts about the 7 subdivisions of Grenada.

import { GD } from "../data/subdivision-facts/gd.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Grenada, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(GD);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
