// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/ge: the facts about the 12 subdivisions of Georgia.

import { GE } from "../data/subdivision-facts/ge.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Georgia, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(GE);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
