// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/gw: the facts about the 12 subdivisions of Guinea-Bissau.

import { GW } from "../data/subdivision-facts/gw.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Guinea-Bissau, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(GW);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
