// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/gy: the facts about the 10 subdivisions of Guyana.

import { GY } from "../data/subdivision-facts/gy.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Guyana, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(GY);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
