// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/hr: the facts about the 21 subdivisions of Croatia.

import { HR } from "../data/subdivision-facts/hr.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Croatia, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(HR);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
