// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/ht: the facts about the 10 subdivisions of Haiti.

import { HT } from "../data/subdivision-facts/ht.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Haiti, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(HT);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
