// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/hu: the facts about the 43 subdivisions of Hungary.

import { HU } from "../data/subdivision-facts/hu.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Hungary, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(HU);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
