// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/id: the facts about the 45 subdivisions of Indonesia.

import { ID } from "../data/subdivision-facts/id.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Indonesia, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/id";
 *
 * facts.length;    // 45
 * facts[0].code;   // "ID-AC"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(ID);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
