// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/iq: the facts about the 19 subdivisions of Iraq.

import { IQ } from "../data/subdivision-facts/iq.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Iraq, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(IQ);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
