// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/ir: the facts about the 31 subdivisions of Iran.

import { IR } from "../data/subdivision-facts/ir.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Iran, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(IR);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
