// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/is: the facts about the 72 subdivisions of Iceland.

import { IS } from "../data/subdivision-facts/is.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Iceland, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(IS);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
