// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/it: the facts about the 126 subdivisions of Italy.

import { IT } from "../data/subdivision-facts/it.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Italy, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(IT);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
