// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/jm: the facts about the 14 subdivisions of Jamaica.

import { JM } from "../data/subdivision-facts/jm.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Jamaica, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(JM);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
