// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/jp: the facts about the 47 subdivisions of Japan.

import { JP } from "../data/subdivision-facts/jp.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Japan, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/jp";
 *
 * facts.length;    // 47
 * facts[0].code;   // "JP-01"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(JP);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
