// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/kh: the facts about the 25 subdivisions of Cambodia.

import { KH } from "../data/subdivision-facts/kh.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Cambodia, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(KH);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
