// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/ki: the facts about the 3 subdivisions of Kiribati.

import { KI } from "../data/subdivision-facts/ki.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Kiribati, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(KI);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
