// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/km: the facts about the 3 subdivisions of Comoros.

import { KM } from "../data/subdivision-facts/km.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Comoros, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/km";
 *
 * facts.length;    // 3
 * facts[0].code;   // "KM-A"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(KM);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
