// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/kn: the facts about the 16 subdivisions of St. Kitts & Nevis.

import { KN } from "../data/subdivision-facts/kn.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of St. Kitts & Nevis, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/kn";
 *
 * facts.length;    // 16
 * facts[0].code;   // "KN-01"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(KN);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
