// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/kp: the facts about the 13 subdivisions of North Korea.

import { KP } from "../data/subdivision-facts/kp.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of North Korea, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(KP);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
