// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/lc: the facts about the 10 subdivisions of St. Lucia.

import { LC } from "../data/subdivision-facts/lc.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of St. Lucia, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(LC);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
