// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/lr: the facts about the 15 subdivisions of Liberia.

import { LR } from "../data/subdivision-facts/lr.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Liberia, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(LR);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
