// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/ls: the facts about the 10 subdivisions of Lesotho.

import { LS } from "../data/subdivision-facts/ls.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Lesotho, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(LS);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
