// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/lv: the facts about the 43 subdivisions of Latvia.

import { LV } from "../data/subdivision-facts/lv.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Latvia, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/lv";
 *
 * facts.length;    // 43
 * facts[0].code;   // "LV-002"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(LV);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
