// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/ma: the facts about the 87 subdivisions of Morocco.

import { MA } from "../data/subdivision-facts/ma.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Morocco, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/ma";
 *
 * facts.length;    // 87
 * facts[0].code;   // "MA-01"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(MA);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
