// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/md: the facts about the 37 subdivisions of Moldova.

import { MD } from "../data/subdivision-facts/md.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Moldova, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(MD);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
