// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/mh: the facts about the 26 subdivisions of Marshall Islands.

import { MH } from "../data/subdivision-facts/mh.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Marshall Islands, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(MH);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
