// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/mm: the facts about the 15 subdivisions of Myanmar (Burma).

import { MM } from "../data/subdivision-facts/mm.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Myanmar (Burma), in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/mm";
 *
 * facts.length;    // 15
 * facts[0].code;   // "MM-01"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(MM);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
