// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/mr: the facts about the 15 subdivisions of Mauritania.

import { MR } from "../data/subdivision-facts/mr.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Mauritania, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(MR);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
