// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/mr: the facts about the 15 subdivisions of Mauritania.

import { MR } from "../data/subdivision-facts/mr.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Mauritania, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/mr";
 *
 * facts.length;    // 15
 * facts[0].code;   // "MR-01"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(MR);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
