// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/mt: the facts about the 68 subdivisions of Malta.

import { MT } from "../data/subdivision-facts/mt.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Malta, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(MT);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
