// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/mv: the facts about the 21 subdivisions of Maldives.

import { MV } from "../data/subdivision-facts/mv.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Maldives, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(MV);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
