// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/mw: the facts about the 31 subdivisions of Malawi.

import { MW } from "../data/subdivision-facts/mw.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Malawi, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(MW);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
