// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/mx: the facts about the 32 subdivisions of Mexico.

import { MX } from "../data/subdivision-facts/mx.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Mexico, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(MX);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
