// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/ne: the facts about the 8 subdivisions of Niger.

import { NE } from "../data/subdivision-facts/ne.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Niger, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/ne";
 *
 * facts.length;    // 8
 * facts[0].code;   // "NE-1"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(NE);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
