// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/nl: the facts about the 18 subdivisions of Netherlands.

import { NL } from "../data/subdivision-facts/nl.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Netherlands, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/nl";
 *
 * facts.length;    // 18
 * facts[0].code;   // "NL-AW"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(NL);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
