// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/nr: the facts about the 14 subdivisions of Nauru.

import { NR } from "../data/subdivision-facts/nr.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Nauru, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(NR);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
