// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/nz: the facts about the 17 subdivisions of New Zealand.

import { NZ } from "../data/subdivision-facts/nz.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of New Zealand, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/nz";
 *
 * facts.length;    // 17
 * facts[0].code;   // "NZ-AUK"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(NZ);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
