// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/pk: the facts about the 7 subdivisions of Pakistan.

import { PK } from "../data/subdivision-facts/pk.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Pakistan, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(PK);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
