// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/pl: the facts about the 16 subdivisions of Poland.

import { PL } from "../data/subdivision-facts/pl.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Poland, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(PL);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
