// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/ps: the facts about the 16 subdivisions of Palestinian Territories.

import { PS } from "../data/subdivision-facts/ps.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Palestinian Territories, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(PS);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
