// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/pw: the facts about the 16 subdivisions of Palau.

import { PW } from "../data/subdivision-facts/pw.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Palau, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(PW);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
