// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/qa: the facts about the 8 subdivisions of Qatar.

import { QA } from "../data/subdivision-facts/qa.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Qatar, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(QA);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
