// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/ro: the facts about the 42 subdivisions of Romania.

import { RO } from "../data/subdivision-facts/ro.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Romania, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/ro";
 *
 * facts.length;    // 42
 * facts[0].code;   // "RO-AB"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(RO);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
