// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/ru: the facts about the 83 subdivisions of Russia.

import { RU } from "../data/subdivision-facts/ru.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Russia, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/ru";
 *
 * facts.length;    // 83
 * facts[0].code;   // "RU-AD"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(RU);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
