// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/sb: the facts about the 10 subdivisions of Solomon Islands.

import { SB } from "../data/subdivision-facts/sb.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Solomon Islands, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/sb";
 *
 * facts.length;    // 10
 * facts[0].code;   // "SB-CE"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(SB);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
