// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/sc: the facts about the 27 subdivisions of Seychelles.

import { SC } from "../data/subdivision-facts/sc.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Seychelles, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(SC);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
