// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/se: the facts about the 21 subdivisions of Sweden.

import { SE } from "../data/subdivision-facts/se.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Sweden, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/se";
 *
 * facts.length;    // 21
 * facts[0].code;   // "SE-AB"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(SE);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
