// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/ss: the facts about the 10 subdivisions of South Sudan.

import { SS } from "../data/subdivision-facts/ss.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of South Sudan, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/ss";
 *
 * facts.length;    // 10
 * facts[0].code;   // "SS-BN"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(SS);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
