// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/st: the facts about the 7 subdivisions of São Tomé & Príncipe.

import { ST } from "../data/subdivision-facts/st.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of São Tomé & Príncipe, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(ST);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
