// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/st: the facts about the 7 subdivisions of São Tomé & Príncipe.

import { ST } from "../data/subdivision-facts/st.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of São Tomé & Príncipe, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/st";
 *
 * facts.length;    // 7
 * facts[0].code;   // "ST-01"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(ST);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
