// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/sv: the facts about the 14 subdivisions of El Salvador.

import { SV } from "../data/subdivision-facts/sv.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of El Salvador, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/sv";
 *
 * facts.length;    // 14
 * facts[0].code;   // "SV-AH"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(SV);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
