// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/sz: the facts about the 4 subdivisions of Eswatini.

import { SZ } from "../data/subdivision-facts/sz.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Eswatini, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(SZ);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
