// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/tg: the facts about the 5 subdivisions of Togo.

import { TG } from "../data/subdivision-facts/tg.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Togo, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(TG);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
