// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/th: the facts about the 78 subdivisions of Thailand.

import { TH } from "../data/subdivision-facts/th.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Thailand, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/th";
 *
 * facts.length;    // 78
 * facts[0].code;   // "TH-10"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(TH);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
