// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/tl: the facts about the 13 subdivisions of Timor-Leste.

import { TL } from "../data/subdivision-facts/tl.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Timor-Leste, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/tl";
 *
 * facts.length;    // 13
 * facts[0].code;   // "TL-AL"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(TL);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
