// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/to: the facts about the 5 subdivisions of Tonga.

import { TO } from "../data/subdivision-facts/to.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Tonga, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(TO);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
