// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/tr: the facts about the 81 subdivisions of Türkiye.

import { TR } from "../data/subdivision-facts/tr.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Türkiye, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/tr";
 *
 * facts.length;    // 81
 * facts[0].code;   // "TR-01"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(TR);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
