// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/tr: the facts about the 81 subdivisions of Türkiye.

import { TR } from "../data/subdivision-facts/tr.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Türkiye, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(TR);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
