// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/tt: the facts about the 15 subdivisions of Trinidad & Tobago.

import { TT } from "../data/subdivision-facts/tt.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Trinidad & Tobago, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(TT);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
