// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/ua: the facts about the 27 subdivisions of Ukraine.

import { UA } from "../data/subdivision-facts/ua.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Ukraine, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/ua";
 *
 * facts.length;    // 27
 * facts[0].code;   // "UA-05"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(UA);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
