// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/ug: the facts about the 139 subdivisions of Uganda.

import { UG } from "../data/subdivision-facts/ug.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Uganda, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(UG);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
