// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/um: the facts about the 9 subdivisions of U.S. Outlying Islands.

import { UM } from "../data/subdivision-facts/um.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of U.S. Outlying Islands, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/um";
 *
 * facts.length;    // 9
 * facts[0].code;   // "UM-67"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(UM);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
