// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/uy: the facts about the 19 subdivisions of Uruguay.

import { UY } from "../data/subdivision-facts/uy.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Uruguay, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(UY);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
