// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/vn: the facts about the 63 subdivisions of Vietnam.

import { VN } from "../data/subdivision-facts/vn.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Vietnam, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(VN);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
