// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/wf: the facts about the 3 subdivisions of Wallis & Futuna.

import { WF } from "../data/subdivision-facts/wf.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/** The facts about the subdivisions of Wallis & Futuna, in code order, one for each subdivision, every level. */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(WF);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
