// Generated by scripts/build-data.ts. Do not edit by hand.
// The entry @johnmorrisdotca/kuni/subdivision-facts/ws: the facts about the 11 subdivisions of Samoa.

import { WS } from "../data/subdivision-facts/ws.data";
import { expandSubdivisionFacts } from "../rows";
import type { SubdivisionFacts } from "../types";

/**
 * The facts about the subdivisions of Samoa, in code order, one for each subdivision, every level. Also the default export.
 *
 * @example
 * ```ts
 * import facts from "@johnmorrisdotca/kuni/subdivision-facts/ws";
 *
 * facts.length;    // 11
 * facts[0].code;   // "WS-AA"
 * ```
 */
const SUBDIVISION_FACTS: readonly SubdivisionFacts[] = expandSubdivisionFacts(WS);

export default SUBDIVISION_FACTS;
export { SUBDIVISION_FACTS };
