// Generated by scripts/build-data.ts. Do not edit by hand: change the script or its inputs and run pnpm data.
// The 31 withdrawn countries of ISO 3166-3, one object each.
// Source: Wikidata (CC0), the snapshot data-sources/wikidata-codes-2026-10-10.json: the codes, names, years and successors
// Source: scripts/withdrawn-config.ts (MIT): the few codes, years, names and successors Wikidata does not give, with the reasons

import type { WithdrawnRow } from "../rows";

const WITHDRAWN_ROWS: readonly WithdrawnRow[] = [
  {"code":"AIDJ","alpha2":"AI","alpha3":"AFI","numeric":"262","en":"French Territory of the Afars and the Issas","ja":"フランス領アファル・イッサ","since":"1974","until":"1977","successors":["DJ"],"reusedBy":"AI"},
  {"code":"ANHH","alpha2":"AN","alpha3":"ANT","numeric":"530","en":"Netherlands Antilles","ja":"オランダ領アンティル","since":"1974","until":"2010","successors":["BQ","CW","SX"],"reusedBy":null},
  {"code":"BQAQ","alpha2":"BQ","alpha3":"ATB","numeric":null,"en":"British Antarctic Territory","ja":"イギリス領南極地域","since":"1974","until":"1979","successors":["AQ"],"reusedBy":"BQ"},
  {"code":"BUMM","alpha2":"BU","alpha3":"BUR","numeric":"104","en":"Burma","ja":"ビルマ","since":"1974","until":"1989","successors":["MM"],"reusedBy":null},
  {"code":"BYAA","alpha2":"BY","alpha3":"BYS","numeric":"112","en":"Byelorussian Soviet Socialist Republic","ja":"ベラルーシ・ソビエト社会主義共和国","since":"1974","until":"1992","successors":["BY"],"reusedBy":"BY"},
  {"code":"CSHH","alpha2":"CS","alpha3":"CSK","numeric":"200","en":"Czechoslovakia","ja":"チェコスロバキア","since":"1974","until":"1993","successors":["CZ","SK"],"reusedBy":null},
  {"code":"CSXX","alpha2":"CS","alpha3":"SCG","numeric":"891","en":"Serbia and Montenegro","ja":"セルビア・モンテネグロ","since":"2003","until":"2006","successors":["ME","RS"],"reusedBy":null},
  {"code":"CTKI","alpha2":"CT","alpha3":"CTE","numeric":"128","en":"Canton and Enderbury Islands","ja":null,"since":"1974","until":"1984","successors":["KI"],"reusedBy":null},
  {"code":"DDDE","alpha2":"DD","alpha3":"DDR","numeric":"278","en":"East Germany","ja":"東ドイツ","since":"1974","until":"1990","successors":["DE"],"reusedBy":null},
  {"code":"DYBJ","alpha2":"DY","alpha3":"DHY","numeric":"204","en":"Republic of Dahomey","ja":"ダホメ共和国","since":"1974","until":"1977","successors":["BJ"],"reusedBy":null},
  {"code":"FQHH","alpha2":"FQ","alpha3":"ATF","numeric":null,"en":"French Southern and Antarctic Lands","ja":"フランス領南方・南極地域","since":"1974","until":"1979","successors":["AQ","TF"],"reusedBy":null},
  {"code":"FXFR","alpha2":"FX","alpha3":"FXX","numeric":"249","en":"Metropolitan France","ja":"フランス本土","since":"1993","until":"1997","successors":["FR"],"reusedBy":null},
  {"code":"GEHH","alpha2":"GE","alpha3":"GEL","numeric":null,"en":"Gilbert and Ellice Islands","ja":"ギルバート・エリス諸島","since":"1974","until":"1979","successors":["KI"],"reusedBy":"GE"},
  {"code":"HVBF","alpha2":"HV","alpha3":"HVO","numeric":"854","en":"Republic of Upper Volta","ja":"オートボルタ","since":"1974","until":"1984","successors":["BF"],"reusedBy":null},
  {"code":"JTUM","alpha2":"JT","alpha3":"JTN","numeric":"396","en":"Johnston Atoll","ja":"ジョンストン島","since":"1974","until":"1986","successors":["UM"],"reusedBy":null},
  {"code":"MIUM","alpha2":"MI","alpha3":"MID","numeric":"488","en":"Midway Atoll","ja":"ミッドウェー島","since":"1974","until":"1986","successors":["UM"],"reusedBy":null},
  {"code":"NHVU","alpha2":"NH","alpha3":"NHB","numeric":null,"en":"New Hebrides","ja":"ニューヘブリディーズ諸島","since":"1974","until":"1980","successors":["VU"],"reusedBy":null},
  {"code":"NQAQ","alpha2":"NQ","alpha3":"ATN","numeric":"216","en":"Queen Maud Land","ja":"ドローニング・モード・ランド","since":"1974","until":"1983","successors":["AQ"],"reusedBy":null},
  {"code":"NTHH","alpha2":"NT","alpha3":"NTZ","numeric":"536","en":"Saudi–Iraqi Neutral Zone","ja":"サウジアラビア・イラク中立地帯","since":"1974","until":"1993","successors":["IQ","SA"],"reusedBy":null},
  {"code":"PCHH","alpha2":"PC","alpha3":"PCI","numeric":"582","en":"Trust Territory of the Pacific Islands","ja":"太平洋諸島信託統治領","since":"1974","until":"1986","successors":["FM","MH","MP","PW"],"reusedBy":null},
  {"code":"PUUM","alpha2":"PU","alpha3":"PUS","numeric":"849","en":"United States Miscellaneous Pacific Islands","ja":null,"since":"1974","until":"1986","successors":["UM"],"reusedBy":null},
  {"code":"PZPA","alpha2":"PZ","alpha3":"PCZ","numeric":null,"en":"Panama Canal Zone","ja":"パナマ運河地帯","since":"1974","until":"1980","successors":["PA"],"reusedBy":null},
  {"code":"RHZW","alpha2":"RH","alpha3":"RHO","numeric":null,"en":"Southern Rhodesia","ja":"南ローデシア","since":"1974","until":"1980","successors":["ZW"],"reusedBy":null},
  {"code":"SKIN","alpha2":"SK","alpha3":"SKM","numeric":null,"en":"Kingdom of Sikkim","ja":"シッキム王国","since":"1974","until":"1975","successors":["IN"],"reusedBy":"SK"},
  {"code":"SUHH","alpha2":"SU","alpha3":"SUN","numeric":"810","en":"Soviet Union","ja":"ソビエト連邦","since":"1974","until":"1992","successors":["AM","AZ","EE","GE","KZ","KG","LV","LT","MD","RU","TJ","TM","UZ"],"reusedBy":null},
  {"code":"TPTL","alpha2":"TP","alpha3":"TMP","numeric":"626","en":"East Timor","ja":"東ティモール","since":"1974","until":"2002","successors":["TL"],"reusedBy":null},
  {"code":"VDVN","alpha2":"VD","alpha3":"VDR","numeric":null,"en":"North Vietnam","ja":"北ベトナム","since":"1974","until":"1977","successors":["VN"],"reusedBy":null},
  {"code":"WKUM","alpha2":"WK","alpha3":"WAK","numeric":"872","en":"Wake Island","ja":"ウェーク島","since":"1974","until":"1986","successors":["UM"],"reusedBy":null},
  {"code":"YDYE","alpha2":"YD","alpha3":"YMD","numeric":"720","en":"South Yemen","ja":"南イエメン","since":"1974","until":"1990","successors":["YE"],"reusedBy":null},
  {"code":"YUCS","alpha2":"YU","alpha3":"YUG","numeric":"891","en":"Yugoslavia","ja":"ユーゴスラビア","since":"1974","until":"2003","successors":["CS"],"reusedBy":null},
  {"code":"ZRCD","alpha2":"ZR","alpha3":"ZAR","numeric":"180","en":"Zaire","ja":"ザイール","since":"1974","until":"1997","successors":["CD"],"reusedBy":null},
];

/**
 * The day the Wikidata snapshot of the withdrawn codes was read.
 *
 * @example
 * ```ts
 * import { WITHDRAWN_READ } from "@johnmorrisdotca/kuni/withdrawn";
 *
 * WITHDRAWN_READ; // "2026-10-10"
 * ```
 */
const WITHDRAWN_READ = "2026-10-10";

export { WITHDRAWN_READ, WITHDRAWN_ROWS };
